<div class="home-content-box">
    <h2 class="lead">Redesign 2015</h2>
    <p>
        Jusbib erscheint im Frühling 2015 in einem neuen Kleid. Das Responsive Design passt sich dynamisch der Bildschirmgrösse diverser Endgeräte an, Sie können damit swissbib ohne Einschränkungen auf dem Smartphone, dem Tablet oder dem PC nutzen.
    </p>

    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.swissbib.blogspot.ch/') ?>" target="_blank" class="btn btn-link" title="Link zum Blog">Mehr erfahren</a>
</div>

