<?php
/** @var String[] $pages List of pages/keys */
/** @var Boolean $first Route directly matched to content */
/** @var String $topic Active topic */

$this->headTitle($this->translate('helppage') . ' - ' . $this->translate('helppage.' . $topic));
?>

<!-- end: col1 (sidebar) -->
<div class="<?= $this->layoutClass('mainbody') ?>">

  <?php if (!$first): ?>
    <p class="notFirstMatchWarning"><?=$this->transEsc('helppage.notFirstMatchWarning')?></p>
  <?php endif; ?>

	<?=$this->helpContent;?>
</div>
<!-- end: col3 (content) -->

<!-- begin: col1 (sidebar)  -->
<div class="<?= $this->layoutClass('sidebar') ?>">
  <h4><?=$this->transEsc('helppage.subtitle')?></h4>
  <ul class="list-group">
    <?php foreach ($pages as $page): ?>
      <a href="<?=$this->url('help-page', array('topic' => ucfirst($page)))?>" title="" class="list-group-item<?=($page===$topic?' active':'')?>">
        <?=$this->transEsc('helppage.' . $page)?>
      </a>
    <?php endforeach; ?>
  </ul>
</div>

