<div class="home-content-box">
    <h2 class="lead">Redesign 2015</h2>
    <p>
        Swissbib adopte au printemps 2015 un nouveau visage. Son design s’adapte de manière dynamique aux écrans de tous les périphériques,
        vous permettant de l’utiliser confortablement sur votre smartphone, votre tablette ou votre ordinateur.
    </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.swissbib.blogspot.ch/') ?>" target="_blank" class="btn btn-link" title="Blog">Più info</a>
</div>