<div class="home-content-box">
    <h2 class="lead">A proposito di swissbib</h2>
    <p>
        Swissbib è il catalogo delle Biblioteche universitarie svizzere e della Biblioteca nazionale svizzera. Offre un accesso rapido, semplice e completo all'informazione scientifica.
    </p>
    <a href="<?= $this->basePath('Libraries') ?>" class="btn btn-link" title="Istituzione">Istituzione participante</a>
</div>
