<div class="home-content-box">
    <h2 class="lead">Redesign 2015</h2>
    <p>
        Dalla primavera 2015, swissbib si presenta con una nuova faccia. Il suo design si adatta dinamicamente agli schermi dei differenti
        dispositivi, la qual cosa consente di utilizzarlo comodamente sia con lo smartphone come con il tablet o con il computer.
    </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.swissbib.blogspot.ch/') ?>" target="_blank" class="btn btn-link" title="Blog">Più info</a>
</div>