<?
$record         = $this->driver;
$viewRecord     = $this->record($record);

$shortTitle           = $record->getShortTitle();
$titleStatement       = $record->getTitleStatement(true);
$subtitle             = $viewRecord->getSubtitle($titleStatement);
$responsible          = $viewRecord->getResponsible($titleStatement, $record);
$publications         = $record->getPublicationDetails();
$physicalDescriptions = $record->getPhysicalDescriptions(false);
$edition              = $record->getEdition();
$cartMathData         = $record->getCartMathData();
$formats              = $viewRecord->getFormatList();
$hostitems            = $record->getHostItemEntry();
$journalTitle         = $record->getContainerTitle();
$ref                  = $record->getContainerReference();
$highlightedFulltext  = $record->getHighlightedFulltext();

$showFRBR = $this->configAccess()->Site->displayFrbr;
$groupID  = $this->driver->getGroup(true);
$theme    = $this->configAccess()->Site->theme;
?>

<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
    <!-- main / short title -->
    <div class="col-sm-12">
        <h3 property="name"><?=$this->escapeHtml($shortTitle)?></h3>
    </div>

    <div class="col-sm-4 hidden-xs">
        <div>
        <? /* Display thumbnail if appropriate: */ ?>
        <? $mediumThumb = $this->record($this->driver)->getThumbnail('medium'); $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
        <? if ($mediumThumb): ?>
        <? if ($largeThumb): ?><a href="<?=$this->escapeHtmlAttr($largeThumb)?>"><? endif; ?>
          <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($mediumThumb);?>"/>
        <? if ($largeThumb): ?></a><? endif; ?>
      <? else: ?>
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

        <? // if you have a preview tab but want to move or remove the preview link
        // from this area of the record view, this can be split into
        // getPreviewData() (should stay here) and
        // getPreviewLink() (can go in your desired tab) ?>
        <?=$this->record($this->driver)->getPreviews()?>
  </div>

  <div class="col-sm-8 col-xs-12">
    <? if (isset($subtitle)): ?>
      <h4 class="resultViewSubTitle"><?= $this->escapeHtml($subtitle) ?></h4>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
    <? if (!empty($responsible)): ?>
        <!-- Verfasser / Beitragende -->
        <tr>
            <th><?=$this->transEsc('Author')?>: </th>
            <td property="author"><?=$this->escapeHtml($responsible)?></td>
        </tr>
    <? endif; ?>

    <!-- Impressum -->
    <? if (!empty($publications)): ?>
        <tr>
            <th><?=$this->transEsc('Publication')?>: </th>
            <td>
                <? foreach ($publications as $field): ?>
                    <span property="publisher" typeof="Organization">
                        <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
                            <span property="location"><?=$this->escapeHtml($pubPlace)?> :</span>
                        <? endif; ?>
                        <? $pubName = $field->getName(); if (!empty($pubName)): ?>
                            <span property="name"> <?=$this->escapeHtml($pubName)?>, </span>
                        <? endif; ?>
                    </span>
                    <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
                        <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
                    <? endif; ?>
                    <br/>
                <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <? if (!empty($journalTitle)): ?>
      <tr>
        <th><?=$this->transEsc('Journal Title')?>:</th>
        <td>
          <a href="<?= $viewRecord->getLink('journaltitle', $journalTitle)?>"><?=$this->escapeHtml($journalTitle)?></a>
          <? if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
        </td>
      </tr>
      <? endif; ?>

      <? if ($hostitems): ?>
      <tr>
        <th><?= $this->transEsc('note_773') ?>: </th>
        <td>
            <? foreach ($hostitems as $hostitem): ?>
                <? $text = array_key_exists('related', $hostitem) ? $hostitem['title'] . ', ' . $hostitem['related'] : $hostitem['title'] ?>
                <?= $this->escapeHtml($text) ?><br />
            <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <?php if ($cartMathData): ?>
      <tr>
        <th><?= $this->transEsc('Map_Scale') ?>:</th>
        <td><?= $this->escapeHtml($cartMathData) ?></td>
      </tr>
      <?php endif; ?>

      <?php if ($physicalDescriptions): ?>
      <tr>
        <th><?= $this->transEsc('Physical Description') ?>:</th>
        <td><?= $this->physicalDescription($physicalDescriptions) ?></td>
      </tr>
      <?php endif; ?>

      <? if (!empty($formats)): ?>
        <tr>
          <th><?=$this->transEsc('Format')?>: </th>
          <td><?= $formats ?></td>
        </tr>
      <? endif; ?>

      <? if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td property="bookEdition"><?=$this->escapeHtml($edition)?></td>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->driver->openURLActive('record') ? $this->driver->getOpenURL() : false;
        // Account for replace_other_urls setting
        $urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->record($this->driver)->getLinkDetails();
      ?>
      <? if (!empty($urls) || $openUrl): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
          <? if ($openUrl): ?>
            <?=$this->openUrl($openUrl)?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <?php if (!empty($showFRBR) && $showFRBR && !empty($groupID)) : ?>
       <tr>
         <th></th>
         <td>
           <a href="<?=
            $this->url('search-results') . '?lookfor=' . $groupID . "&type=FRBR"
            . "&sort=publishDateSort+desc" ?>"
               class="btn btn-default icon_show" title="<?= $this->transEsc('FRBR_Button') ?>">
                <span class="hidden-xs"><?= $this->transEsc('FRBR_Button') ?></span>
            </a>
         </td>
       </tr>
      <?php endif; ?>

    </table>
    <?/* End Main Details */?>
  </div>
</div>
