<?
$record         = $this->driver;
$viewRecord     = $this->record($record);

$shortTitle     = $record->getShortTitle();
$titleStatement = $record->getTitleStatement(true);
$subtitle       = $viewRecord->getSubtitle($titleStatement);
$responsible    = $viewRecord->getResponsible($titleStatement, $record);
$publications   = $record->getPublicationDetails();

?>

<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
    <!-- main / short title -->
    <div class="col-sm-12">
        <h3 property="name"><?=$this->escapeHtml($shortTitle)?></h3>
    </div>

    <div class="col-sm-4 hidden-xs">
        <div class="text-center">
        <? /* Display thumbnail if appropriate: */ ?>
        <? $mediumThumb = $this->record($this->driver)->getThumbnail('medium'); $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
        <? if ($mediumThumb): ?>
        <? if ($largeThumb): ?><a href="<?=$this->escapeHtmlAttr($largeThumb)?>"><? endif; ?>
          <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($mediumThumb);?>"/>
        <? if ($largeThumb): ?></a><? endif; ?>
      <? else: ?>
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <?=$this->record($this->driver)->getPreviews()?>

    <? $theme = $this->configAccess()->Site->theme; ?>
  </div>

  <div class="col-sm-8 col-xs-12">
    <? if (isset($subtitle)): ?>
      <h4 class="resultViewSubTitle"><?= $this->escapeHtml($subtitle) ?></h4>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
    <? if (!empty($responsible)): ?>
        <!-- Verfasser / Beitragende -->
        <tr>
            <th><?=$this->transEsc('Author')?>: </th>
            <td property="author"><?=$this->escapeHtml($responsible)?></td>
        </tr>
    <? endif; ?>

    <!-- Impressum -->
    <? if (!empty($publications)): ?>
        <tr>
            <th><?=$this->transEsc('Publication')?>: </th>
            <td>
                <? foreach ($publications as $field): ?>
                    <span property="publisher" typeof="Organization">
                        <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
                            <span property="location"><?=$this->escapeHtml($pubPlace)?> :</span>
                        <? endif; ?>
                        <? $pubName = $field->getName(); if (!empty($pubName)): ?>
                            <span property="name"> <?=$this->escapeHtml($pubName)?>, </span>
                        <? endif; ?>
                    </span>
                    <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
                        <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
                    <? endif; ?>
                    <br/>
                <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>



      <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
      <tr>
        <th><?=$this->transEsc('Journal Title')?>:</th>
        <td>
          <a href="<?=$this->record($this->driver)->getLink('journaltitle', $journalTitle)?>"><?=$this->escapeHtml($journalTitle)?></a>
          <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
        </td>
      </tr>
      <? endif; ?>

      <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <? if (!empty($nextTitles)): ?>
      <tr>
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <? foreach($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($prevTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <? foreach($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $hostitems=$this->driver->getHostItemEntry(); ?>
      <? if ($hostitems): ?>
      <tr>
        <th><?= $this->transEsc('note_773') ?>: </th>
        <td>
            <? foreach ($hostitems as $hostitem): ?>
                <? $text = array_key_exists('related', $hostitem) ? $hostitem['title'] . ', ' . $hostitem['related'] : $hostitem['title'] ?>
                <?= $this->escapeHtml($text) ?><br />
            <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $cartMathData=$this->driver->getCartMathData(); ?>
      <?php if ($cartMathData): ?>
      <tr>
        <th><?= $this->transEsc('Map_Scale') ?>:</th>
        <td><?= $this->escapeHtml($cartMathData) ?></td>
      </tr>
      <?php endif; ?>

      <? $physicalDescriptions=$this->driver->getPhysicalDescriptions(false); ?>
      <?php if ($physicalDescriptions): ?>
      <tr>
        <th><?= $this->transEsc('Physical Description') ?>:</th>
        <td><?= $this->physicalDescription($physicalDescriptions) ?></td>
      </tr>
      <?php endif; ?>

      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <tr>
          <th><?=$this->transEsc('Format')?>: </th>
          <td><?=$this->record($this->driver)->getFormatList()?></td>
        </tr>
      <? endif; ?>

      <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td property="bookEdition"><?=$this->escapeHtml($edition)?></td>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->driver->openURLActive('record') ? $this->driver->getOpenURL() : false;
        // Account for replace_other_urls setting
        $urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->record($this->driver)->getLinkDetails();
      ?>
      <? if (!empty($urls) || $openUrl): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
          <? if ($openUrl): ?>
            <?=$this->openUrl($openUrl)?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if(!empty($recordLinks)): ?>
        <tr>
          <th><?=$this->transEsc('Related Items')?>:</th>
          <td>
            <? foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <? endforeach; ?>
            <? /* if we have record links, display relevant explanatory notes */
              $related = $this->driver->getRelationshipNotes();
              if (!empty($related)): ?>
                <? foreach ($related as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
                <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <?
         $showFRBR = $this->configAccess()->Site->displayFrbr;
         $groupID              = $this->driver->getGroup(true);
      ?>
      <?php if (!empty($showFRBR) && $showFRBR && !empty($groupID)) : ?>
       <tr>
         <th></th>
         <td>
           <a href="<?=
            $this->url('search-results') . '?lookfor=' . $groupID . "&type=FRBR"
            . "&sort=publishDateSort+desc" ?>"
               class="btn btn-default icon_show" title="<?= $this->transEsc('FRBR_Button') ?>">
                <span class="hidden-xs"><?= $this->transEsc('FRBR_Button') ?></span>
            </a>
         </td>
       </tr>
      <?php endif; ?>

    </table>
    <?/* End Main Details */?>
  </div>
</div>
