<?
  /** @var    Swissbib\RecordDriver\SolrMarc $record */
  /** @var    VuFind\View\Helper\Root\Record $viewRecord */
  $record = $this->driver;
  $viewRecord = $this->record($this->driver);
  $thumbnail = $viewRecord->getThumbnail('small');
  $thumbnailSrc = $thumbnail ? $thumbnail : $this->url('cover-unavailable');
  $detailLink = $this->recordLink()->getUrl($record);
  $titleStatement = $record->getTitleStatement(true);
  $shortTitle = $record->getShortTitle();
    if (!empty($shortTitle)) {
        $shortTitle = $this->escapeHtml($shortTitle);
    }
    else {
        $shortTitle = $this->transEsc('Title not available');
    };
  $subtitle = $viewRecord->getSubtitle($titleStatement);
  $responsible = $viewRecord->getResponsible($titleStatement, $record);
  $edition = $record->getEdition();
  $summDate= $record->getHumanReadablePublicationDates();
  $hostitems = $record->getHostItemEntry();
  $groupID = $record->getGroup(true);
  $uniqueID = $record->getUniqueID();
  $showFRBR = $this->configAccess()->Site->displayFrbr;
  $memorizeLink = $this->recordLink()->getActionUrl($this->driver, 'Save');
  $formats = $viewRecord->getFormatList();

  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getResourceSource();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->id;
    $user_id = $this->list->user_id;
  } else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
  }
?>

<div class="row result">
    <div class="col-sm-1 hidden-print">
        <label class="pull-left"><?=$viewRecord->getCheckbox() ?></label>
        <input type="hidden" value="<?=$id ?>" class="hiddenId"/>
    </div>
    <div class="col-sm-2 hidden-xs left no-gutter hidden-print">
        <a href="<?=$this->recordLink()->getUrl($record)?>" class="title img-responsive">
        <? if (!($thumbnail === false)): ?>
            <img class="recordcover" src="<?= $thumbnail ?>" />
        <? else: ?>
            <div class="thumbico <?= $viewRecord->getThumbnailPlaceholder() ?>"></div>
        <? endif; ?>
        </a>
    </div>
    <div class="col-sm-6 col-xs-10 middle">
        <h2>
            <a class="title" title="<?= $shortTitle ?>" href="<?=$this->recordLink()->getUrl($record)?>"><?= $shortTitle ?></a>
        </h2>

        <div class="meta">
            <? if (isset($subtitle)): ?>
            <?= $this->escapeHtml($subtitle) ?><br />
            <? endif; ?>
            <? if ($responsible): ?>
                <span class="hidden-xs"><strong><?= $this->transEsc('Author') ?>:</strong></span>
                <span>
                    <?= $this->escapeHtml($responsible) ?>
                </span><br />
            <? endif; ?>
        </div>

    <!-- Zeitschriftentitel, Erscheinungsjahr -->
    <div class="meta">
        <? if (!empty($hostitems)): ?>
            <? foreach ($hostitems as $hostitem): ?>
                <span class="hidden-xs label"><strong><?= $this->transEsc('note_773') ?>:</strong></span>
                <? $text = array_key_exists('related', $hostitem) ? $hostitem['title'] . ', ' . $hostitem['related'] : $hostitem['title'] ?>
                <span><?= $this->escapeHtml($text) ?></span><br />
            <? endforeach; ?>
        <? endif; ?>
        <? if (!empty($journalTitle)): ?>
            <span class="hidden-xs label"><strong><?= $this->transEsc('Published in')?>:</strong></span>
            <span><a href="<?= $viewRecord->getLink('journaltitle', $journalTitle)?>"><?= $this->escapeHtml($journalTitle)?></a></span><br />
        <? endif; ?>
        <? if (!empty($summDate)): ?>
            <span class="hidden-xs label"><strong><?= $this->transEsc('Year') ?>:</strong></span>
            <span><?= $this->escapeHtml($summDate[0]) ?></span><br />
        <? endif; ?>
        <? if (!empty($edition)): ?>
            <span class="hidden-xs label"><strong><?= $this->transEsc('Edition') ?>:</strong></span>
            <span><?= $this->escapeHtml($edition) ?></span><br />
        <? endif; ?>
        <!-- ID -->
        <? if (!empty($uniqueID)): ?>
          <span class="visible-print-inline">
            <span class="hidden-xs label"><strong><?= $this->transEsc('Item_ID') ?>:</strong></span>
            <span><?= $uniqueID ?></span>
          </span>
          <br class="visible-print-inline"/>
        <? endif; ?>
        <!-- Medien-Typ -->
        <? if (!empty($formats)): ?>
          <span class="hidden-xs label"><strong><?= $this->transEsc('Format') ?>:</strong></span>
          <span><?= $formats ?></span><br />
        <? endif; ?>
        <br />
    </div>

    <div class="last">
    <? $listTags = ($this->usertags()->getMode() !== 'disabled') ? $this->driver->getTags(
        $list_id, // get tags for all lists if no single list is selected
        $user_id, 'tag'
       ) : array();
    ?>
    <? if (count($listTags) > 0): ?>
      <strong><?=$this->transEsc('Your Tags')?>:</strong>
      <? $i = 0; foreach ($listTags as $tag): ?><? ($i++ == 0)?><a href="<?=$this->currentPath() . $results->getUrlQuery()->addFacet('tags', $tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a><? endforeach; ?>
      <br/>
    <? endif; ?>
    <? $listNotes = $this->driver->getListNotes($list_id, $user_id); ?>
    <? if (count($listNotes) > 0): ?>
      <strong><?=$this->transEsc('Notes')?>:</strong>
      <? if (count($listNotes) > 1): ?><br/><? endif; ?>
      <? foreach ($listNotes as $note): ?>
        <?=$this->escapeHtml($note)?><br/>
      <? endforeach; ?>
    <? endif; ?>

    <? if (count($this->lists) > 0): ?>
        <strong><?=$this->transEsc('Saved in')?>:</strong>
        <? $i=0;foreach($this->lists as $current): ?>
            <a href="<?=$this->url('userList', array('id' => $current->id))?>"><?=$current->title?></a><? if($i++ < count($this->lists)-1): ?><? endif; ?>
        <? endforeach; ?>
    <? endif; ?>

        <?
        $openUrl = $this->driver->openURLActive('record') ? $this->driver->getOpenURL() : false;
        // Account for replace_other_urls setting
        $urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->record($this->driver)->getLinkDetails();
        ?>
    <? /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
            but even if we don't plan to display the link, we still want to get the $openUrl
            value for use in generating a COinS (Z3988) tag -- see bottom of file.

        $openUrl = $this->driver->getOpenURL();
        $openUrlActive = $this->driver->openURLActive('results');
        $urls = $this->record($this->driver)->getLinkDetails();
        if ($openUrlActive || !empty($urls)):
      ?>
        <? if ($openUrlActive): ?>
          <br/>
          <?=$this->openUrl($openUrl)?>
          <?
            if ($this->driver->replaceURLsWithOpenURL()) {
              // clear URL list if replace setting is active
              $urls = array();
            }
          ?>
        <? endif;?>

        <? if (!is_array($urls)) { $urls = array(); }
          if(!$this->driver->isCollection()):
            foreach ($urls as $current): ?>
              <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" class="fulltext" target="new"><i class="fa fa-external-link"></i> <?=($current['url'] == $current['desc']) ? $this->transEsc('Get full text') : $this->escapeHtml($current['desc'])?></a>
            <? endforeach; ?>
          <? endif; ?>
        <? endif; */?>
      <br/>


      <? if (/*!$openUrlActive && */ empty($urls) && $this->driver->supportsAjaxStatus()): ?>
        <span class="status ajax-availability hidden"><?=$this->transEsc('Loading')?>...</span>
        <br/><br/>
      <? endif; ?>
      <?=$this->record($this->driver)->getPreviews()?>
    </div>
  </div>

  <div class="col-xs-2 right hidden-print">
    <a href="<?=$this->url('myresearch-edit')?>?id=<?=urlencode($id)?>&amp;source=<?=urlencode($source)?><? if (!is_null($list_id)):?>&amp;list_id=<?=urlencode($list_id)?><? endif; ?>" class="edit tool"><i class="fa fa-edit"></i><?=$this->transEsc('Edit')?></a><br/>
    <? /* Use a different delete URL if we're removing from a specific list or the overall favorites: */
      $deleteUrl = is_null($list_id)
          ? $this->url('myresearch-favorites')
          : $this->url('userList', array('id' => $list_id));
      $deleteUrlGet = $deleteUrl . '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);
    ?>
    <div class="dropdown">
      <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="<?=$deleteUrlGet ?>"><i class="fa fa-trash-o"></i>
        <?=$this->transEsc('Delete') ?>
      </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li><a onClick="$.post('<?=$deleteUrl?>', {'delete':'<?=$this->escapeHtmlAttr($id) ?>','source':'<?=$this->escapeHtmlAttr($source) ?>','confirm':true},function(){location.reload(true)})" title="<?=$this->transEsc('confirm_delete_brief')?>"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
        <li><a><?=$this->transEsc('confirm_dialog_no')?></a></li>
      </ul>
    </div>
  </div>
    <span class="Z3988" title="<?= $this->escapeHtml($record->getOpenURL()) ?>"></span>
</div>
