<h1>Il progetto swissbib</h1>
<p>
    Swissbib è un progetto nazionale, finanziato dalla Conferenza universitaria svizzera e da swissuniversities nel quadro
    del programma <a href="<?= $this->redirectProtocolwrapper()->getWrappedURL('http://www.swissuniversities.ch/it/organisation/projekte-und-programme/suk-p-2-wissensch-information-zugang-verarbeitung-speicherung')?>"
                     target="_blank">P-2 "Informazione scientifica: accesso, trattamento e conservazione"</a>. Il progetto
    è in capo alla <a href="https://ub.unibas.ch" target="_blank">Biblioteca universitaria di Basilea</a>. Per il periodo
    2008-2013, swissbib è stato reso possibile grazie al finanziamento del programma di innovazione e cooperazione
    <a href="<?= $this->redirectProtocolwrapper()->getWrappedURL('http://www.e-lib.ch')?>" target="_blank">"e-lib.ch : Biblioteca elettronica svizzera"</a>.
</p>

<h2>Reti di biblioteche e archivi digitali che vi partecipano</h2>
<p>
    Di seguito sono elencati i sistemi bibliotecari, gli archivi digitali e le collezioni che partecipano a swissbib. E’ la
    loro disponibilità a fornire i dati e il sostegno fornito a differenti livelli che permette l'esistenza di swissbib:
</p>
<ul class="list">
    <li>Réseaux IDS – Informationsverbund Deutschschweiz</li>
    <ul>
        <li>IDS Basel Bern</li>
        <li>NEBIS</li>
        <li>IDS Luzern</li>
        <li>IDS St. Gallen</li>
    </ul>
    <li>Biblioteca nazionale svizzera</li>
    <li>RERO - Réseau des bibliothèques de Suisse occidentale</li>
    <li>SBT - Sistema bibliotecario ticinese</li>
    <li>Réseau de bibliothèques Alexandria</li>
    <li>Aargauer Bibliotheksnetz</li>
    <li>Bibliotheksverbund Graubünden</li>
    <li>St. Galler Bibliotheksnetz</li>
    <li>Liechtensteiner Bibliotheken</li>
    <li>retro.seals.ch – periodici digitalizzati</li>
    <li>e-codices - Biblioteca virtuale dei manoscritti conservati in Svizzera</li>
    <li>ZORA - Zurich Open Repository and Archive</li>
    <li>Collezioni della Biblioteca nazionale</li>
    <ul>
        <li>Catalogo collettivo svizzero dei manifesti</li>
        <li>Archivio svizzero di letteratura</li>
        <li>Archivio federale dei monumenti storici</li>
    </ul>
</ul>
<p>
    Le seguenti collezioni dovrebbero essere integrate in swissbib nel 2015-2016:
</p>
<ul class="list">
    <li>Bibliotheken Schaffhausen</li>
    <li>Bibliotheken Thurgau</li>
    <li>E-book delle Università di Basilea e Berna</li>
    <li>BORIS -  Bern Open Repository and Information System</li>
    <li>Infoscience - Scientific publications of EPFL</li>
    <li>réro doc - Bibliothèque numérique de RERO</li>
    <li>Bibliografia della storia svizzera</li>
    <li>HAN - Handschriften, Archive, Nachlässe</li>
    <li>Altre collezioni ancora</li>
</ul>

<h2>Concezione e design</h2>
<p>
    Per lo sviluppo e il design del nostro sito web, beneficiamo dell’apporto della società <a href="https://www.snowflake.ch/" target="_blank">Snowflake (Zurigo)</a>.
</p>

<h2>Tecnologia</h2>
<p>
    Swissbib utilizza differenti componenti software al fine di garantire alta qualità e affidabilità del servizio:
</p>
<ul class="list">
    <li>elaborazione dati: <a href="http://www.oclc.org/de/de/cbs/default.htm" target="_blank">CBS - Metadata management solution</a> (OCLC).</li>
    <li>motore di ricerca: <a href="http://lucene.apache.org/solr/" target="_blank">Apache Solr/Lucene</a> (Open Source)</li>
    <li>interfaccia utente: <a href="http://vufind-org.github.io/vufind/" target="_blank">vufind</a> (Open Source)</li>
    <li>altre componenti del servizio: <a href="https://github.com/swissbib" target="_blank">swissbib</a> (Open Source)</li>
</ul>
</p>

<h2>Progetti partner e sottoprogetti</h2>
<p>
    Swissbib è concepito come una piattaforma aperta e mette a disposizione dati, soluzioni software e competenze per lo sviluppo
    di singoli progetti. A vari livelli, swissbib è la base per i seguenti progetti:
</p>
<ul class="list">
    <li>swissbib Basel Bern – catalogo regionale del sistema IDS Basel Bern</li>
    <li>jusbib – metacatalogo per la letteratura giuridica specializzata</li>
    <li>Kartenportal.ch – portale di accesso alle carte geografiche possedute da biblioteche e archivi svizzeri</li>
    <li>linked.swissbib.ch – conferimento dei dati delle biblioteche svizzere sotto forma di "linked open data"</li>
</ul>

<h2>Altre informazioni</h2>
<p>
    Gli indirizzi che seguono, offrono ulteriori informazioni sul progetto nonché le modalità di contatto:
</p>
<ul class="list">
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.swissbib.blogspot.ch')?>" target="_blank">Blog</a></li>
    <li><a title="<?= $this->transEsc('menu.feedback') ?>" href="" id="feedback"><?= $this->transEsc('menu.feedback') ?></a></li>
    <li><a href="&#109;&#97;&#x69;&#x6c;&#116;&#111;&#58;&#115;&#x77;&#105;&#x73;&#115;&#98;&#x69;&#98;&#45;&#117;&#x62;&#64;&#x75;&#x6e;&#x69;&#x62;&#97;&#x73;&#x2e;&#99;&#x68;"><?= $this->transEsc('Email') ?></a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/ub-hauptbibliothek/wir-ueber-uns/adresse-kontakte')?>" target="_blank">Indirizzo (Projekt swissbib, Universitätsbibliothek Basel)</a></li>
    <li><a href="https://www.swissbib.org" target="_blank">Wiki</a></li>
</ul>