<h1>About swissbib</h1>
<h2>What is swissbib</h2>
<p>
    Swissbib is a national catalogue enabling you to search the libraries of Swiss universities, universities of applied science, federal
    research institutions and the Swiss national library. Use swissbib for search and display of results, and the catalogue shows you, in
    which libraries you can get the titles found.
</p>

<h2>What do I find in swissbib</h2>
<p>
    With over 21 million records, swissbib offers access to the collections of more than 900 libraries, archives and other institutions
    from all regions of Switzerland under one interface. Included are books, journals, theses, e-books, digitised content, films, sheet
    music as well as sound records, photographs, slides, teaching materials, language courses, and much more.
</p>

<h2>How do I search swissbib</h2>
<p>
    Swissbib offers a simple search entry with many <a class="help-link" href="<?=$this->url('help-home')?>?topic=search" title="<?= $this->transEsc('Search Tips') ?>">extra options</a>
    and an <a class="help-link" href="<?=$this->url('help-home')?>?topic=advsearch" title="<?= $this->transEsc('Search Tips') ?>">advanced search</a>. Result lists are arranged according
    to relevance criteria and can also be sorted by author, title, or year. The facets or filters enable you to limit the results by various criteria.
</p>

<h2>Where do I get the title desired</h2>
<p>
    Behind the icon <i class="fa fa-institution"></i> you see number and names of owning libraries. A click on the library delivers more information. If the document is an
    online ressource that is freely accesible, we offer a direkt link under the icon <i class="fa fa-external-link"></i>.
</p>
<p>
    Under the tab "Holdings" of a record view, more information like location, callnumber and availability are shown. Here, swissbib offers links to the
    regional catalogues of Swiss networks, where orders can be placed. You will need to log in again.
</p>

<h2>Why log in with swissbib</h2>
<p>
    Upon login in swissbib, you can personalise several settings. This includes:
</p>
<ul class="list">
    <li>use a history of your searches</li>
    <li>define your favorite libraries and use them as filters</li>
    <li>save lists</li>
    <li>configure the interface (language, list lenght)</li>
</ul>
<p>
    In case you do <strong>not</strong>log in, you will loose all settings when closing the browser.
</p>

<h2>How does the login in swissbib work</h2>
<p>
    As a supra-regional service, swissbib offers a login mechanism independent of libraries. There are two options:
</p>
<ul class="list">
    <li>
        <strong>switchAAI:</strong> For students and staff of universities, universities of applied science and further institutionen, we
        use the nationall service of switch. This login is offered by the universities and used by students for services like VPN and
        learning plateforms
        (<a href="https://www.switch.ch/services/aai/" target="_blank" title="switchAAI information">more information</a>).
    </li>
    <li>
        <strong>switch Guest Login:</strong> Access for private person is offered for users who do not have a switchAAI login. It is also a
        switch service
        (<a href="https://www.switch.ch/aai/support/tools/guest-login/" target="_blank" title="Guest Login information">more information</a>).
    </li>
</ul>

<h2>Why log off</h2>
<p>
    At public stations you should log off <strong>and close the browser</strong>, or your account could be used by another person.
</p>

<h2>How up-to-date is swissbib</h2>
<p>
    Records in swissbib are updated daily.
</p>