<h1>Project swissbib</h1>
<p>As a national project, swissbib is funded by the Schweizerischen Hochschulkonferenz and swissuniversities as part of the program
   <a href="<?= $this->redirectProtocolwrapper()->getWrappedURL('http://www.swissuniversities.ch/de/organisation/projekte-und-programme/suk-p-2-wissensch-information-zugang-verarbeitung-speicherung')?>"
       target="_blank">P2 "Scientific information : Access, processing and storage"</a>. The project is affiliated with the
    <a href="https://ub.unibas.ch" target="_blank">University Library Basel</a>. For the period of 2008 to 2013, swissbib was funded
    through innovation and cooperation project
    <a href="<?= $this->redirectProtocolwrapper()->getWrappedURL('http://www.e-lib.ch')?>" target="_blank">"e-lib.ch: Digital Library Switzerland"</a>
</p>

<h2>Participating networks and repositories</h2>
<p>
    The following library networks, digital repositories and special collections are part of swissbib. Their data delivery, support and cooperation
    on various levels make our service possible:
</p>
<ul class="list">
    <li>All networks of IDS - Informationsverbund Deutschschweiz</li>
    <ul>
        <li>IDS Basel Bern</li>
        <li>NEBIS</li>
        <li>IDS Luzern</li>
        <li>IDS St. Gallen</li>
    </ul>
    <li>Swiss National Library</li>
    <li>RERO - Réseau des bibliothèques de Suisse occidentale</li>
    <li>SBT - Sistema bibliotecario ticinese</li>
    <li>Bibliotheksverbund Alexandria</li>
    <li>Aargauer Bibliotheksnetz</li>
    <li>Bibliotheksverbund Graubünden</li>
    <li>St. Galler Bibliotheksnetz</li>
    <li>Liechtensteiner Bibliotheken</li>
    <li>retro.seals.ch - retrodigitized jourlans</li>
    <li>e-codices - Virtual Manuscript Library of Switzerland</li>
    <li>ZORA - Zurich Open Repository and Archive</li>
    <li>Archival collections of the National Library</li>
    <ul>
        <li>Catalogue collectif suisse des affiches</li>
        <li>Digitalisate des Schweizerischen Literaturarchives</li>
        <li>Digitalisate des Eidgenössischen Archivs für Denkmalpflege</li>
    </ul>
</ul>
<p>
    The following collections should be intergrated into swissbib in 2015-2016
</p>
<ul class="list">
    <li>Bibliotheken Schaffhause</li>
    <li>Bibliotheken Thurgau</li>
    <li>E-Books der Universitäten Basel und Bern</li>
    <li>BORIS -  Bern Open Repository and Information System</li>
    <li>Infoscience - Scientific publications of EPFL</li>
    <li>réro doc - Bibliothèque numérique de RERO</li>
    <li>Bibliographie für Schweizer Geschichte</li>
    <li>HAN - Handschriften, Archive, Nachlässe</li>
    <li>Additional archival collections</li>
</ul>

<h2>Development and design</h2>
<p>
    For development and design of our website, we are supported by <a href="https://www.snowflake.ch/" target="_blank">snowflake (Zürich)</a>.
</p>

<h2>Technology</h2>
<p>
    Swissbib uses different software components to guarantee a high quality and availability of the service:
</p>
<ul class="list">
    <li>Data processing: <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.oclc.org/de/de/cbs/default.htm')?>" target="_blank">CBS - Metadata management solution</a> by OCLC.</li>
    <li>Search engine: <a href="<?= $this->redirectProtocolwrapper()->getWrappedURL('http://lucene.apache.org/solr')?>" target="_blank">Apache Solr/Lucene</a> (Open Source)</li>
    <li>User interface: <a href="<?= $this->redirectProtocolwrapper()->getWrappedURL('http://vufind-org.github.io/vufind')?>" target="_blank"> (Open Source)</li>
    <li>Additional components: <a href="https://github.com/swissbib" target="_blank">swissbib</a> (Open Source)</li>
</ul>
</p>

<h2>Partner and sub-projects</h2>
<p>
    Swissbib sees itself as an open plateform, providing data, software solutions, and knowhow to help realise other projects. The following
    projects rely in different degrees on swissbib
</p>
<ul class="list">
    <li>swissbib Basel Bern - Regional catalogue of the network IDS Basel Bern</li>
    <li>jusbib - Metacatalogue for law literature</li>
    <li>Kartenportal.ch - Portal for maps from libraries and archives in Switzerland</li>
    <li>linked.swissbib.ch (sister project) - Publication of Swiss library data as linked open data</li>
</ul>

<h2>Additional information</h2>
<p>
    You can find additional information on the project and ways to contact us under the following addresses:
</p>
<ul class="list">
    <li><a href="http://www.swissbib.blogspot.ch/" target="_blank">Blog</a></li>
    <li><a title="<?= $this->transEsc('menu.feedback') ?>" href="" id="feedback"><?= $this->transEsc('menu.feedback') ?></a></li>
    <li><a href="&#109;&#97;&#x69;&#x6c;&#116;&#111;&#58;&#115;&#x77;&#105;&#x73;&#115;&#98;&#x69;&#98;&#45;&#117;&#x62;&#64;&#x75;&#x6e;&#x69;&#x62;&#97;&#x73;&#x2e;&#99;&#x68;"><?= $this->transEsc('Email') ?></a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/ub-hauptbibliothek/wir-ueber-uns/adresse-kontakte')?>" target="_blank">Address (Projekt swissbib, Universitätsbibliothek Basel)</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.swissbib.blogspot.ch')?>" target="_blank">project wiki</a></li>
</ul>