<h1>About swissbib Basel Bern</h1>
<p>swissbib Basel Bern contains over 7 Mio. titles from over 200 <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">scientific libraries in Basel and Bern</a> (among them libraries of the universities of Basel and Bern, Swiss national library, as well as several libraries of universities of applied sciences).</p>
<p>The project is maintained by <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.informationsverbund.ch/21.0.html') ?>" target="_blank">Verbund IDS Basel Bern</a> and relies on the infrastructure and know-how of the Swiss metacatalog <a href="https://www.swissbib.ch" target="_blank" title="swissbib">swissbib</a>.</p>
<h2>What does swissbib Basel Bern contain?</h2>
<p>swissbib Basel Bern contains two separate databases:</p>
<p><strong>Books & more</strong></p>
<ul>
    <li>books/e-books, journals/e-journals, newspapers, CDs/DVDs, databases etc. Listed is the <strong>title information</strong> of those items, <strong>rather than articles or single chapters</strong>.</li>
    <li>Retro-digitised scientific journals from Switzerland (project retro.seals), offering direct access to full text.</li>
</ul>
<p><strong>Articles & more</strong></p>
<ul>
    <li><strong>journal articles, chapters</strong> etc. from numerous e-journals, e-books and databases offered by the universities of Basel and Bern. From within the IP-range or VPN of the university articles are available as full text.</li>
    <li>freely available electronic resources from the internet, accessible without geographical restrictions.</li>
</ul>
<p>Titles without full text access can be ordered via <i class="fa fa-external-link"></i> SFX-Services at your library.</p>
<h2>Contact</h2>
<p>We are happy to help you with any questions and welcome your feedback:</p>
<ul>
    <li>For questions concerning your account or specific titles please contact your <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">library</a> </li>
    <li>For questions or suggestions concerning swissbib Basel Bern: <a id="feedbackLink" class="modal-link" href="<?= $this->url('feedback-home') ?>"><?= $this->transEsc("menu.contact") ?></a></li>
</ul>
<h2>News</h2>
Subscribe to our <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch') ?>" target="_blank">blog</a>.