<h1>FAQ</h1>
<h2>Rechercher, Recherche avancée</h2>
<ul class="list">
    <li>
        <strong>Est-il possible d'effectuer une recherche dans le fonds d'une bibliothèque définie?</strong>
        <br/>Soit en sélectionant la bibliothèque en tant que favorit et en utilisant dans la liste de résultats <i>Affiner la recherche - Favoris</i> ou en utilisant <i>Recherche avancée - Affiner la recherche - Bibliothèque</i>.
    </li>
    <li>
        <strong>Porquoi l'accès au texte intégral ne fonctionne pas toujours?</strong>
        <br/>Pour l'accès au texte intégral vous devez vous trouver sur le campus de l'université qui a licencié le titre ou vous indetifier par VPN.
    </li>
</ul>

<h2>Commander</h2>
<ul class="list">
    <li>
        <strong>Pouvez vous m'envoyer un certain ouvrage?</strong>
        <br/>Sélectionnez la bibliothèque de votre choix. Cliquez sur <i>Commander</i>. Si l'envoi postal à votre adresse peut se faire, vous pouvez choisir cette option sous <i>Lieu de reprise/livraison</i>.
    </li>
</ul>

<h2>My swissbib</h2>
<ul class="list">
    <li>
        <strong>Comment obtenir rapidement un aperçu de mes prêts?</strong>
        <br/>Connectez-vous, puis cliquez sur <i>Compte: votre nom</i>.<br>
    </li>
</ul>
              
<h2>Vous ne trouvez pas la réponse à votre question?</h2>
<ul class="list">
    <li>
        Pour les questions concernant votre compte, adressez-vous à <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/" target="_blank">votre bibliothèque</a>.
    </li>
    <li>
        Pour les questions concernant des oeuvres particulières, adressez-vous à <a href="<?= $this->url('libraries-index') ?>">la bibliothèque concernée</a>: cliquez sur le <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_link-external.gif') ?>" alt="Informations sur la bibliothèque"> sous Localisation.
    </li>
    <li>
        Contacter swissbib Basel Bern: e-mail à <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> ou commentaire dans le <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a>.
    </li>
</ul>

<h2>Das Richtige nicht gefunden?</h2>
<ul class="list">
    <li>Erweitern Sie Ihre Suche auf <a href="https://www.swissbib.ch/" target="_blank">swissbib.ch</a> (ganze Schweiz) und bestellen Sie bequem aus <a href="http://www.ub.unibas.ch/ids-basel-bern/ids-kurierbibliotheken/" target="_blank">IDS-Kurierbibliotheken.</a></li>
    <li>Schicken Sie uns Ihren Fernleihauftrag: Bestellformular <a href="http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/ausleihe/kurier-und-fernleihe/fernleihformular/" target="_blank">UB Basel</a> / <a href="http://www.ub.unibe.ch/content/bestellen__ausleihen/fernleihe/bestellformular/index_ger.html" target="_blank">UB Bern</a></li>
    <li>Schicken Sie uns Ihren Anschaffungsvorschlag: Anschaffungsvorschlag <a href="http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/ausleihe/anschaffungsvorschlag/" target="_blank">UB Basel</a> / <a href="http://www.ub.unibe.ch/content/bestellen__ausleihen/anschaffungsvorschlaege/index_ger.html" target="_blank">UB Bern</a></li>
</ul>