<h1>Se connecter</h1>
<p>Si vous avez une carte d'utilisateur valable dans l'IDS Basel Bern vous pouvez vous connecter avec votre
    login habituel.</p>
<!--
<p>Si vous avez une carte d'utilisateur valable dans l'un des réseaux suivants vous pouvez vous connecter avec votre
    login habituel:</p>
<ul class="list">
    <li>IDS Basel Bern</li>
    <li>IDS Luzern</li>
    <li>IDS St. Gallen</li>
    <li>NEBIS</li>
    <li>St. Galler Bibliotheksnetz</li>
</ul>
-->

<h2>Pas de carte?</h2>
<p><a href="http://aleph.unibas.ch/F/?func=bor-new-0&CON_LNG=FRE"
      target="_blank"><?= $this->transEsc('Create New Account') ?></a></p>

<h2>Pourqoi se connecter?</h2>
<p>Différentes fonctions de prêt, bibliothèques favorites, listes, recherches sauvegardées et paramètres enregistrés
    sont à votre disposition lorsque vous vous connectez.</p>

<h2>Mot de passe oublié?</h2>
<p>Faites réinitialiser le mot de passe par <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/"
                                               target="_blank">votre bibliothèque</a>.</p>

<h2>Profil</h2>
<p><a href="http://aleph.unibas.ch/F/?func=LOGIN-PAGE" target="_blank">Changer le mot de passe, l'adresse etc.</a></p>

<h2>Pourquoi se déconnecter?</h2>
<p>Il est nécessaire de vous déconnecter des ordinateurs publiques afin d'éviter l'utilisation de votre compte par une
    tierce personne.</p>
</br>
<h1>My swissbib</h1>
<h2>Recherches sauvegardées</h2>
<p>Lorsque vous n'êtes pas connectés, vos recherches seront mémorisées jusqu'à la fermeture du navigateur. Vous pouvez
    répéter la recherche ou- si vous vous connectez - la sauvegarder.</p>

<h2>Favoris</h2>
<p>Afin de sauvegarder une bibliothèque dans les favoris, utilisez <i>Mon swissbib - Favoris</i> ou cliquez sur le <img
        src="<?= $this->basePath('themes/swissbib/images/icon_favorit_library.gif') ?>"
        alt="<?= $this->transEsc('mylibraries.add')?>"
        title="<?= $this->transEsc('mylibraries.add')?>"> dans le catalogue. Ces bibliothèques sont mises en évidence par un <img
        src="<?= $this->basePath('/themes/swissbib/images/icon_favorit_library.gif') ?>"
        alt="Favorit"> dans la liste de résultats et peuvent être choisies comme filtre.
</p>

<h2>Listes de sélection</h2>
<ul class="list">
    <li>Lorsque vous vous connectez, vous pouvez sauvegarder des titres sur des listes de sélection par ce symbole: <br />
        <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_notepad_add.gif') ?>"
             alt="<?= $this->transEsc('memorizelistadd')?>"
             title="<?= $this->transEsc('memorizelistadd')?>">
    </li>
    <li>Lorsque vous sauvegardez un titre et que vous créez en même temps une nouvelle liste de sélection, vous devez
        cliquer deux fois sur <i>Sauvegarder</i>.
    </li>
    <li>Publique = Liste visible pour tout le monde qui connaît l'URL</li>
    <li>Privé = Liste visible seulement pour vous</li>
</ul>

<h2>Paramètres</h2>
<p>Langue du catalogue, nombre de résultats affichés par page</p>

<h2>Compte IDS Basel Bern</h2>
<p>Votre compte</p>
