<div class="pagination-container">
    <? if ($this->pageCount): ?>

       <?=$this->render('search/controls/count.phtml'); ?>

      <ul class="pagination">
        <li class="hidden-sm hidden-xs">
            <a href="#"><?= $this->transEsc('pagination.page') ?>:</a>
        </li>
        <? if (isset($this->previous)): ?>
            <li><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->previous)?>"><i class="fa fa-caret-left"></i></a></li>
        <? else: ?>
            <li class="inactive"><a href="#"><i class="fa fa-caret-left"></i></a></li>
        <? endif; ?>

        <li>
            <a>
                <span class="<?= isset($this->previous) ? 'standard' : 'marked' ?>">
                    <?= $this->current ?>
                </span>
                <?= $this->transEsc('of') ?>
                <span class="<?= isset($this->next) ? 'standard' : 'marked' ?>">
                    <?= $this->pageCount ?>
                </span>
            </a>
        </li>

        <? if (isset($this->next)): ?>
            <li><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->next)?>"><i class="fa fa-caret-right"></i></a></li>
        <? else: ?>
            <li class="inactive"><a href="#"><i class="fa fa-caret-right"></i></a></li>
        <? endif; ?>
      </ul>
    <? endif; ?>
</div>