<h2>jusbib in three steps</h2>
<p>
    Jusbib offers quick, easy and broad access to judicial literature in form of books, journals, periodicals, music, films,
    illustrations, maps and electronic resources in Switzerland. In jusbib you can search for documents from all Swiss academic
    libraries and the National Swiss library at the same time.
</p>

<p>
    Here we will explain how you can find relevant materials and how to access them.
</p>

<ol class="list">
    <li><a href="#search">Search</a></li>
    <li><a href="#refine">Find</a></li>
    <li><a href="#locate">Choose and order</a></li>
</ol>
<h2><a name="search"></a>Search</h2>
<div class="floatbox">
    <p>
        Type one or more terms in the search bar.
    </p>
    <p>
        <em>By using a <strong>*</strong> you can replace <strong>any number</strong> of characters. This is useful when looking
        for terms with different endings (e.g. manag* for manager, managing, managers etc.).</em>
    </p>
    <p>
        <em>By using a question mark <strong>?</strong> you can replace <strong>one</strong> character. This is useful when looking
        for terms with more than one spelling (e.g. advis?r for adviser and adivsor).</em>
    </p>
    <p>
        <em>By placing your search terms in quotation marks <strong>“…”</strong>, you can search for an <strong>exact sequence of words</strong>
        (e.g. “legal status”).</em>
    </p>
</div>

<h2><a name="refine"></a>Find</h2>
<div class="floatbox">
    <h3>Filter</h3>
    <p>
        You can limit your results by using the filters on the right.
    <p>
        Are you looking for a <strong>specific author?</strong> <br/>By typing a name in to the search bar, you will find
        literature by and about that person. To limit the results to literature by a certain person, click on the desired
        name under the filter <strong>author</strong>.
    </p>
    <p>
        Are you looking for specific <strong>subject?</strong><br/> Under the filter <strong>subject</strong> you will find
        different <strong>subject terms</strong> to limit your results.
    </p>
</div>

<h3>Sorting your results</h3>
<p>
    Does sorting by <strong>year (newest first)</strong> not provide you with the desired results? Try changing the sorting
    options to e.g. sort by &raquo;relevance&laquo;.
</p>
<h3>Where can you order?</h3>
<p>
    Click on the icon <i class="fa fa-institution"></i>, located on the right of every entry, to see in which libraries the
    title is available. A click on the library name will bring you more information.
</p>

<h2><a name="locate"></a>Choose and order</h2>
<div class="floatbox">
    <p>
        Click on the title to see the full entry including bibliographical information (title, author, place, publisher,
        date of publication, page number, edition etc.). In the lower area you can also see, which libraries allow access
        to their literature. You also have the option of choosing the libraries you use the most and adding them to your
        favorites by clicking on the heart icon <i class="fa fa-heart-o"></i>. Setting <strong>favorites</strong> is helpful
        while searching for documents, because the results from your favorite libraries will be shown first.
    </p>
    <p>
        By clicking on the <strong>library name</strong>, you will find the location and call number. Many libraries also
        show if the book is currently available or not.
    </p>
    <h3>Lend / Order</h3>
    <p>
        The documents of the libraries must be ordered <strong>directly over the particular library</strong>. To order or reserve documents,
        click on the link <strong>Go to holdings</strong>. This will take you to the owning library where you will have to log in again.
    </p>
</div>

<h2>Log in</h2>
<h3>Why log in when using jusbib?</h3>
<p>
    When you log in to jusbib, you can use many personal settings. You can:
</p>
<ul class="list">
    <li>go back to old searches</li>
    <li>choose your favorite libraries once and use them for every search</li>
    <li>save your list for a long period of time </li>
    <li>choose  your settings (language, list length)</li>
</ul>
<p>
    If you do <strong>not</strong> log in, you will loose all your settings when you close the browser.
</p>

<h2>How does jusbib login work?</h2>
<p>
    As a nationwide service, jusbib offers library independent login. There are two options:
</p>
<ul class="list">
    <li>
        <strong>switchAAI:</strong> For students, university staff, advanced technical colleges and other institutions we use
        the national service from switch. The logins are provided by these institutions, which students can also use for
        other services such as VPN or learning platforms
        (<a href="https://www.switch.ch/services/aai/" target="_blank" title="Info zu switchAAI">More information</a>).
    </li>
    <li>
        <strong>switch Guest Login:</strong> This access is for private users, who are not students and therefor can not log
        in with switchAAI. This service is also provided by switch
        (<a href="https://www.switch.ch/aai/support/tools/guest-login/" target="_blank" title="Info zum Guest Login">More information</a>).
    </li>
</ul>

<h2>Why log out?</h2>
<p>
    When using public computers, you should always log out and <strong>close the browser</strong>, so that no one can use your account.
</p>
