<h2>About jusbib</h2>
<p>
    Jusbib is the <b>metacatalogue</b> of Swiss law libraries and further relevant holdings of <b>law literature</b>.
    Interface and search functionalities correspond with those of the national catalogue
    <a href="https://www.swissbib.ch" target="_blank">swissbib</a>.
</p>
<p>
    Additionally, records can be searched through a standardised law classification system, the multilingual and systematic
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://isdc.ch/d2wfiles/document/5445/4018/0/Plan%20syst%20D(ISDC).pdf') ?>"
       target="_blank">Classification of the Swiss Institute for Comparative Law</a>.
</p>
<p>
    The project jusbib was started by the <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.lawlibraries.ch/') ?>" target="_blank">
    Association of Legal Libraries in Switzerland</a> and carried out in close cooperation with the swissbib team. It is funded by the
    <a href="https://www.bj.admin.ch/bj/en/home.html" target="_blank">Federal Office of Justice</a> and the association
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.svri.ch/index.html') ?>" target="_blank">eJustice.CH</a>.
</p>
