<div class="<?= $this->layoutClass('mainbody') ?> breadcrumbMain">

<? if((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true)
   && !empty($this->layout()->breadcrumbs)
   && $this->layout()->breadcrumbs !== false
 ): ?>
   <ul class="breadcrumb hidden-print">
   <? if(is_array($this->layout()->breadcrumbs)): ?>
     <? if(count($this->layout()->breadcrumbs) > 1): ?>
       <?=$this->render('breadcrumbs/multi.phtml', array(
           'parents' => $this->layout()->breadcrumbs,
           'title'   => $this->layout()->title,
           'end'     => $this->layout()->breadcrumbEnd,
           'from'    => $this->layout()->from
         )) ?>
     <? else: ?>
       <?=$this->render('breadcrumbs/default.phtml', array(
           'parents' => $this->layout()->breadcrumbs,
           'title'   => $this->layout()->title
         )) ?>
     <? endif; ?>
   <? else: ?>
     <?=$this->layout()->breadcrumbs ?>
   <? endif; ?>
   </ul>
 <? endif; ?>
</div>
<div class="col-md-3 breadcrumbSide"></div>
