<? if ($external === true): ?>
    <div class="authorbox">
        <p><?=$this->transEsc('Access')?></p>
        <p>
            <?=$this->transEsc('external_access_info')?> (<a target="_blank" class="color singleLink" href="http://mobile.unibas.ch/home.html" title="Uni Basel">Uni Basel</a> / <a target="_blank" class="color singleLink" href="http://www.vpn.unibe.ch/" title="Uni Basel">Uni Bern</a>).
        </p>
    </div>
<? endif; ?>
<? $summonDatabases = $this->recommend->getResults(); if (!empty($summonDatabases)): ?>
    <div class="authorbox">
        <p><?=$this->transEsc('summon_database_recommendations')?></p>
        <? foreach ($summonDatabases as $current): ?>
            <p><a href="<?=$this->escapeHtmlAttr($current['link'])?>"><?=$this->escapeHtml($current['title'])?></a><br/><?=$this->escapeHtml($current['description'])?></p>
        <? endforeach; ?>
    </div>
<? endif; ?>