<?php
///** @var \Swissbib\RecordDriver\SolrMarc		$record  */
$record = $this->driver;
/** @var \VuFind\View\Helper\Root\Record $viewRecord */
$viewRecord = $this->record($record);

$authors    = $this->driver->getDeduplicatedAuthors();
$hasAuthors = !empty($authors['main']) || !empty($authors['secondary']) || !is_null($authors['corporate']) && !empty($authors['corporate']);

if (!$hasAuthors) {
  return '';
}
?>

<? if (!empty($authors['main']) || !empty($authors['secondary']) || !is_null($authors['corporate']) && !empty($authors['corporate'])): ?>

  <h4 class="list-group-item title"><?= $this->transEsc('Author') ?></h4>
  <ul class="list-group">

    <?php if (!empty($authors['main'])): ?>
      <li class="list-group-item">
        <a href="<?= $viewRecord->getLink('author', $authors['main']) ?>"
           title="<?= $this->escapeHtml($authors['main']) ?>"><?= $this->escapeHtml($authors['main']) ?></a>
      </li>
    <?php endif; ?>

    <?php if (!empty($authors['secondary'])): ?>
      <? $tauthors = array(); //de-dublication in PHP style...?>

      <?php foreach ($authors['secondary'] as $secondaryAuthor): ?>
        <? $tauthors[$secondaryAuthor] = $secondaryAuthor ?>
      <?php endforeach; ?>

      <?php foreach ($tauthors as $secondaryAuthor): ?>
        <li class="list-group-item">
          <a href="<?= $viewRecord->getLink('author', $secondaryAuthor) ?>" title="<?= $this->escapeHtml($secondaryAuthor) ?>">
            <?= $this->escapeHtml($secondaryAuthor) ?>
          </a>
        </li>
      <?php endforeach; ?>
    <?php endif; ?>

    <?php if (!is_null($authors['corporate']) && !empty($authors['corporate'])): ?>
      <? if (!is_array($authors['corporate'])): ?>
        <? $authors['corporate'] = array($authors['corporate']);?>
      <? endif; ?>

      <?php foreach ($authors['corporate'] as $corporateAuthor): ?>
        <li class="list-group-item">
          <a href="<?= $viewRecord->getLink('author', $corporateAuthor) ?>" title="<?= $this->escapeHtml($corporateAuthor) ?>">
            <?= $this->escapeHtml($corporateAuthor) ?>
          </a>
        </li>
      <?php endforeach; ?>
    <?php endif; ?>
  </ul>

<? endif; ?>



