<h2>jusbib in drei Schritten</h2>
<p>
    Jusbib bietet einen raschen, einfachen und umfassenden Zugang zur  juristischen Literatur in Form von Büchern, Zeitschriften,
    Zeitungen, Musik, Bildern, Filmen, Karten und elektronischen Ressourcen in der Schweiz an. In jusbib sind die Bestände
    aller Schweizer Hochschulbibliotheken und der Schweizerischen Nationalbibliothek gleichzeitig recherchierbar.
</p>

<p>Wir erklären Ihnen, wie Sie in jusbib relevante Materialien recherchieren und anschliessend darauf zugreifen
    können.</p>

<ol class="list">
    <li><a href="#search">Suchen</a></li>
    <li><a href="#refine">Finden</a></li>
    <li><a href="#locate">Auswählen und Bestellen</a></li>
</ol>
<h2><a name="search"></a>Suchen</h2>
<div class="floatbox">
    <p>
        Geben Sie einen oder mehrere Begriffe in den Suchschlitz ein.
    </p>
    <p>
        <em>Mit einem Stern <strong>*</strong> können Sie <strong>beliebig viele</strong> Zeichen ersetzen, um z.B.
        Begriffe mit unterschiedlicher Endung zu erfassen (Bsp. miet* für 'Miete', 'Mieter', 'Mietrecht', etc.).</em>
    </p>
    <p>
        <em>Das Fragezeichen <strong>?</strong> ersetzt <strong>ein</strong> Zeichen und erlaubt Ihnen, unterschiedliche
            Schreibweisen zu berücksichtigen (Bsp. europe?n für 'european' und 'européen').</em>
    </p>
    <p>
        <em>Indem Sie Ihre Suchbegriffe in Anführungszeichen <strong>“...“</strong> setzen, haben Sie die Möglichkeit,
            nach einer <strong>genauen Wortabfolge</strong> zu suchen (Bsp. „legal status“).
        </em>
    </p>
</div>

<h2><a name="refine"></a>Finden</h2>
<div class="floatbox">
    <h3>Filter</h3>
    <p>
        Sie können Ihre Treffer anhand der Filter auf der rechten Seite eingrenzen.
    </p>
    <p>
        Suchen Sie nach einem <strong>bestimmten Autor</strong>? <br/>Eine einfache Suche nach dem Namen ergibt Dokumente
        von einer oder auch über eine Person. Um nur Dokumente von einer bestimmten Person zu erhalten, wählen Sie den
        gewünschten Namen beim Filter <strong>Autor</strong> aus und klicken Sie darauf, um die Treffermenge
        einzugrenzen.
    </p>
    <p>
        Suchen Sie nach einem <strong>Thema</strong>? <br/>Unter einem der Filter für den <strong>Inhalt</strong> finden
        Sie <strong>thematische Suchbegriffe</strong>, um Ihre Treffer einzuschränken.
    </p>
</div>

<h3>Ergebnisse sortieren</h3>
<p>
    Liefert die Sortierung nach <strong>Jahr (neuestes zuerst)</strong> nicht das Gewünschte? Ändern Sie die Reihenfolge,
    in der die Ergebnisse Ihrer Suche angezeigt werden sollen - z.B. auf &raquo;Relevanz&laquo;.
</p>
<h3>Wo können Sie das Gesuchte bestellen?</h3>
<p>
    Das Symbol <i class="fa fa-institution"></i> auf der rechten Seite jedes Titels zeigt Ihnen, in welchen Bibliotheken
    ein Exemplar vorhanden ist. Ein Klick auf den Bibliotheksnamen bringt Ihnen weitere Informationen.
</p>

<h2><a name="locate"></a>Auswählen und Bestellen</h2>
<div class="floatbox">
    <p>
        Mit einem Klick auf einen Titel in der Trefferliste öffnet sich die Vollanzeige der bibliographischen Angaben
        (Titel, Autor, Ort, Verlag, Erscheinungsjahr, Seitenzahl, Auflage etc..). Im unteren Bereich sehen Sie zudem,
        welche Bibliotheken den Zugriff auf das Dokument ermöglichen. Ebenfalls haben Sie hier die Möglichkeit, durch
        einen Klick auf das kleine Herzsymbol <i class="fa fa-heart"></i> Ihre meistgenutzten Bibliotheken als <strong>Favoriten</strong>
        zu definieren, damit sie immer an erster Stelle erscheinen.
    </p>
    <p>
        Ein Klick auf den <strong>Bibliotheksnamen</strong> zeigt Ihnen Standort und Signatur an. Bei vielen Bibliotheken
        erfahren Sie zudem, ob das Dokument verfügbar oder schon ausgeliehen ist.
    </p>

    <h3>Ausleihe/Bestellung</h3>
    <p>
        Die Dokumente der Bibliotheken müssen Sie <strong>direkt über die jeweilige Bibliothek beziehen</strong>. Für
        den Zugriff bzw. die Bestellung/Reservation klicken Sie auf den Link <strong>zum Bestand</strong>, wechseln zur besitzenden
        Bibliothek und melden sich erneut an.
    </p>
</div>

<h2>Anmelden</h2>
<h3>Wozu in jusbib anmelden</h3>
<p>
    Mit einer Anmeldung in jusbib können Sie verschiedene Einstellungen personalisiert nutzen. Sie können:
</p>
<ul class="list">
    <li>auf bereits getätigte Suchen zurückgreifen</li>
    <li>Favoritenbibliotheken einmal definieren und dann immer wieder nutzen</li>
    <li>Merklisten über einen längeren Zeitraum speichern</li>
    <li>Die Suchoberfläche konfigurieren (Sprache, Listenlänge)</li>
</ul>
<p>
    Wenn Sie sich <strong>nicht</strong> anmelden, verlieren Sie alle Einstellungen, wenn Sie den Browser schliessen.
</p>

<h2>Wie funktioniert die Anmeldung in jusbib</h2>
<p>
    Als überregionaler Service bietet jusbib eine bibliotheksunabhängige Anmeldung. Es stehen zwei Möglichkeiten zur Verfügung:
</p>
<ul class="list">
    <li>
        <strong>switchAAI:</strong> Für Studierende und das Personal von Universitäten, Fachhochschulen und weiteren
        Institutionen nutzen wir den nationalen Dienst von switch. Dieses Login wird von diesen Institutionen bereitgestellt und
        von Studierenden auch für andere Dienste wie VPN oder Lernplattformen genutzt
        (<a href="https://www.switch.ch/services/aai/" target="_blank" title="Info zu switchAAI">Mehr Informationen</a>).
    </li>
    <li>
        <strong>switch Guest Login:</strong> Der Zugang für Private steht speziell jenen Nutzerinnen und Nutzern zur Verfügung, die sich
        nicht über switchAAI anmelden können, da sie bei keiner Hochschule eingeschrieben sind. Er wird ebenfalls von switch bereitgestellt
        (<a href="https://www.switch.ch/aai/support/tools/guest-login/" target="_blank" title="Info zum Guest Login">Mehr Informationen</a>).
    </li>
</ul>

<h2>Wozu abmelden?</h2>
<p>
    An öffentlichen Computern sollten Sie sich abmelden <strong> und den Browser schliessen</strong>, damit ausser Ihnen niemand
    Ihr Konto benutzen kann.
</p>
