<?php
$suggestions = $this->results->getSpellingSuggestions();
$query = $this->results->getUrlQuery();
?>

<? if ( $recordTotal === 0 ): ?>
    <div class="results-top row">
        <div class="col-md-9">
            <h1><i class="fa fa-search"></i> <span><?=$this->transEsc('nohit_heading')?></span></h1>
        </div>
    </div>
<? endif; ?>

<?php if (!empty ($suggestions) &&  !is_array($suggestions) &&
    $suggestions instanceof Swissbib\VuFind\Search\Solr\SpellingResults &&  $suggestions->hasSuggestions()) : ?>

    <div class="alert">
        <p><?=$this->transEsc('Your search terms')?>: <?= $suggestions->getSpellingQuery()->getAllTerms() ?></p>
    </div>

    <div class="alert">
    <h4><?=$this->transEsc('nohit_spelling') ?></h4>
    <!--            <span>suggestions for: --><?//= $suggestions->getSpellingQuery()->getString() ?><!--</span>-->

    <? if ($suggestions->hasCollocations()) :?>
        <!--            <p>Collocation queries</p>-->
        <? foreach($suggestions->getCollocationSuggestions() as $collocation) :?>
            <p><a href="<?=$this->url('search-results')?>?lookfor=<?=urlencode($collocation['query'])?>"><?=$this->escapeHtml($collocation['query']) ?></a></p>
        <? endforeach ?>
    <? endif; ?>

    <? if ($suggestions->hasTerms()) :?>
        <!--                <p>suggestions based on single terms</p> <p>&nbsp;</p>-->
        <? foreach($suggestions->getTermSuggestions() as $key => $termValues) :?>
            <!--                        <p>suggestions for: --><?//= $key ?><!--</p>-->
            <? foreach ($termValues as $termValue): ?>
                <p><a href="<?=$this->url('search-results')?>?lookfor=<?=urlencode($termValue['query'])?>"><?=$this->escapeHtml($termValue['query']) ?></a></p>
            <? endforeach; ?>
            <!--                        --><?// // paragraph element with nbsp is not really nice - look for better css classes?>
            <!--                        <p>&nbsp;</p>-->
        <? endforeach ?>
        </div>

    <? endif; ?>

<?php endif; ?>

<? if ( $recordTotal === 0 ): ?>
    <div class="alert">
        <h4><?=$this->transEsc('nohit_suggest') ?></h4>
        <p><?=$this->transEsc('nohit_text3') ?><a href="http://www.worldcat.org/search?qt=worldcat_org_all&q=<?=$lookfor ?>" target="_blank"><?=$this->transEsc('worldcat') ?></a></p>
    </div>
    <div class="alert">
        <h4><?=$this->transEsc('nohit_tip') ?></h4>
        <p><a class="help-link" href="<?=$this->url('help-home')?>?topic=search"><?= $this->transEsc('Search Tips') ?></a></p>
        <p><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a> <?=$this->transEsc('nohit_text5') ?> </p>
    </div>
<? endif; ?>



