<div class="form-group">
  <label class="col-sm-2 control-label"><?=$this->transEsc('recovery_by_username') ?>:</label>
  <div class="col-sm-4">
    <input type="text" name="username" class="form-control"/>
  </div>
  <input class="btn btn-default" name="submit" type="submit"/>
</div>
<div class="form-group">
  <label class="col-sm-2 control-label"><?=$this->transEsc('recovery_by_email') ?>:</label>
  <div class="col-sm-4">
    <input type="email" name="email" class="form-control"/>
  </div>
  <input class="btn btn-default" name="submit" type="submit"/>
</div>