<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
      $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
  $this->layout()->title = $this->driver->getShortTitle();
?>

<? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <ul class="pager noprint col-md-9">
    <? if ($this->scrollData['nextRecord']): ?>
      <li>
          <a class="btn btn-primary" href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>"><?=$this->transEsc('Next')?> &raquo;</a>
      </li>
    <? else: ?>
      <li class="disabled"><a class="btn btn-primary" href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
    <li>
      <span class="number-of-results"></sp><?=$this->escapeHtml($this->scrollData['currentPosition']) . ' ' . $this->transEsc('of') . ' ' . number_format($this->escapeHtml($this->scrollData['resultTotal'])) ?></span>
    </li>
    <? if ($this->scrollData['previousRecord']): ?>
      <li>
        <a class="btn btn-primary" href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>">&laquo; <?=$this->transEsc('Prev')?></a>
      </li>
    <? else: ?>
      <li class="disabled"><a class="btn btn-primary" href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>

  </ul>
<? endif; ?>

<?=$this->record($this->driver)->getToolbar()?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <div class="record recordId source<?=$this->escapeHtml($this->driver->getResourceSource())?>" id="record">
    <input type="hidden" value="<?=$this->escapeHtml($this->driver->getUniqueId())?>" class="hiddenId" id="record_id" />
    <input type="hidden" value="<?=$this->escapeHtml($this->driver->getResourceSource()) ?>" class="hiddenSource" />
    <?=$this->flashmessages()?>
    <?=$this->record($this->driver)->getCoreMetadata()?>
  </div>

  <? if (count($this->tabs) > 0): ?>
    <a name="tabnav"></a>
    <ul class="recordTabs nav nav-tabs">
      <? foreach ($this->tabs as $tab => $obj): ?>
      <? // add current tab to breadcrumbs if applicable:
        $desc = $obj->getDescription();
        $isCurrent = (strtolower($this->activeTab) == strtolower($tab));
        if ($isCurrent) {
          $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
          $activeTabObj = $obj;
        }
      ?>
      <li<?=$isCurrent ? ' class="active"' : ''?>>
        <a id="<?=$tab ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><?=$this->transEsc($desc)?></a>
      </li>
      <? endforeach; ?>
    </ul>
  <? endif; ?>

  <div class="tab-container">
    <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
  </div>

  <span class="Z3988" title="<?=$this->escapeHtml($this->driver->getOpenURL($this))?>"></span>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <? foreach ($this->related()->getList($this->driver) as $current): ?>
    <?=$this->related()->render($current)?>
  <? endforeach; ?>
</div>
