<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="col-md-3">
    <div>
      <? /* Display thumbnail if appropriate: */ ?>
      <? $mediumThumb = $this->record($this->driver)->getThumbnail('medium'); $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
      <? if ($mediumThumb): ?>
        <? if ($largeThumb): ?><a href="<?=$this->escapeHtml($largeThumb)?>"><? endif; ?>
          <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtml($mediumThumb);?>"/>
        <? if ($largeThumb): ?></a><? endif; ?>
      <? else: ?>
        <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-phone">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtml($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <?=$this->record($this->driver)->getPreviews()?>
  </div>

  <div class="col-md-4 core">
    <h3 property="name"><?=$this->escapeHtml($this->driver->getShortTitle()) ?></h3>
    <h5><?= $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection() ?></h5>

      <p>
      <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
      <? if (isset($authors['main']) && !empty($authors['main'])): ?>
              <?=$this->transEsc('Main Author')?>:  <a href="<?=$this->record($this->driver)->getLink('author', $authors['main'])?>"><?=$this->escapeHtml($authors['main'])?></a><br>
      <? endif; ?>

      <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
              <?=$this->transEsc('Corporate Author')?>: <a href="<?=$this->record($this->driver)->getLink('author', $authors['corporate'])?>"><?=$this->escapeHtml($authors['corporate'])?></a><br>
      <? endif; ?>

      <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
              <?=$this->transEsc('Other Authors')?>: <? $i = 0; foreach ($authors['secondary'] as $field): ?><?=($i++ == 0)?'':', '?><span property="contributor"><a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a></span><? endforeach; ?><br>
      <? endif; ?>
      </p>

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $summary[0] : false; ?>
    <? if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <? if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <? endif; ?>
    <? endif; ?>

    </table>
  </div>

  <div class="col-md-5 core">

        <table>


          <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
              <tr>
                  <th><?=$this->transEsc('Format')?>: </th>
                  <td><?=$this->record($this->driver)->getFormatList()?></td>
              </tr>
          <? endif; ?>

          <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
              <tr>
                  <th><?=$this->transEsc('Language')?>: </th>
                  <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang)?><br/><? endforeach; ?></td>
              </tr>
          <? endif; ?>

          <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
              <tr>
                  <th><?=$this->transEsc('Published')?>: </th>
                  <td>
                      <? foreach ($publications as $field): ?>
                          <span property="publisher" typeof="Organization">
            <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
                <span property="location"><?=$this->escapeHtml($pubPlace)?></span>
            <? endif; ?>
                              <? $pubName = $field->getName(); if (!empty($pubName)): ?>
                                  <span property="name"><?=$this->escapeHtml($pubName)?></span>
                              <? endif; ?>
            </span>
                          <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
                              <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
                          <? endif; ?>
                          <br/>
                      <? endforeach; ?>
                  </td>
              </tr>
          <? endif; ?>

          <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
              <tr>
                  <th><?=$this->transEsc('Edition')?>: </th>
                  <td property="bookEdition"><?=$this->escapeHtml($edition)?></td>
              </tr>
          <? endif; ?>

          <?/* Display series section if at least one series exists. */?>
          <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
              <tr>
                  <th><?=$this->transEsc('Series')?>: </th>
                  <td>
                      <? foreach ($series as $field): ?>
                          <?/* Depending on the record driver, $field may either be an array with
               "name" and "number" keys or a flat string containing only the series
               name.  We should account for both cases to maximize compatibility. */?>
                          <? if (is_array($field)): ?>
                              <? if (!empty($field['name'])): ?>
                                  <a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
                                  <? if (!empty($field['number'])): ?>
                                      <?=$this->escapeHtml($field['number'])?>
                                  <? endif; ?>
                                  <br/>
                              <? endif; ?>
                          <? else: ?>
                              <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
                          <? endif; ?>
                      <? endforeach; ?>
                  </td>
              </tr>
          <? endif; ?>

          <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
              <tr>
                  <th><?=$this->transEsc('Subjects')?>: </th>
                  <td>
                      <? foreach ($subjects as $field): ?>
                          <div class="subjectLine" property="keywords">
                              <? $subject = ''; ?>
                              <? if(count($field) == 1) $field = explode('--', $field[0]); ?>
                              <? $i = 0; foreach ($field as $subfield): ?>
                                  <?=($i++ == 0) ? '' : ' &gt; '?>
                                  <? $subject = trim($subject . ' ' . $subfield); ?>
                                  <a class="backlink" title="<?=$this->escapeHtml($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>"><?=trim($this->escapeHtml($subfield))?></a>
                              <? endforeach; ?>
                          </div>
                      <? endforeach; ?>
                  </td>
              </tr>
          <? endif; ?>

          <?
          $openUrl = $this->driver->openURLActive('record') ? $this->driver->getOpenURL($this) : false;
          // Account for replace_other_urls setting
          $urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->record($this->driver)->getLinkDetails();
          ?>
          <? if (!empty($urls) || $openUrl): ?>
              <tr>
                  <th><?=$this->transEsc('Online Access')?>: </th>
                  <td>
                      <? foreach ($urls as $current): ?>
                          <a href="<?=$this->escapeHtml($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
                      <? endforeach; ?>
                      <? if ($openUrl): ?>
                          <?=$this->openUrl($openUrl)?><br/>
                      <? endif; ?>
                  </td>
              </tr>
          <? endif; ?>

          <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
          <? if(!empty($recordLinks)): ?>
              <tr>
                  <th><?=$this->transEsc('Related Items')?></th>
                  <td>
                      <? foreach ($recordLinks as $recordLink): ?>
                          <?=$this->transEsc($recordLink['title'])?>:
                          <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
                      <? endforeach; ?>
                  </td>
              </tr>
          <? endif; ?>


      </table>

      <a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>" title="<?=$this->transEsc('Add to favorites')?>">
          <span class="label label-info iconlabel"><i class="fa fa-plus"></i>Merkliste</span>
      </a>

      <?/* End Main Details */?>
  </div>

</div>
