<?
  // Set page title.
  $this->headTitle($this->translate('Advanced Search'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li class="active">' . $this->transEsc('Advanced') . '</li>';

  // Set up saved search details:
  if (isset($this->saved) && is_object($this->saved)) {
    $searchDetails = $this->saved->getParams()->getQuery();
    if ($searchDetails instanceof \VuFindSearch\Query\Query) {
        // Not an advanced query -- ignore it.
        $searchDetails = $groups = false;
    } else {
        $groups = $searchDetails->getQueries();
    }
    $hasDefaultsApplied = $this->saved->getParams()->hasDefaultsApplied();
    $searchFilters = $this->saved->getParams()->getFilterList();
  } else {
    $hasDefaultsApplied = $searchDetails = $searchFilters = $groups = false;
  }

  // Set up Javascript:
  // Step 1: Define our search arrays so they are usuable in the javascript
  $this->headScript()->appendScript($this->render('search/advanced/globals.phtml'));
  // Step 2: Call the javascript to make use of the above
  $this->headScript()->appendFile(
    isset($this->advancedSearchJsOverride) ? $this->advancedSearchJsOverride : 'advanced_search.js'
  );
  // Step 3: Build the page
  $this->headScript()->appendScript(
    $this->partial(
      isset($this->buildPageOverride) ? $this->buildPageOverride : 'search/advanced/build_page.phtml',
      array('searchDetails' => $searchDetails)
    )
  );

  $activeTab = '';
?>

<?= $this->render('search/advanced/templates-handlebars') ?>

<? $searchTabs = $this->searchtabs($this->searchClassId, $this->lookfor, $this->searchIndex, 'advanced', 'advanced'); ?>
<? if (count($searchTabs) > 0): ?>
    <ul class="nav nav-tabs">
        <? foreach ($searchTabs as $tab): ?>
            <? if ($tab['selected']) $activeTab = $tab['class']; ?>
            <li<?=$tab['selected'] ? ' class="active"' : ''?>>
                <a href="<?=$tab['selected'] ? '' : $this->escapeHtmlAttr($tab['url'])?>"><?=$this->transEsc($tab['label']); ?></a>
            </li>
        <? endforeach; ?>
    </ul>
<? endif; ?>
<?=$this->flashmessages()?>
<form role="search" name="searchForm" id="advSearchForm" method="get" action="<?=$this->url($this->options->getSearchAction())?>">
  <?= $this->render('search/advanced/' . lcfirst($activeTab)) ?>
</form>
