<div class="<?=$this->layoutClass('mainbody')?>">
  <input type="hidden" name="sort" value="relevance">
  <div class="clearfix">
    <p class="lead pull-left"><?=$this->transEsc('Advanced Search')?></p>
    <div id="groupJoin" class="form-inline pull-right hidden">
      <label for="join"><?=$this->transEsc("search_match")?>:</label>
      <select id="search_bool0" name="join" class="form-control">
        <option value="AND"<? if($searchDetails && $searchDetails->getOperator()=='ALL'):?> selected<?endif?>><?= $this->transEsc('group_AND') ?></option>
        <option value="OR"<? if($searchDetails && $searchDetails->getOperator()=='OR'):?> selected<?endif?>><?= $this->transEsc('group_OR') ?></option>
      </select>
    </div>
  </div>
  <i id="groupPlaceHolder" class="fa fa-plus-circle"></i> <a href="#" onClick="addGroup()"><?= $this->transEsc('add_search_group') ?></a>
  <input class="btn btn-primary pull-right" type="submit" value="<?= $this->transEsc('Find')?>">
  <? if (isset($this->extraAdvancedControls)): ?>
    <?=$this->extraAdvancedControls ?>
    <input class="btn btn-primary pull-right" type="submit" value="<?= $this->transEsc('Find')?>"/>
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <? if ($hasDefaultsApplied): ?>
    <input type="hidden" name="dfApplied" value="1" />
  <? endif ?>
  <? if (!empty($searchFilters)): ?>
    <h4><?=$this->transEsc("adv_search_filters")?></h4>
    <ul class="list-group">
      <label class="list-group-item checkbox"><?=$this->transEsc("adv_search_select_all")?> <input type="checkbox" checked="checked" class="checkbox-select-all"/></label>
    </ul>
    <? foreach ($searchFilters as $field => $data): ?>
      <ul class="list-group">
        <li class="list-group-item title"><?=$this->transEsc($field)?></li>
        <? foreach ($data as $value): ?>
          <label class="list-group-item checkbox"><input class="checkbox-select-item" type="checkbox" checked="checked" name="filter[]" value='<?=$this->escapeHtmlAttr($value['field'])?>:"<?=$this->escapeHtmlAttr($value['value'])?>"' /> <?=$this->escapeHtml($value['displayText'])?></label>
        <? endforeach; ?>
      </ul>
    <? endforeach; ?>
  <? endif; ?>
  <div class="sidegroup">
    <h4><?=$this->transEsc("Search Tips")?></h4>
    <ul class="list-group">
      <a class="list-group-item help-link" href="<?=$this->url('help-home')?>?topic=advsearch" title="<?=$this->transEsc('Help with Advanced Search')?>"><?=$this->transEsc("Help with Advanced Search")?></a>
      <a class="list-group-item help-link" href="<?=$this->url('help-home')?>?topic=search" title="<?=$this->transEsc('Help with Search Operators')?>"><?=$this->transEsc("Help with Search Operators")?></a>
    </ul>
  </div>
</div>