<div class="<?=$this->layoutClass('sidebar')?>">
    <? if (isset($hasDefaultsApplied) && $hasDefaultsApplied): ?>
        <input type="hidden" name="dfApplied" value="1" />
    <? endif ?>
    <? if (!empty($searchFilters)): ?>
        <h4><?=$this->transEsc("adv_search_filters")?></h4>
        <ul class="list-group">
            <label class="list-group-item checkbox"><?=$this->transEsc("adv_search_select_all")?> <input type="checkbox" checked="checked" class="checkbox-select-all"/></label>
        </ul>
        <? foreach ($searchFilters as $field => $data): ?>
            <ul class="list-group">
                <li class="list-group-item title"><?=$this->transEsc($field)?></li>
                <? foreach ($data as $value): ?>
                    <label class="list-group-item checkbox"><input class="checkbox-select-item" type="checkbox" checked="checked" name="filter[]" value='<?=$this->escapeHtmlAttr($value['field'])?>:"<?=$this->escapeHtmlAttr($value['value'])?>"' /> <?=$this->escapeHtml($value['displayText'])?></label>
                <? endforeach; ?>
            </ul>
        <? endforeach; ?>
    <? endif; ?>
    <div class="sidegroup">
        <h4><?=$this->transEsc('Search Tips')?></h4>
        <ul class="list-group">
            <a class="list-group-item" href="<?=$this->url('help-page', array('topic' => 'search')); ?>" target="_blank" title="<?=$this->transEsc('helppage.search')?>"><?=$this->transEsc("helppage.search")?></a>
            <a class="list-group-item help-link" href="<?=$this->url('help-home')?>?topic=search" title="<?=$this->transEsc('Help with Search Operators')?>"><?=$this->transEsc("Help with Search Operators")?></a>
        </ul>
    </div>
    <div class="sidegroup">
        <h4><?=$this->transEsc('Your Account')?></h4>
        <ul class="list-group">
            <a class="list-group-item" href="<?= $this->url('search-history')?>" title="<?= $this->transEsc('Search History')?>"><?=$this->transEsc('Search History')?></a>
            <a class="list-group-item" href="<?=$this->url('myresearch-settings')?>" title="<?=$this->transEsc('My_Search_Settings')?>"><?=$this->transEsc('My_Search_Settings')?></a>
        </ul>
    </div>
    <div class="sidegroup">
        <h4><?=$this->transEsc('other_catalogs')?></h4>
        <ul class="list-group">
            <a class="list-group-item" href="http://www.swissbib.ch" target="_blank" title="swissbib: Schweizerischer Metakatalog">swissbib: Schweizerischer Metakatalog</a></a>
            <a class="list-group-item" href="http://aleph.unibas.ch/F" title="ALEPH-Katalog IDS Basel Bern">ALEPH-Katalog IDS Basel Bern</a>
            <a class="list-group-item" href="http://aleph.unibas.ch/F/?func=option-update-lng&file_name=find-b&p_con_lng=GER&local_base=dsv05" title="Verbundkatalog HAN für Handschriften, Archive und Nachlässe">Verbundkatalog HAN für Handschriften, Archive und Nachlässe</a>
            <a class="list-group-item" href="http://swb.bsz-bw.de/DB=2.104/START_WELCOME" target="_blank" title="Thesaurus (GND)">Thesaurus (GND)</a>
        </ul>
    </div>
</div>