<h1>Projekt swissbib</h1>
<p>Swissbib wird als nationales Projekt von der Schweizerischen Universitätskonferenz und swissuniversities als Teil des Programms
    <a href="<?= $this->redirectProtocolwrapper()->getWrappedURL('http://www.swissuniversities.ch/de/organisation/projekte-und-programme/suk-p-2-wissensch-information-zugang-verarbeitung-speicherung')?>"
       target="_blank">P2 "Wissenschaftliche Information: Zugang, Verarbeitung und Speicherung"</a> gefördert. Das Projekt ist der
    <a href="https://ub.unibas.ch" target="_blank">Universitätsbibliothek Basel</a> angegliedert.
    Für die Periode von 2008 bis 2013 wurde swissbib durch die Finanzierung des Innovations- und Kooperationsprojektes
    <a href="<?= $this->redirectProtocolwrapper()->getWrappedURL('http://www.e-lib.ch')?>" target="_blank">"e-lib.ch: Elektronische Bibliothek Schweiz"</a>
    ermöglicht.
</p>

<h2>Teilnehmende Verbünde und Repositorien</h2>
<p>
    Folgende Bibliotheksverbünde, digitale Repositorien und Spezialbestände sind Teil von swissbib. Ihre Datenlieferungen und Beteiligungen auf
    verschiedenen Ebenen machen unseren Dienst möglich:
</p>
<ul class="list">
    <li>Alle Teilverbünde des IDS - Informationsverbund Deutschschweiz</li>
    <ul>
        <li>IDS Basel Bern</li>
        <li>NEBIS</li>
        <li>IDS Luzern</li>
        <li>IDS St. Gallen</li>
    </ul>
    <li>Schweizerische Nationalbibliothek</li>
    <li>RERO - Réseau des bibliothèques de Suisse occidentale</li>
    <li>SBT - Sistema bibliotecario ticinese</li>
    <li>Bibliotheksverbund Alexandria</li>
    <li>Aargauer Bibliotheksnetz</li>
    <li>Bibliotheksverbund Graubünden</li>
    <li>St. Galler Bibliotheksnetz</li>
    <li>Liechtensteiner Bibliotheken</li>
    <li>retro.seals.ch - digitalisierte Zeitschriften</li>
    <li>e-codices - Virtuelle Handschriftenbibliothek der Schweiz</li>
    <li>ZORA - Zurich Open Repository and Archive</li>
    <li>Archivbestände der Nationalbibliothek</li>
    <ul>
        <li>Catalogue collectif suisse des affiches</li>
        <li>Digitalisate des Schweizerischen Literaturarchives</li>
        <li>Digitalisate des Eidgenössischen Archivs für Denkmalpflege</li>
    </ul>
</ul>
<p>
    Folgende Bestände sollen 2015-2016 in swissbib integriert werden:
</p>
<ul class="list">
    <li>Bibliotheken Schaffhausen</li>
    <li>Bibliotheken Thurgau</li>
    <li>E-Books der Universitäten Basel und Bern</li>
    <li>BORIS -  Bern Open Repository and Information System</li>
    <li>Infoscience - Scientific publications of EPFL</li>
    <li>réro doc - Bibliothèque numérique de RERO</li>
    <li>Bibliographie für Schweizer Geschichte</li>
    <li>HAN - Handschriften, Archive, Nachlässe</li>
    <li>Weitere Archivbestände</li>
</ul>

<h2>Entwicklung und Design</h2>
<p>
    Für Entwicklung und Design unserer Webseite werden wir von der Firma <a href="https://www.snowflake.ch/" target="_blank">snowflake (Zürich)</a>
    unterstützt.
</p>

<h2>Technologie</h2>
<p>
    Swissbib verwendet unterschiedliche Software-Komponenten, um eine hohe Qualität und Verfügbarkeit zu gewährleisten:
</p>
<ul class="list">
    <li>Datenaufbereitung: <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.oclc.org/de/de/cbs/default.htm')?>" target="_blank">CBS - Metadata management solution</a> von OCLC.</li>
    <li>Suchmaschine: <a href="<?= $this->redirectProtocolwrapper()->getWrappedURL('http://lucene.apache.org/solr')?>" target="_blank">Apache Solr/Lucene</a> (Open Source)</li>
    <li>Nutzeroberfläche: <a href="<?= $this->redirectProtocolwrapper()->getWrappedURL('http://vufind-org.github.io/vufind')?>" target="_blank">vufind</a> (Open Source)</li>
    <li>Weitere Komponenten der Gesamtlösung: <a href="https://github.com/swissbib" target="_blank">swissbib</a> (Open Source)</li>
</ul>
</p>

<h2>Partner- und Teilprojekte</h2>
<p>
    Swissbib versteht sich auch als offene Plattform, von welcher Daten, Softwarelösungen und Knowhow zur Verfügung gestellt werden, um eigene Projekte
    zu realisieren. Folgende Projekte stützen sich in unterschiedlichem Ausmass auf swissbib
</p>
<ul class="list">
    <li>swissbib Basel Bern - Regionaler Katalog des Bibliotheksverbunds IDS Basel Bern</li>
    <li>jusbib - Metakatalog für juristische Fachliteratur</li>
    <li>Kartenportal.ch - Fachportal für Karten in Schweizer Bibliotheken und Archiven</li>
    <li>linked.swissbib.ch (Schwesterprojekt) - Publikation der Schweizer Bibliotheksdaten als linked open data</li>
</ul>

<h2>Weitere Informationen</h2>
<p>
    Zusätzliche Informationen zum Projekt oder Möglichkeiten, uns zu kontaktieren, finden Sie unter folgenden Adressen:
</p>
<ul class="list">
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.swissbib.blogspot.ch')?>" target="_blank">Blog</a></li>
    <li><a title="<?= $this->transEsc('menu.feedback') ?>" href="" id="feedback"><?= $this->transEsc('menu.feedback') ?></a></li>
    <li><a href="&#109;&#97;&#x69;&#x6c;&#116;&#111;&#58;&#115;&#x77;&#105;&#x73;&#115;&#98;&#x69;&#98;&#45;&#117;&#x62;&#64;&#x75;&#x6e;&#x69;&#x62;&#97;&#x73;&#x2e;&#99;&#x68;"><?= $this->transEsc('Email') ?></a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/ub-hauptbibliothek/wir-ueber-uns/adresse-kontakte')?>" target="_blank">Adresse (Projekt swissbib, Universitätsbibliothek Basel)</a></li>
    <li><a href="https://www.swissbib.org" target="_blank">Projekt-Wiki</a></li>
</ul>