<h2>Projekt swissbib</h2>
<p>swissbib ist ein nationales Projekt, das vom Bund gefördert wird. ... SUK-P2
    Unter der Federführung der Universitätsbibliothek Basel
</p>

<h2>Datenlieferung</h2>
<ul class="list">
    <li>Alle Teilverbünde des IDS - Informationsverbund Deutschschweiz</li>
    <li>Schweizerische Nationalbibliothek</li>
    <li>RERO - Réseau des bibliothèques de Suisse occidentale</li>
    <li>sbt - Sistema bibliotecario ticinese und die Mehrheit der IDS-Partner</li>
    <li>Bibliotheksverbund Alexandria</li>
</ul>

<h3>Übersetzung</h3>
<p>Die französische und italienische Version der Oberfläche wurde den Schweizer Erfordernissen angepasst. Ebenso werden
    die Inhalte auf swissbib übersetzt.</p>
<ul class="list">
    <li>Französische Oberfläche: Mitglieder der COPAC von RERO</li>
    <li>Französische Inhaltselemente: UB Basel</li>
    <li>Italienische Oberfläche und Inhaltselemente: Biblioteca Universitaria Lugano</li>
</ul>

<h2>Entwicklung und Design</h2>
<p>
    Das Design und Konzept der Webseite wurde durch <a href="http://www.nose.ch" target="_blank">Nose Design AG</a>
    erstellt.</p>

<h2>Die Software-Lösung hinter swissbib</h2>
<p>Die Software-Lösung für swissbib besteht aus den drei Komponenten:
<ul class="list">
    <li>Datenaufbereitung: <a href="http://www.oclc.org/de/de/cbs/default.htm" target="_blank">CBS - Metadata management
            solution</a> von OCLC.
    </li>
    <li>Suchmaschine: <a href="http://lucene.apache.org/solr/" target="_blank">Apache Solr/Lucene</a> (Open Source)</li>
    <li>Nutzeroberfläche: <a href="http://www.vufind.org" target="_blank">vufind</a> (Open Source)</li>
    <li>einzelne Komponenten der Gesamtlösung: <a href="https://github.com/swissbib" target="_blank">swissbib</a> (Open Source)</li>
</ul>
</p>


<p>Folgende Verbünde und Bibliotheken sind bereits in swissbib enthalten:</p>
<ul class="list">
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22SBT%22') ?>" target="_blank">Sistema
            bibliotecario ticinese </a></li>
    <!-- (32 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSBB%22') ?>" target="_blank">IDS Basel/Bern</a>
    </li>
    <!-- (193 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSLU%22') ?>" target="_blank">IDS Luzern</a>
    </li>
    <!-- (30  Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22SNL%22') ?>" target="_blank">Schweizerische
            Nationalbibliothek</a></li>
    <!-- (1 Bibliothek) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22IDSS*%22') ?>" target="_blank">IDS St. Gallen</a>
    </li>
    <!-- (36 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22NEBIS%22') ?>" target="_blank">NEBIS</a></li>
    <!-- (172 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22RERO%22') ?>" target="_blank">RERO Westschweizer
            Bibliotheksverbund</a></li>
    <!--  (236 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22SGBN%22') ?>" target="_blank">St. Galler
            Bibliotheksnetz</a></li>
    <!--  (52 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22BGR%22') ?>" target="_blank">Bibliotheksverbund
            Graubünden</a></li>
    <!-- (26 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ABN%22') ?>" target="_blank">Aargauer
            Bibliotheksnetz</a></li>
    <!-- (25 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ALEX%22') ?>" target="_blank">Bibliotheksverbund
            Alexandria</a></li>
    <!-- (20 Bibliotheken) -->
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22LIBIB%22') ?>" target="_blank">Liechtensteiner
            Bibliotheken</a></li>
    <!-- (25 Bibliotheken -->
</ul>

<h2>Was ist (noch) nicht enthalten?</h2>
<p>2015-2016 werden weitere Verbünde und Bibliotheken in swissbib verfügbar werden:</p>
<ul class="list">
    <li>Bibliotheken Schaffhausen</li>
    <li>Bibliotheken Thurgau</li>
</ul>


<p>Ausserdem bietet swissbib weitere Datenquellen an:</p>
<ul class="list">
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22CCSA%22') ?>" target="_blank">Catalogue collectif
            suisse des affiches</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=institution%3A%22CHARCH02%22') ?>" target="_blank">Digitalisate
            des Schweizerischen Literaturarchives</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=institution%3A%22CHARCH01%22') ?>" target="_blank">Digitalisate
            des Eidgenössischen Archivs für Denkmalpflege</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ECOD%22') ?>" target="_blank">e-codices</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22RETROS%22') ?>"
           target="_blank">retro.seals.ch</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22SERVAL%22') ?>" target="_blank">SERVAL</a></li>
    <li><a href="<?= $this->basePath('Search/Results?filter=union%3A%22ZORA%22') ?>" target="_blank">ZORA</a></li>
</ul>

<p>2014-2015 werden folgende Datenquellen hinzukommen:</p>
<ul class="list">
    <li>rerodoc</li>
    <li>alexandria</li>
    <li>BORIS</li>
    <li>infoscience</li>
    <li>Bibliographie für Schweizer Geschichte</li>
</ul>
