<div class="home-content-box">
    <h2 class="lead">Redesign 2015</h2>
    <p>A partire dal 5 maggio 2015 swissbib Basel Bern si adatta dinamicamente alle dimensioni dei diversi schermi. In questo modo le ricerche possono essere effettuate senza restrizioni su smartphone, tablet o computer.</p>

    <a href="http://swissbib-baselbern.blogspot.com/2015/05/redesign-2015.html" target="_blank" class="btn btn-link">Più info</a>
</div>
