<div class="home-content-box">
  <h2 class="lead">Serve aiuto?</h2>
    <!--<p><iframe width="230" height="160" src="<?= $this->redirectProtocolWrapper()->getWrappedURL('https://tube.switch.ch/embed/8e47b4c8') ?>" style="border:none" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe></p>
  <a href="<?= $this->url('help-page', array('topic' => 'search')); ?>" class="btn btn-link">Più info</a>-->
    <p>Cominciate con i nostri video (in tedesco):</p>
    <p><a href="https://tube.switch.ch/videos/8e47b4c8" target="_blank" class="btn btn-link"><i class="fa fa-play-circle"></i> Ricerca base</a></p>
    <p><a href="https://tube.switch.ch/videos/5cf66034" target="_blank" class="btn btn-link"><i class="fa fa-play-circle"></i> Richiedere</a></p>
</div>