<?
$record         = $this->driver;
$viewRecord     = $this->record($record);

$subjectVocabularies = $record->getAllSubjectVocabularies(true);
$placeNames = $record->getHierarchicalPlaceNames();

/* Display Standard-IDs */
$isbns  = $record->getISBNs();
$issns  = $record->getISSNs();
$ismns  = $record->getISMNs();
$dois   = $record->getDOIs();
$urns   = $record->getURNs();

$alttitle = $record->getAltTitle();

$series      = $record->getSeries();
$recordLinks = $record->getAllRecordLinks();
$nextTitles  = $record->getNewerTitles();
$prevTitles  = $record->getPreviousTitles();
?>

<table class="table table-striped" summary="<?=$this->transEsc('Description')?>">

    <? if (!empty($isbns)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
        <th><?=$this->transEsc('ISBN')?>: </th>
        <td>
            <? foreach ($isbns as $field): ?>
                <?=$this->escapeHtml($field)?><br/>
            <? endforeach; ?>
        </td>
    </tr>
    <? endif; ?>

    <? if (!empty($issns)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
        <th><?=$this->transEsc('ISSN')?>: </th>
        <td>
            <? foreach ($issns as $field): ?>
                <?=$this->escapeHtml($field)?><br/>
            <? endforeach; ?>
        </td>
    </tr>
    <? endif; ?>

    <? if (!empty($ismns)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
        <th><?= $this->transEsc('ISMN') ?>: </th>
        <td>
            <? foreach ($ismns as $field): ?>
                <?= $this->escapeHtml($field) ?><br/>
            <? endforeach; ?>
        </td>
    </tr>
    <? endif; ?>

    <? if (!empty($dois)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
        <th><?= $this->transEsc('DOI') ?>: </th>
        <td>
            <? foreach ($dois as $field): ?>
                <?= $this->escapeHtml($field) ?><br/>
            <? endforeach; ?>
        </td>
    </tr>
    <? endif; ?>

    <? if (!empty($urns)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
        <th><?= $this->transEsc('URN') ?>: </th>
        <td>
            <? foreach ($urns as $field): ?>
                <?= $this->escapeHtml($field) ?><br/>
            <? endforeach; ?>
        </td>
    </tr>
    <? endif; ?>

    <? if (!empty($alttitle)): ?>
        <? $contentDisplayed = true; ?>
        <tr>
            <th> <?=$this->transEsc('Other_Title') ?>: </th>
            <td>
                <? foreach ($alttitle as $field): ?>
                    <?= $this->escapeHtml($field) ?><br/>
                <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <? if (!empty($series)): ?>
    <? $contentDisplayed = true; ?>
    <tr>
        <th><?= $this->transEsc('Series') ?>: </th>
        <td>
        <? foreach ($series as $field): ?>
            <? if (is_array($field)): ?>
                <? if (!empty($field['name'])): ?>
                    <?= $this->escapeHtml($field['name']) ?>
                    <? if (!empty($field['number'])): ?>
                        <?= $this->escapeHtml($field['number']) ?>
                    <? endif; ?>
                    <br/>
                <? endif; ?>
                <? else: ?>
                    <?= $this->escapeHtml($field) ?> <br/>
                <? endif; ?>
        <? endforeach; ?>
        </td>
    </tr>
    <? endif; ?>

    <? /* Display and link to related items (field configured in config_base.ini -> marc_links) */ ?>
    <? if (!empty($recordLinks)): ?>
    <? $contentDisplayed = true; ?>
        <tr>
            <th><?= $this->transEsc('Related Items') ?></th>
            <td>
                <? foreach ($recordLinks as $recordLink): ?>
                    <?= $this->transEsc($recordLink['title']) ?>:
                    <a href="<?= $this->recordLink()->related($recordLink['link']) ?>"><?= $this->escapeHtml($recordLink['value']) ?></a>
                    <br/>
                <? endforeach; ?>
            </td>
        </tr>
    <? endif; ?>

    <? /* This section is only valid when the above links do not exist */ ?>
    <? if (!empty($nextTitles) or !empty($prevTitles)): ?>
    <? $contentDisplayed = true; ?>
        <tr>
            <? if (!empty($nextTitles)): ?>
                <th><?= $this->transEsc('New Title') ?>: </th>
                <td>
                    <? foreach ($nextTitles as $field): ?>
                        <a href="<?= $viewRecord->getLink('title', $field) ?>"><?= $this->escapeHtml($field) ?></a>
                        <br/>
                    <? endforeach; ?>
                </td>
            <? endif; ?>
        </tr>
        <tr>
            <? if (!empty($prevTitles)): ?>
                <th><?= $this->transEsc('Previous Title') ?>: </th>
                <td>
                    <? foreach ($prevTitles as $field): ?>
                        <a href="<?= $viewRecord->getLink('title', $field) ?>"><?= $this->escapeHtml($field) ?></a>
                        <br/>
                    <? endforeach; ?>
                </td>
            <? endif; ?>
        </tr>
    <? endif; ?>

  <?
  $notes      = $record->getGeneralNotes();
  $freq       = $record->getPublicationFrequency();
  $contDates  = $record->getContResourceDates();
  $diss       = $record->getDissertationNotes();
  $bib        = $record->getBibliographyNotes();
  $access     = $record->getAccessRestrictions();
  $credits    = $record->getProductionCredits();
  $origtitle  = $record->getOriginalTitle();
  $perfomer   = $record->getPerformerNote();
  $awards     = $record->getAwards();
  $citenotes  = $record->getCitationNotes();
  $orignotes  = $record->getOriginalVersionNotes();
  $copynotes  = $record->getCopyNotes();
  $system     = $record->getSystemDetails();
  ?>

  <? if (!empty($notes) or !empty($freq) or !empty($contDates) or !empty($diss) or
      !empty($bib) or !empty($access) or !empty($credits) or !empty($awards) or
      !empty($citenotes) or !empty($orignotes) or !empty($copynotes) or
      !empty($origtitle) or !empty($perfomer) or !empty($system)): ?>
    <? $contentDisplayed = true; ?>

      <? /* Display general notes (field 500) */ ?>
      <? if (!empty($notes)): ?>
        <tr>
          <th><?= $this->transEsc('Item Description') ?>: </th>
          <td>
            <? foreach ($notes as $field): ?>
                <?= $this->escapeHtml($field) ?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* Display publication frequency (field 310) */ ?>
      <? if (!empty($freq)): ?>
        <tr>
          <th><?= $this->transEsc('Publication Frequency') ?>: </th>
          <td>
              <? foreach ($freq as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
              <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* Display Dates of Publication and/or Sequential Designation (field 362) */ ?>
      <? if (!empty($contDates)): ?>
        <tr>
          <th><?= $this->transEsc('Numeration') ?>: </th>
          <td>
              <? foreach ($contDates as $field): ?>
                  <?= $this->escapeHtml($field)?><br>
              <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* Display dissertation notes (field 502) */ ?>
      <? if (!empty($diss)): ?>
        <tr>
          <th><?= $this->transEsc('Dissertation_Note') ?>: </th>
          <td>
              <? foreach ($diss as $field): ?>
                  <?= $this->escapeHtml($field) ?><br/>
              <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* Display bibliography notes (field 504) */ ?>
      <? if (!empty($bib)): ?>
        <tr>
          <th><?= $this->transEsc('Bibliography') ?>: </th>
          <td>
              <? foreach ($bib as $field): ?>
                  <?= $this->escapeHtml($field) ?><br/>
              <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* Display access restriction notes (field 506) */ ?>
      <? if (!empty($access)): ?>
        <tr>
          <th><?= $this->transEsc('Access') ?>: </th>
          <td>
              <? foreach ($access as $field): ?>
                  <?= $this->escapeHtml($field) ?><br/>
              <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* Display production credit notes (field 508) */ ?>
      <? if (!empty($credits)): ?>
        <tr>
          <th><?= $this->transEsc('Production Credits') ?>: </th>
          <td>
              <? foreach ($credits as $field): ?>
                  <?= $this->escapeHtml($field) ?><br/>
              <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* Display original title (field 509) */ ?>
      <? if (!empty($origtitle)): ?>
        <tr>
          <th><?= $this->transEsc('Original_Title') ?>: </th>
          <td>
              <? foreach ($origtitle as $field): ?>
                  <?= $this->escapeHtml($field) ?><br/>
              <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* Display citation / reference note (field 510) */ ?>
      <? if (!empty($citenotes)): ?>
        <tr>
          <th><?= $this->transEsc('Citation_Note') ?>: </th>
          <td>
              <? foreach ($citenotes as $field): ?>
                  <?= $this->escapeHtml($field) ?><br/>
              <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* Display participant / performers note */ ?>
      <? if (!empty($perfomer)): ?>
        <tr>
          <th><?= $this->transEsc('Performer') ?>: </th>
          <td>
              <? foreach ($perfomer as $field): ?>
                  <?= $this->escapeHtml($field) ?><br/>
              <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* Display original version note (field 534) */ ?>
      <? if (!empty($orignotes)): ?>
        <tr>
          <th><?= $this->transEsc('Original_Version_Note') ?>: </th>
          <td>
              <? foreach ($orignotes as $field): ?>
                  <?= $this->escapeHtml($field) ?><br/>
              <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* Display copy and version identification note (fields 562 or 590) */ ?>
      <? if (!empty($copynotes)): ?>
        <tr>
          <th><?= $this->transEsc('Copy_Note') ?>: </th>
          <td>
              <? foreach ($copynotes as $field): ?>
                  <?= $this->escapeHtml($field) ?><br/>
              <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* Display system information note (field 538) */ ?>
      <? if (!empty($system)): ?>
        <tr>
          <th><?= $this->transEsc('Format') ?>: </th>
          <td>
            <? foreach ($system as $field): ?>
                <?= $this->escapeHtml($field) ?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? /* Display award notes (field 586) */ ?>
      <? if (!empty($awards)): ?>
        <tr>
          <th><?= $this->transEsc('Awards') ?>: </th>
          <td>
              <? foreach ($awards as $field): ?>
                  <?= $this->escapeHtml($field) ?><br/>
              <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>
  <? endif; ?>

    <?
    /** == Rara-Elements (place name, special entries == */
    ?>
    <? if ($placeNames): ?>
    <? $contentDisplayed = true; ?>
        <th><?= $this->transEsc('PublicationPlace') ?></th>
        <td>
            <? foreach ($placeNames as $field): ?>
                <?= $this->escapeHtml($field) ?><br />
            <? endforeach; ?>
        </td>
    <? endif; ?>

    <? /** == Schlagworte */ ?>
    <? if($subjectVocabularies): ?>
    <? $contentDisplayed = true; ?>
    <? /* ohne allgemeine Überschrift, Design @todo
    <th><?= $this->transEsc('Subjects') ?></th>
    */ ?>
    <? foreach ($subjectVocabularies as $vocabulary => $fieldsData): ?>
        <tr>
            <th><?= $this->transEsc('vocabulary.' . $vocabulary, array(), $vocabulary) ?>: </th>
            <td>
            <? foreach ($fieldsData as $fieldIndex => $fieldData): ?>
                <? foreach ($fieldData as $fieldValues): ?>
                    <? /* Optional: Filter out numeric fields directly here in template
                          $fieldValues = array_filter($fieldValues, function($value) {
                             return !is_numeric($value);
                          }); */ ?>
                        <?= $this->escapeHtml(implode(' > ', $fieldValues)) ?><br />
                    <? endforeach; ?>
                <? endforeach; ?>
            </td>
        </tr>
    <? endforeach; ?>
    <? endif; ?>

    <? if (!isset($contentDisplayed) || !$contentDisplayed): // Avoid errors if there were no rows above ?>
    <tr>
        <td><?=$this->transEsc('no_description')?></td>
    </tr>
  <? endif; ?>
</table>
