<?php

/** @var  Swissbib\RecordDriver\SolrMarc $record */
$record = $this->driver;
$holdings = $record->getHoldingsStructure();

// Copy favorites to own container
$holdings = $this->extractFavoriteInstitutionsForHoldings($holdings);

// Set page title.
$this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());

?>
<? if ($holdings): ?>

  <div class="panel-group" id="groups" role="tablist" aria-multiselectable="true">
    <? foreach ($holdings as $groupCode => $group): ?>
    <!-- begin: group -->
    <div class="panel panel-default" id="group-<?= $groupCode ?>">
      <!-- begin: group heading -->
      <div class="panel-heading" role="tab" id="heading-<?= $groupCode ?>">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#groups" href="#collapse-<?= $groupCode ?>" aria-expanded="true" aria-controls="collapse-<?= $groupCode ?>">
            <? if (is_array($group['label'])): ?>
              <? $group['label'] = implode('', array_unique($group['label'])); ?>
            <? endif; ?>
            <span><?= $this->zendTranslate($group['label']) ?></span>
          </a>
        </h4>
      </div>
      <!-- end: group heading -->
      <!-- begin: group content -->
      <div id="collapse-<?= $groupCode ?>" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-<?= $groupCode ?>">
        <div class="panel-body">

          <div class="panel-group" id="institutions-<?= $groupCode ?>" role="tablist" aria-multiselectable="true">
          <? foreach ($group['institutions'] as $institutionCode => $institution): ?>

            <!-- begin: institution -->
            <div class="panel panel-default" id="institution-<?= $institutionCode ?>">
              <!-- begin: institution heading -->
              <div class="panel-heading" role="tab" id="heading-<?= $institutionCode ?>">
                <h4 class="panel-title">
                  <a data-toggle="collapse" data-parent="#institutions-<?= $groupCode ?>" href="#collapse-<?= $institutionCode ?>" aria-expanded="true" aria-controls="collapse-<?= $institutionCode ?>">
                    <?= $this->escapeHtml($this->zendTranslate($institution['label'], 'institution')) ?>
                  </a>
                </h4>
              </div>
              <!-- end: institution heading -->

              <!-- begin: institution content -->
              <div id="collapse-<?= $institutionCode ?>" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-<?= $institutionCode ?>">
                <div class="panel-body">
                </div>
              </div>
              <!-- end: institution content -->
            </div>
            <!-- end: institution -->

          <? endforeach; ?>
          </div>

        </div>
      </div>
      <!-- end: group content -->
    </div>
    <!-- end: group -->

    <? endforeach; ?>

  </div>



  <!-- old code below - remove after redesign -->

  <? foreach ($holdings as $groupCode => $group): ?>
    <!-- begin: innerbox <?= $groupCode ?> -->
    <div class="innerbox grey holdingsBox" id="holdings-<?= $groupCode ?>">
      <?
      $expandLib = isset($_GET['expandlib']) ? $_GET['expandlib'] : '';
      $expandedOrCollapsedClass = 'collapsed';
      $expandOnLoad = '';
      if (isset($group['institutions']) && sizeof($group['institutions'])) {
        foreach ($group['institutions'] as $institutionSysCode => $institution) {
          if ($institutionSysCode == $expandLib) {
            $expandedOrCollapsedClass = 'expanded';
            $expandOnLoad = $groupCode;
          }
        }
      }
      ?>

      <? if ($expandOnLoad != ''): ?>
        <script type="text/javascript">
          // On DOM-ready: expand selected library even if it's collapsed via cookie
          $(document).ready(function () {
            var toggleButton = $('#library_toggler_<?=$expandOnLoad?>').get(0),
                cookieName = encodeURI("toggler_" + jQuery(toggleButton).attr("id"));
            if (jQuery.cookie(cookieName) && jQuery.cookie(cookieName) != "expanded") {
              toggleButton.click();
            }

            var institutionToggleButton = $('#holding-institution-<?=$expandOnLoad?>-<?=$expandLib?>');
            if (institutionToggleButton) {
                institutionToggleButton.click();
            }
          });
        </script>
      <? endif; ?>

      <h3 class="toggler persist <?= $expandedOrCollapsedClass ?>" id="holding-group-<?= $groupCode ?>">
        <? if (is_array($group['label'])): ?>
          <? $group['label'] = implode('', array_unique($group['label'])); ?>
        <? endif; ?>
        <span><?= $this->zendTranslate($group['label']) ?></span>
      </h3>

      <div class="holding-group-<?= $groupCode ?>">

        <div class="innerbox">
          <? foreach ($group['institutions'] as $institutionCode => $institution): ?>
            <div class="institutionBox institution-<?= $institutionCode ?>-box"
                 id="holding-institution-<?= $groupCode ?>-<?= $institutionCode ?>-box">
              <h4 id="holding-institution-<?= $groupCode ?>-<?= $institutionCode ?>" class="toggler institutionToggler">
                <?= $this->escapeHtml($this->zendTranslate($institution['label'], 'institution')) ?>
              </h4>

              <? if ($this->institutionDefinedAsFavorite()->isInstitutionDefinedAsFavorite($institutionCode)): ?>
                <ul class="miniactions miniactions-<?= $institutionCode ?> hidden-print">
                  <li class="institutionFavorite">
                    <? $favoriteLabel = isset($institution['favorite']) ? 'mylibraries.remove' : 'mylibraries.add'; ?>
                    <a href="javascript:void(0)"
                       title="<?= $this->transEsc($favoriteLabel) ?>"><?= $this->transEsc($favoriteLabel) ?></a>
                  </li>
                </ul>
              <? endif; ?>

              <div class="holding-institution-<?= $groupCode ?>-<?= $institutionCode ?>" id="holding-institution-<?= $institutionCode ?>">
                <div class="holdingsAjaxSpinner holding-ajax-spinner-<?= $groupCode ?>-<?= $institutionCode ?>">
                  <span class="spinner"></span>
                  <span>Loading...</span>
                </div>
              </div>
            </div>
          <? endforeach; ?>

        </div>
      </div>
    </div>
    <!-- end: innerbox <?= $groupCode ?> -->

  <? endforeach; ?>

  <div id="holdings-items-popup" style="display:none">
    Loading...
  </div>

  <script type="text/javascript">
    swissbib.Holdings.initRecord('<?=$record->getUniqueID()?>');
    swissbib.HoldingFavorites.initRecord('<?=$record->getUniqueID()?>');
    vufindString.favoriteReload = '<?=$this->transEsc('mylibraries.reload')?>';
  </script>

<? else: ?>

  <?= $this->render('RecordTab/holdingils-noholdings') ?>

<? endif; ?>