<div class="hidden-sm hidden-xs">
    <?=$this->transEsc("Showing")?>
    <strong><?=$this->localizedNumber($this->results->getStartRecord())?></strong> - <strong><?=$this->localizedNumber($this->results->getEndRecord())?></strong>
    <? if (!isset($this->skipTotalCount)): ?>
      <?=$this->transEsc('of')?> <strong><?=$this->localizedNumber($this->recordTotal)?></strong>
    <? endif; ?>
</div>

<div class="hidden-md hidden-lg">
    <strong><?=$this->localizedNumber($this->recordTotal)?></strong> <?=$this->transEsc("Results")?>
</div>