<h1>Über swissbib Basel Bern</h1>
<p>swissbib Basel Bern verzeichnet über 7 Mio. Titel aus über 200 <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">wissenschaftlichen Bibliotheken in Basel und Bern</a> (Bibliotheken der Universitäten Basel und Bern, Nationalbibliothek, einige Spezialbibliotheken sowie Fachhochschulbibliotheken).</p>
<p>Das Projekt wird getragen vom <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.informationsverbund.ch/21.0.html') ?>" target="_blank">Verbund IDS Basel Bern</a> und nutzt Infrastruktur und Know How des gesamtschweizerischen Metakatalogs <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('https://www.swissbib.ch') ?>" target="_blank" title="swissbib">swissbib</a>.</p>
<h2>Was findet man in swissbib Basel Bern?</h2>
<p>In swissbib Basel Bern können zwei separate Datenbanken durchsucht werden:</p>
<p><strong>Bücher & mehr</strong></p>
<ul>
    <li>Verschiedenste Medien wie Bücher/E-Books, Zeitschriften/E-Journals, Zeitungen, CD/DVD, Datenbanken etc. Verzeichnet sind die <strong>Titel</strong> dieser Medien, <strong>i.d.R. nicht einzelne Artikel oder Kapitel</strong> daraus.</li>
    <li>Retrodigitalisierte wissenschaftliche Zeitschriften aus der Schweiz (Projekt retro.seals), mit Direktzugang zu den digitalen Artikeltexten.</li>
</ul>
<p><strong>Artikel & mehr</strong></p>
<ul>
    <li><strong>Artikel, Buchkapitel, Textbeiträge</strong> etc. aus zahlreichen E-Journals, E-Books und Datenbanken, die von den Universitäten Basel bzw. Bern zur Verfügung gestellt werden. In den meisten Fällen kann von einem Universitätsstandort aus direkt auf den elektronischen Volltext zugegriffen werden.</li>
    <li>Elektronische Ressourcen, die frei im Internet und somit auch ausserhalb der Universitäten Basel und Bern zugänglich sind.</li>
</ul>
<p>Titel, zu denen kein direkter Volltextzugang besteht, können Sie via <i class="fa fa-external-link"></i> SFX-Services bei Ihrer Bibliothek bestellen.</p>
<h2>Kontakt</h2>
<p>Gerne unterstützen wir Sie bei der Recherche und beim Bestellen in unserem Katalog oder nehmen Ihre Anregungen und Kritik entgegen:</p>
<ul>
    <li>Fragen zu Ihrem Konto oder zu bestimmten Medien: Wenden Sie sich bitte an Ihre Stammbibliothek bzw. die <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">Bibliothek</a>, die das Medium besitzt.</li>
    <li>Fragen und Anregungen zur Suchoberfläche swissbib Basel Bern: <a id="feedbackLink" class="modal-link" href="<?= $this->url('feedback-home') ?>"><?= $this->transEsc("menu.contact") ?></a></li>
</ul>
<h2>News</h2>
<p>Abonnieren Sie unseren <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch') ?>" target="_blank">Blog</a>.</p>



<!--<h1>A proposito di swissbib</h1>

<h2>Contatto</h2>
<ul class="list">
    <li>Per domande concernenti il tuo conto ti preghiamo di contattare la <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/" target="_blank">tua biblioteca</a>.</li>
    <li>Per domande concernenti un determinato documento ti preghiamo di contattare direttamente la <a href="<?/*= $this->url('libraries-index') */?>">biblioteca</a> che lo possiede.</li>
    <li>Contatto swissbib Basel Bern: inviaci una e-mail a <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> oppure scrivi un commento sul nostro <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a>.</li>
</ul>

<h2>News</h2>
<p>Segui il nostro <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a></p>
</br>
<h1>Fonte dei dati</h1>

<h2>Libri &amp; più</h2>
<ul class="list">
<li>Le biblioteche scientifiche di <a href="<?/*= $this->url('libraries-index') */?>#nav_0">Basilea</a> e <a href="<?/*= $this->url('libraries-index') */?>#nav_1">Berna</a></li>
<li><a href="http://retro.seals.ch" target="_blank">retro.seals</a>: riviste scientifiche retrodigitalizzate</li>  
</ul> 
<h2>Articoli &amp; più</h2>
<ul class="list">
    <li>In <i>Articoli &amp; più</i> troverai i contenuti di numerosi periodici elettronici, gli e-book e le banche dati in abbonamento presso le biblioteche universitarie di Basilea e/o Berna. Nella maggior parte dei casi è possibile accedere direttamente al testo integrale in versione elettronica (articolo di rivista, capitolo di e-book, ecc.), se ci si trova in una sede universitaria.</li>
    <li>Il catalogo <i>Articoli &amp; più</i> contiene inoltre risorse elettroniche liberamente accessibili in rete.</li>
    <li>I documenti per i quali non è possibile un accesso diretto al testo integrale possono essere ordinati presso la tua biblioteca universitaria tramite prestito interbibliotecario.</li>
    <li>Per ulteriori informazioni riguardanti le fonti catalogate, vedi <a href="http://www.proquest.com/products-services/The-Summon-Service.html" target="_blank">ProQuest</a>.</li>
</ul>-->
