<h1>A proposito di swissbib Basel Bern</h1>
<p>swissbib Basel Bern comprende più di 7 mio. di notizie bibliografiche provenienti da oltre 200 <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">biblioteche accademiche di Basilea e Berna</a> (biblioteche delle università di Basilea e Berna, Biblioteca nazionale svizzera, alcune biblioteche specializzate e biblioteche di scuole universitarie professionali).</p>
<p>Questo progetto è stato affidato al <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.informationsverbund.ch/21.0.html') ?>" target="_blank">sistema bibliotecario IDS Basel Bern</a> e si serve dell'infrastruttura e del know-how del metacatalogo nazionale <a href="https://www.swissbib.ch" target="_blank" title="swissbib">swissbib</a>.</p>
<h2>Che cosa si trova in swissbib Basel Bern?</h2>
<p>swissbib Basel Bern è suddiviso in due banche dati separate:</p>
<p><strong>Libri & più</strong></p>
<ul>
    <li>per diversi tipi di documenti, come libri/ebook, riviste/ejournal, giornali, CD/DVD, banche dati, ecc. Vengono catalogati i <strong>titoli</strong> di questi documenti, <strong> ma di regola non i singoli articoli o capitoli</strong> in essi contenuti.</li>
    <li>per riviste scientifiche retrodigitalizzate in Svizzera (progetto retro.seals), con accesso diretto ai testi integrali degli articoli.</li>
</ul>
<p><strong>Articoli & più</strong></p>
<ul>
    <li><strong>per singoli articoli, capitoli, contributi,</strong> ecc. estratti da numerosi ejournal, ebook e banche dati messi a disposizione dalle università di Basilea, risp. Berna. Nella maggior parte dei casi è possibile l'accesso diretto al testo integrale, se si effettua la ricerca nella propria rete di ateneo.</li>
    <li>per risorse elettroniche disponibili gratuitamente in Internet, e dunque accessibili anche al di fuori della rete universitaria di Basilea e Berna.</li>
</ul>
<p>Gli articoli che non sono accessibili direttamente in versione elettronica possono essere ordinati presso la tua biblioteca tramite i <i class="fa fa-external-link"></i> servizi SFX.</p>
<h2>Contatto</h2>
<p>Siamo lieti di aiutarti nella ricerca o nell'ordinazione di documenti nel nostro catalogo, e di ricevere suggerimenti o critiche.</p>
<ul>
    <li>Per domande relative al tuo conto o a un determinato documento ti preghiamo di contattare la tua biblioteca o, risp., la  <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">biblioteca</a> che possiede il documento.</li>
    <li>Per domande o opinioni concernenti l'interfaccia di swissbib Basel Bern: <a id="feedbackLink" class="modal-link" href="<?= $this->url('feedback-home') ?>"><?= $this->transEsc("menu.contact") ?></a></li>
</ul>
<h2>News</h2>
Iscriviti al nostro <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://swissbib-baselbern.blogspot.ch') ?>" target="_blank">blog</a>.