<h1>Costi / Termini di spedizione</h1>
<h2>Servizio di corriere IDS</h2>
<p>Documenti che appartengono a una biblioteca con servizio di corriere IDS possono essere ordinati, ritirati e restituiti presso qualsiasi altra biblioteca con servizio di corriere IDS:</p><ul>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a100/?S=1') ?>" target="_blank">Basel UB Hauptbibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a140/?S=1') ?>" target="_blank">Basel UB Medizin</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a125/?S=1') ?>" target="_blank">Basel UB Wirtschaft - SWA</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b400') ?>" target="_blank">Bern UB Zentralbibliothek/Speichermagazin</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b410') ?>" target="_blank">Bern UB Basisbibliothek Unitobler</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b500') ?>" target="_blank">Bern UB Bibliothek vonRoll</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/index.php?id=1218') ?>" target="_blank">Luzern Zentral- und Hochschulbibliothek Sempacherstrasse</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/index.php?id=1219') ?>" target="_blank">Luzern Zentral- und Hochschulbibliothek UNI/PH-Gebäude</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.unisg.ch/wissen/bibliothek') ?>" target="_blank">St. Gallen HSG</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.sg.ch/home/kultur/kantonsbibliothek.html') ?>" target="_blank">St. Gallen Kantonsbibliothek Vadiana</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zb.uzh.ch') ?>" target="_blank">Zürich Zentralbibliothek</a></li>
</ul>

<p>Ulteriori biblioteche di Berna con servizio di corriere con le dette biblioteche di Basilea:</p>
<ul>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b452') ?>" target="_blank">Bern UB Fachbereichsbibliothek Bühlplatz</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b465') ?>" target="_blank">Bern UB Juristische Bibliothek</a> (punto di ritiro)</li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b415') ?>" target="_blank">Bern UB Schweizerische Osteuropabibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zb.unibe.ch/aleph/biblinfo/b517.html') ?>" target="_blank">Bern PH Weiterbildung und Medienbildung</a></li>
</ul>
<p><strong>Costi:</strong> Fr. 5.- per documento. Pagamento in contanti al momento del ritiro. Per il mancato ritiro di documenti ordinati viene fatturato il medesimo importo.</p>
<p><strong>Tempi di consegna:</strong> I documenti ordinati online vengono prelevati dal corriere IDS giornalmente (salvo il sabato) dalla biblioteca prestante e, di regola, consegnati entro due giorni lavorativi alla biblioteca che hai scelto come punto di ritiro. Lì i documenti rimangono riservati per te durante l'arco di una settimana.</p>
<h2>Servizio di corriere Basilea e Berna</h2>
<p>I corrieri locali di <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/ausleihe/kurier-und-fernleihe') ?>" target="_blank" title="Basler Kurier">Basilea</a> e <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/bestellen__ausleihen/kurier') ?>" target="_blank" title="Berner Kurier">Berna</a> sono gratuiti.
<h2>Invio postale di documenti dalla UB Basel o dalla UB Bern al tuo recapito privato</h2>
<p><strong>Costi:</strong> Fr. 12.- per documento. </p>
<p><strong>Tempi di consegna:</strong> Da lunedì a venerdì gli ordini verranno elaborati e spediti entro 24 ore.</p>
<h2>Invio di copie (per posta o in formato elettronico) dalla UB Basel o dalla UB Bern</h2>
<p><strong>Costi per utenti privati:</strong> Fr. 8.- ogni 20 pagine.</p>
<p><strong>Costi per imprese:</strong> Fr. 24.- per ordini fino a 20 pagine, successivamente Fr. 8.- ogni 20 pagine supplementari.
<p><strong>Tempi di consegna:</strong> Da lunedì a venerdì elaborazione dell'ordine entro 24 ore.</p>
<p>I costi verranno fatturati dall'IDS Basel Bern.</p>
<p><strong>Contatto:</strong> Inkasso-/Clearingstelle UB ZB Bern, +41 (0)31 631 92 21, <a href="mailto:clearing@ub.unibe.ch">clearing@ub.unibe.ch</a></p>
<h2>Invio al tuo recapito privato da altre biblioteche</h2>
<p>Per le condizioni delle altre biblioteche, vedi il relativo sito web: <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">Biblioteca</a></p>