<h1>FAQ</h1>
<h2>Ricerca, Ricerca avanzata</h2>
<ul class="list">
    <li>
        <strong>Posso limitare la mia ricerca a una determinata biblioteca?</strong>
        <br/>Ci sono varie possibilità. Nella lista dei risultati, puoi usare il filtro <i>Affinare la ricerca - Biblioteca</i> oppure <i>Affinare la ricerca - Preferite</i> (se hai già predefinito delle biblioteche preferite).<br/>Nella ricerca avanzata puoi selezionare una biblioteca sotto <i>Affinare la ricerca</i>.
    </li>
    <li>
        <strong>Perché qualche volta non posso accedere al testo integrale?</strong>
        <br/>L'accesso diretto al testo integrale spesso funziona solo all'interno della rete di un'università che possieda una sottoscrizione per i contenuti. Effettua il login tramite VPN se non ti trovi in una sede universitaria.
    </li>
</ul>
           
<h2>Ordinare</h2>
<ul class="list">
    <li>
        <strong>Potete inviarmi il documento xy?</strong>
        <br/>Scegli la biblioteca dalla quale desideri ordinare il documento. Clicca su <i>Ordinare</i>. Se è possibile la spedizione postale al tuo recapito privato, la troverai quale opzione sotto <i>Punto di ritiro/invio</i>.
    </li>
</ul>

<h2>My swissbib</h2>
<ul class="list">
    <li>
        <strong>Come arrivare velocemente alla mia lista dei prestiti?</strong>
        <br/>Effettua il login, poi clicca su <i>Conto: il tuo nome</i> in alto a destra.
    </li>
</ul>
       
<h2>Non trovi risposta alla tua domanda?</h2>       
<ul class="list">
    <li>
        Per domande concernenti il tuo conto ti preghiamo di contattare la <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/" target="_blank">tua biblioteca</a>.
    </li>
    <li>
        Per domande concernenti un determinato documento ti preghiamo di contattare direttamente la <a href="<?= $this->url('libraries-index') ?>">biblioteca</a> che lo possiede.<br/>Link dal catalogo: clicca sull'icona <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_link-external.gif') ?>" alt="Info biblioteca"> sotto Localizzazione.
    </li>
    <li>
        Contatto swissbib Basel Bern: inviaci una e-mail a <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> oppure scrivi un commento sul nostro <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">blog</a>.
    </li>
</ul>

<h2>Das Richtige nicht gefunden?</h2>
<ul class="list">
    <li>Erweitern Sie Ihre Suche auf <a href="https://www.swissbib.ch/" target="_blank">swissbib.ch</a> (ganze Schweiz) und bestellen Sie bequem aus <a href="http://www.ub.unibas.ch/ids-basel-bern/ids-kurierbibliotheken/" target="_blank">IDS-Kurierbibliotheken.</a></li>
    <li>Schicken Sie uns Ihren Fernleihauftrag: Bestellformular <a href="http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/ausleihe/kurier-und-fernleihe/fernleihformular/" target="_blank">UB Basel</a> / <a href="http://www.ub.unibe.ch/content/bestellen__ausleihen/fernleihe/bestellformular/index_ger.html" target="_blank">UB Bern</a></li>
    <li>Schicken Sie uns Ihren Anschaffungsvorschlag: Anschaffungsvorschlag <a href="http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/ausleihe/anschaffungsvorschlag/" target="_blank">UB Basel</a> / <a href="http://www.ub.unibe.ch/content/bestellen__ausleihen/anschaffungsvorschlaege/index_ger.html" target="_blank">UB Bern</a></li>
</ul>