<h1>Login</h1>
<p>Identificarti con il numero e la password della tua tessera utente IDS Basel Bern.</p>
<!--
<p>Se possiedi una tessera utente valida per qualsiasi biblioteca cooperante, puoi identificarti come d'abitudine:</p>
<ul class="list">
    <li>IDS Basel Bern</li>
    <li>IDS Luzern</li>
    <li>IDS St. Gallen</li>
    <li>NEBIS</li>
    <li>St. Galler Bibliotheksnetz</li>
</ul>
-->
<h2>Non hai un conto?</h2>
<p><a href="http://aleph.unibas.ch/F/?func=bor-new-0&CON_LNG=ENG"
      target="_blank"><?= $this->transEsc('Create New Account') ?></a></p>

<h2>Perché il login?</h2>
<p>Per effettuare dei prestiti, per salvare le tue biblioteche preferite, per recuperare liste o ricerche che hai
    salvato, per modificare le impostazioni.</p>

<h2>Hai dimenticato la password?</h2>
<p>Contatta la <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/" target="_blank">tua biblioteca</a>.
</p>

<h2>Profilo</h2>
<p><a href="http://aleph.unibas.ch/F/?func=LOGIN-PAGE" target="_blank">Cambia password, indirizzo, ecc.</a></p>

<h2>Perché il logout?</h2>
<p>Se stai usando un computer pubblico, effettua il logout per evitare che qualcun altro utilizzi il tuo conto.</p>
</br>
<h1>Il mio swissbib</h1>
<h2>Ricerche salvate</h2>
<p>Se non hai effettuato il login, le tue ricerche saranno salvate fino a quando non chiudi il browser. Puoi ripetere
    una ricerca oppure, dopo il login, salvarla a tempo indeterminato.</p>

<h2>Preferite</h2>
<p>Se vuoi aggiungere una biblioteca alle <i>Preferite</i> puoi farlo attraverso <i>Il mio swissbib - Preferite</i>
    oppure cliccando sull'icona del <img
        src="<?= $this->basePath('themes/swissbib/images/icon_favorit_library.gif') ?>"
        alt="<?= $this->transEsc('mylibraries.add')?>"
        title="<?= $this->transEsc('mylibraries.add')?>"> nel catalogo. Nella tua lista di risultati queste biblioteche sono marcate con un <img
        src="<?= $this->basePath('/themes/swissbib/images/icon_favorit_library.gif') ?>"
        alt="Favorit"> e possono essere usate come filtro.</p>

<h2>Liste</h2>
<ul class="list">
    <li>Dopo il login puoi salvare dei titoli nelle tue liste: <br />
        <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_notepad_add.gif') ?>"
             alt="<?= $this->transEsc('memorizelistadd')?>"
             title="<?= $this->transEsc('memorizelistadd')?>">
    </li>
    <li>Se crei una nuova lista mentre stai salvando un titolo dovrai cliccare due volte su <i>Salva</i>.</li>
    <li>Pubblico = Lista visibile per tutti che conoscono l'URL</li>
    <li>Personale = Lista visibile solo a te</li>
</ul>

<h2>Impostazioni</h2>
<p>Lingua dell'interfaccia del catalogo, numero di titoli per pagina</p>

<h2>Conto IDS Basel Bern</h2>
<p>Funzioni di prestito</p>
