<div class="home-content-box">
    <h2 class="lead">Über swissbib</h2>
    <p>
        Swissbib ist der Katalog aller Schweizer Hochschulbibliotheken, der Schweizerischen Nationalbibliothek, zahlreicher Kantonsbibliotheken und weiterer Institutionen. Er bietet einen raschen, einfachen und umfassenden Zugang zu wissenschaftlichen Publikationen in der Schweiz an.
    </p>
    <a href="<?= $this->basePath('Libraries') ?>" class="btn btn-link" title="Liste der Institutionen">Teilnehmende Institutionen</a>
</div>
