<div class="home-content-box">
  <h2 class="lead">Redesign 2015</h2>
  <p>
      In spring 2015, swissbib puts on new clothes. Responsive Design adapts dynamically to the size of your screen. You will be able to use swissbib without limitations on a smartphone, a tablet, or a desktop computer.
  </p>
    <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.swissbib.blogspot.ch/') ?>" target="_blank" class="btn btn-link" title="Link to our blog">Read more</a>
</div>