<div class="home-content-box">
    <h2 class="lead">About swissbib</h2>
    <p>
        Swissbib is the catalog of all Swiss university libraries, the Swiss national library, several cantonal libraries and of other institutions. It provides a convenient, fast and comprehensive gateway to academic publications in Switzerland.
    </p>
    <a href="<?= $this->basePath('Libraries') ?>" class="btn btn-link" title="List of institutions">Participating institutions</a>
</div>