<table class="table table-condensed">
  <tr>
    <th><?=$this->transEsc('Library')?></th>
    <th><?=$this->transEsc('Location')?></th>
    <th><?=$this->transEsc('Status')?></th>
  </tr>
  <? $i = 0; foreach ($this->statusItems as $item): ?>
    <? if (++$i == 5) break; // Show no more than 5 items ?>
    <tr>
      <td class="fullLocation">
        <!-- <? var_dump($item); ?>--> 
        <? $locationText = $this->transEsc('location_' . $item['location'], [], $item['location']); ?>
        <? $locationText = $this->transEsc($item['branchname']); ?>
        <? if (isset($item['locationhref']) && $item['locationhref']): ?>
          <a href="<?=$item['locationhref']?>" target="_blank"><?=$locationText?></a>
        <? else: ?>
          <?=$locationText?>
        <? endif; ?>
      </td>
      <td class="fullCallnumber">
        <?=$this->transEsc($item['sublocation'])?>
        <? if ($this->callnumberHandler): ?>
           - <a href="<?=$this->url('alphabrowse-home') ?>?source=<?=$this->escapeHtmlAttr($this->callnumberHandler) ?>&amp;from=<?=$this->escapeHtmlAttr($item['callnumber']) ?>"><?=$this->escapeHtml($item['callnumber'])?></a>
        <? else: ?>
          -
          <? if (!empty($item['callnumber']) || $item['callnumber'] === "0"):?>
             <?=$this->escapeHtml($item['callnumber'])?>
          <? else: ?>
            <?
                $callnumberString = $item['pseudocallnumber'];
                if(strpos($callnumberString,"CH") === false) {
                    $callnumberString = mb_substr($callnumberString,0,3,"UTF-8");
                }
                $callnumberString = rtrim($callnumberString, ",.; ");
            ?>
          <?=$callnumberString?>
          <? endif; ?>
        <? endif; ?>
      </td>
      <td class="fullAvailability">
        <? if (isset($item['use_unknown_message']) && $item['use_unknown_message']): ?>
          <span><?=$this->transEsc("status_unknown_message")?></span>
        <? elseif ($item['availability']): ?>
          <span class="text-success"><?=($item['reserve'] == 'Y') ? $this->transEsc("On Reserve") : $this->transEsc("Available")?></span>
        <? else: ?>
          <span class="text-danger"><?=$this->transEsc($item['status'])?></span>
        <? endif; ?>
        <? if(!empty($item['item_notes'])): ?>
          <br /><span style="font-weight: normal"><?=$this->transEsc("Note")?>:</span> <span><?=join(',', $item['item_notes'])?></span>
        <? endif; ?>
      </td>
    </tr>
  <? endforeach; ?>
<? if (count($this->statusItems) > 5): ?>
  <tr><td colspan="3"><a href="<?=$this->url('record', ['id' => $this->statusItems[0]['id']])?>"><?=count($this->statusItems) - 5?> <?=$this->transEsc('more')?> ...</a></td></tr>
<? endif; ?>
</table>
