<div class="home-content-box">

    <h2 class="lead">Redesign 2015</h2>
    <p>As of May 5 the user interface of swissbib Basel Bern will adapt its display depending on the device it is used on. Searches on smart phones, tablets or desktop PCs adapt automatically for optimal usability.</p>

    <a href="http://swissbib-baselbern.blogspot.com/2015/04/redesign-2015.html" class="btn btn-link">Weiterlesen</a>

</div>