<div class="home-content-box">
  <h2 class="lead">Redesign 2015</h2>
    <p>
     Swissbib Basel Bern erscheint im Frühling 2015 in einem neuen Kleid. Das Responsive Design passt sich dynamisch der Bildschirmgrösse diverser Endgeräte an, Sie können damit swissbib ohne Einschränkungen auf dem Smartphone, dem Tablet oder dem PC nutzen. Die neue Oberfläche geht am 4. Mai 2015 live.
    </p>
  <a href="" class="btn btn-link">Weiterlesen</a>
</div>