<div class="home-content-box">
    <h2 class="lead">Über jusbib</h2>
    <p>
        jusbib ist ein Metakatalog von Schweizer Rechtsbibliotheken und weiteren relevanten Beständen der juristischen Literatur. Oberfläche und Suchfunktionalitäten von jusbib entsprechen jenen von swissbib.
    </p>
    <a href="<?= $this->basePath('Libraries') ?>" class="btn btn-link" title="Liste der Institutionen">Teilnehmende Institutionen</a>
</div>
