<div class="home-content-box">
  <h2 class="lead">Wie weiter?</h2>
    <iframe width="230" height="160" src="<?= $this->redirectProtocolWrapper()->getWrappedURL('https://tube.switch.ch/embed/8e47b4c8') ?>" style="border:none" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
  <a href="<?= $this->url('help-page', array('topic' => 'search')); ?>" class="btn btn-link">Weiterlesen</a>
</div>