<div class="home-content-box">
    <h2 class="lead">Redesign 2015</h2>
    <p>swissbib Basel Bern passt sich ab 5. Mai 2015 dynamisch der Bildschirmgrösse diverser Endgeräte an. So kann damit ohne Einschränkungen auf dem Smartphone, Tablet oder Computer recherchiert werden.</p>

    <a href="http://swissbib-baselbern.blogspot.com/2015/05/redesign-2015.html" target="_blank" class="btn btn-link">Weiterlesen</a>
</div>