<div class="home-content-box">
  <h2 class="lead">Wie weiter?</h2>
  <p>

      Suchen, Finden, Personalisieren, Weiterleiten, uvm.
  </p>
   <!-- <iframe src="https://tube.switch.ch/embed/945c5e7b" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>-->
  <a href="<?= $this->url('help-page', array('topic' => 'myswissbib')); ?>" class="btn btn-link">Weiterlesen</a>
</div>