<h4><?=$this->transEsc('Your Account')?></h4>
<ul class="nav nav-list">
  <? if ($this->userlist()->getMode() !== 'disabled'): ?>
    <li<?=$this->active == 'favorites' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-favorites')?>"><?=$this->transEsc('Favorites')?> <i class="fa fa-star pull-right"></i></a></li>
  <? endif; ?>
  <? if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
    <li<?=$this->active == 'checkedout' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-checkedout')?>"><?=$this->transEsc('Checked Out Items')?> <i class="fa fa-book pull-right"></i></a></li>
    <li<?=$this->active == 'holds' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-holds')?>"><?=$this->transEsc('Holds and Recalls')?> <i class="fa fa-flag pull-right"></i></a></li>
    <? if ($this->ils()->checkFunction('StorageRetrievalRequests')): ?>
    <li<?=$this->active == 'storageRetrievalRequests' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-storageretrievalrequests')?>"><?=$this->transEsc('Storage Retrieval Requests')?> <i class="fa fa-archive pull-right"></i></a></li>
    <? endif; ?>
    <? if ($this->ils()->checkFunction('ILLRequests')): ?>
    <li<?=$this->active == 'ILLRequests' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-illrequests')?>"><?=$this->transEsc('Interlibrary Loan Requests')?> <i class="fa fa-exchange pull-right"></i></a></li>
    <? endif; ?>
    <li<?=$this->active == 'fines' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-fines')?>"><?=$this->transEsc('Fines')?> <i class="fa fa-usd pull-right"></i></a></li>
    <li<?=$this->active == 'profile' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-profile')?>"><?=$this->transEsc('Profile')?> <i class="fa fa-user pull-right"></i></a></li>
  <? endif; ?>
  <li<?=$this->active == 'history' ? ' class="active"' : ''?>><a href="<?=$this->url('search-history')?>?require_login"><?=$this->transEsc('history_saved_searches')?> <i class="fa fa-search pull-right"></i></a></li>
  <? if ($user = $this->auth()->isLoggedIn()): ?>
    <li><a href="<?=$this->url('myresearch-logout')?>"><?=$this->transEsc("Log Out")?> <i class="fa fa-signout pull-right"></i></a></li>
  <? endif; ?>
</ul>
<? if ($this->auth()->isLoggedIn() && $this->auth()->getManager()->supportsPasswordChange()): ?>
  <h4><?=$this->transEsc('Preferences')?></h4>
  <ul class="nav nav-list">
    <li<?=$this->active == 'newpassword' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-changepassword') ?>"><?=$this->transEsc('Change Password') ?> <i class="fa fa-lock pull-right"></i></a></li>
  </ul>
<? endif; ?>
<? if ($this->userlist()->getMode() !== 'disabled' && $user = $this->auth()->isLoggedIn()): ?>
  <h4><?=$this->transEsc('Your Lists')?></h4>
  <ul class="nav nav-list">
    <li<?=$this->active == 'favorites' ? ' class="active"' : ''?>><a href="<?=$this->url('myresearch-favorites')?>"><?=$this->transEsc('Your Favorites')?> <i class="fa fa-star pull-right"></i></a></li>
    <? $lists = $user->getLists() ?>
    <? foreach ($lists as $list): ?>
        <li<?=$this->active == 'list' . $list['id'] ? ' class="active"' : ''?>> <a href="<?=$this->url('userList', array('id' => $list['id']))?>"><?=$this->escapeHtml($list['title'])?> <span class="pull-right"><?=$list->cnt?></span></a></li>
    <? endforeach; ?>
    <li><a href="<?=$this->url('editList', array('id'=>'NEW'))?>" title="<?=$this->transEsc('Create a List') ?>"><?=$this->transEsc('Create a List') ?> <span class="pull-right"><i class="fa fa-plus"></i></span></a></li>
  </ul>
<? endif ?>
