<h2>Über jusbib</h2>
<p>
    Jusbib ist der <b>Metakatalog</b> der Schweizer Rechtsbibliotheken und weiterer relevanter Bestände <b>der juristischen Literatur</b>.
    Oberfläche und Suchfunktionalitäten von Jusbib entsprechen jenen von Swissbib.
</p>
<p>
    Zusätzlich können die Datensätze mittels einer einheitlichen Rechtsklassifikation abgefragt werden. Es handelt sich um die
    mehrsprachige systematische <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://isdc.ch/d2wfiles/document/5445/4018/0/Plan%20syst%20D(ISDC).pdf') ?>"
                                   target="_blank">Klassifikation des Schweizerischen Instituts für Rechtsvergleichung</a>.
</p>
<p>
    Das Projekt Jusbib wurde von der <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.lawlibraries.ch/') ?>" target="_blank">
    Vereinigung der juristischen Bibliotheken der Schweiz</a> gestartet und in enger Zusammenarbeit mit dem Team von swissbib
    durchgeführt. Es erhält eine finanzielle Unterstützung des <a href="https://www.bj.admin.ch/bj/de/home.html" target="_blank">Bundesamtes für Justiz</a>
    und des Vereins <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.svri.ch/index.html') ?>" target="_blank">eJustice.CH</a>.
</p>
