<? $results = $this->recommend->getResults(); ?>
<? if ($results->getResultTotal() > 0): ?>
  <h4><?=$this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search')?></h4>
<? endif; ?>
<? $checkboxFilters = $results->getParams()->getCheckboxFacets(); if (count($checkboxFilters) > 0): ?>
  <? foreach ($checkboxFilters as $current): ?>
    <div class="checkboxFilter<?=($results->getResultTotal() < 1 && !$current['selected'] && !$current['alwaysVisible']) ? ' hide' : ''?>">
      <label class="checkbox">
        <input type="checkbox" name="filter[]" value="<?=$this->escapeHtml($current['filter'])?>"
        <?=$current['selected'] ? 'checked="checked"' : ''?> id="<?=$this->escapeHtml(str_replace(' ', '', $current['desc']))?>"
        onclick="document.location.href='<?=$current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter'])?>';" />
        <?=$this->transEsc($current['desc'])?>
      </label>
    </div>
  <? endforeach; ?>
<? endif; ?>
<? $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : array(); ?>
<? $collapsedFacets = $this->recommend->getCollapsedFacets() ?>
<? $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); if (!empty($filterList)): ?>
  <div class="list-group filters">
    <li class="list-group-item"><strong><?=$this->transEsc('Remove Filters')?></strong></li>
    <? foreach ($filterList as $field => $filters): ?>
      <? foreach ($filters as $i => $filter): ?>
        <?
          $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
          if ($index !== false) {
              unset($collapsedFacets[$index]); // Open if we have a match
          }
          if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
            $removeLink = $this->currentPath().$results->getUrlQuery()->replaceTerm($filter['value'], '');
          } else {
            $removeLink = $this->currentPath().$results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], true, $filter['operator']);
          }
          if ($filter['displayText'] == '[* TO *]') {
            $filter['displayText'] = $this->translate('filter_wildcard');
          }
        ?>
        <a class="list-group-item active" href="<?=$removeLink?>">
          <span class="badge"><i class="fa fa-minus"></i></span>
          <? if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' '; if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?><?=$this->transEsc($field)?>: <?=$this->escapeHtml($filter['displayText'])?></a>
        </a>
      <? endforeach; ?>
    <? endforeach; ?>
  </div>
<? endif; ?>
<?= isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>
<? $sideFacetSet = $this->recommend->getFacetSet(); $rangeFacets = $this->recommend->getAllRangeFacets(); ?>
<? if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
  <? foreach ($sideFacetSet as $title => $cluster): ?>
    <? $allowExclude = $this->recommend->excludeAllowed($title); ?>
      <div class="panel-group" id="side-panel-<?=$this->escapeHtml($title) ?>">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#side-panel-<?=$this->escapeHtml($title) ?>" href="#side-collapse-<?=$this->escapeHtml($title) ?>"><?=$this->transEsc($cluster['label'])?></a>
            </h4>
          </div>
          <div class="panel-collapse collapse <? if(!in_array($title, $collapsedFacets)): ?> in<? endif ?>" id="side-collapse-<?=$this->escapeHtml($title) ?>">
    <ul class="list-group collapsed">
      <? if (isset($rangeFacets[$title])): ?>
        <li class="list-group-item"><strong><?=$this->transEsc($cluster['label'])?></strong></li>
        <li class="list-group-item">
          <form class="form-inline text-center" action="" name="<?=$this->escapeHtml($title)?>Filter" id="<?=$this->escapeHtml($title)?>Filter">
            <?=$results->getUrlQuery()->asHiddenFields(array('page' => "/./", 'filter' => "/^{$title}:.*/"))?>
            <input type="hidden" name="<?=$this->escapeHtml($rangeFacets[$title]['type'])?>range[]" value="<?=$this->escapeHtml($title)?>"/>
            <div class="row">
              <label class="col-md-6" for="<?=$this->escapeHtml($title)?>from">
                <?=$this->transEsc('date_from')?>:<br/>
                <input type="text" maxlength="4" class="col-md-12" name="<?=$this->escapeHtml($title)?>from" id="<?=$this->escapeHtml($title)?>from" value="<?=isset($rangeFacets[$title]['values'][0])?$this->escapeHtml($rangeFacets[$title]['values'][0]):''?>" />
              </label>
              <label class="col-md-6" for="<?=$this->escapeHtml($title)?>to">
                <?=$this->transEsc('date_to')?>:<br/>
                <input type="text" maxlength="4" class="col-md-12" name="<?=$this->escapeHtml($title)?>to" id="<?=$this->escapeHtml($title)?>to" value="<?=isset($rangeFacets[$title]['values'][1])?$this->escapeHtml($rangeFacets[$title]['values'][1]):''?>" />
              </label>
            </div>
            <? if ($rangeFacets[$title]['type'] == 'date'): ?>
              <div><input type="text" class="col-md-10 hidden" id="<?=$this->escapeHtml($title)?><?=$this->escapeHtml($rangeFacets[$title]['type'])?>Slider"/></div>
            <? endif; ?>
            <input class="btn btn-default" type="submit" value="<?=$this->transEsc('Set')?>"/>
          </form>
        </li>
        <? if ($rangeFacets[$title]['type'] == 'date'): ?>
          <? $this->headScript()->appendFile('bootstrap-slider.js'); ?>
          <?
            $min = !empty($rangeFacets[$title][0]) ? min($rangeFacets[$title][0], 1400) : 1400;
            $future = date('Y', time()+31536000);
            $max = !empty($rangeFacets[$title][1]) ? max($future, $rangeFacets[$title][1]) : $future;
            $low  = !empty($rangeFacets[$title][0]) ? $rangeFacets[$title][0] : $min;
            $high = !empty($rangeFacets[$title][1]) ? $rangeFacets[$title][1] : $max;
            $script = <<<JS
$(document).ready(function() {
  var fillTexts = function() {
    var v = {$this->escapeHtml($title)}dateSlider.getValue();
    $('#{$this->escapeHtml($title)}from').val(v[0]);
    $('#{$this->escapeHtml($title)}to').val(v[1]);
  };
  var {$this->escapeHtml($title)}dateSlider = $('#{$this->escapeHtml($title)}dateSlider')
    .slider({
       'min':{$min},
       'max':{$max},
       'handle':"square",
       'tooltip':"hide",
       'value':[{$low},{$high}]
    })
    .on('slide', fillTexts)
    .data('slider');
});
JS;
          ?>
          <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
        <? endif; ?>
      <? else: ?>
        <? foreach ($cluster['list'] as $i=>$thisFacet): ?>
          <?
            if(strlen($thisFacet['displayText']) == 0) {
              $thisFacet['displayText'] = "-";
            }
          ?>
          <? $moreClass = 'narrowGroupHidden-'.$this->escapeHtml($title).' hidden'; ?>
        <? if ($i == 6): ?>
          <a id="more-narrowGroupHidden-<?=$this->escapeHtml($title)?>" class="list-group-item" href="javascript:moreFacets('narrowGroupHidden-<?=$title ?>')"><?=$this->transEsc('more')?> ...</a>
        <? endif; ?>
        <? if ($thisFacet['isApplied']): ?>
          <a class="list-group-item active<? if ($i>5): ?><?=$moreClass ?><?endif ?><? if ($thisFacet['operator'] == 'OR'): ?> facetOR applied" href="<?=$this->currentPath().$results->getUrlQuery()->removeFacet($title, $thisFacet['value'], true, $thisFacet['operator']) ?><? endif ?>">
            <? if($thisFacet['operator'] == 'OR'): ?>
              <i class="fa fa-check"></i>
            <? else: ?>
              <span class="badge"><i class="fa fa-check"></i></span>
            <? endif; ?>
            <?=$this->escapeHtml($thisFacet['displayText'])?>
          </a>
        <? else: ?>
          <a href="<?=$this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], $thisFacet['operator'])?>" class="list-group-item facet<?=$thisFacet['operator'] ?><? if ($i>5): ?> <?=$moreClass ?><?endif ?>">
            <? if($thisFacet['operator'] == 'OR'): ?>
              <i class="fa fa-check-empty"></i>
            <? endif; ?>
            <span class="badge">
              <? if ($allowExclude): ?>
                <?=number_format($thisFacet['count'])?><a href="<?=$this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], 'NOT') ?>" title="<?=$this->transEsc('exclude_facet') ?>"><i class="fa fa-remove"></i></a>
              <? else: ?>
                <?=number_format($thisFacet['count'])?>
              <? endif; ?>
            </span>
            <?=$this->escapeHtml($thisFacet['displayText'])?>
          </a>
        <? endif; ?>
      <? endforeach; ?>
        <? if ($i > 5): ?><a class="list-group-item <?=$moreClass ?>" href="javascript:lessFacets('narrowGroupHidden-<?=$title ?>')"><?=$this->transEsc('less')?> ...</a><? endif; ?>
      <? endif; ?>
    </ul>
    </div>
    </div>
    </div>
  <? endforeach; ?>
<? endif; ?>