<div class="<?=$this->layoutClass('mainbody')?>" id="libraryList">
    <? $i = 0; ?>
    <? foreach ($this->groupedInstitutions as $institutionGroup): ?>
        <?=
        $this->render(
            'libraries/group',
            array(
                 'group'        => $institutionGroup['group'],
                 'institutions' => $institutionGroup['institutions'],
                 'nr'           => $i++
            )
        ) ?>
    <? endforeach; ?>
</div>
<div class="<?=$this->layoutClass('sidebar')?> hidden-xs">
  <div id="libraryListSidebar" class="affix" role="complementary">
    <ul class="list-group nav sidenav">
      <? $arrayLength = count($this->groupedInstitutions);
      for ($i = 0; $i < $arrayLength; $i++): ?>
        <li class="list-group-item">
          <a href="#nav_<?= $i ?>"><?= $this->groupedInstitutions[$i]['group']['label'][$this->layout()->userLang] ?></a>
        </li>
      <? endfor; ?>
    </ul>
  </div>
</div>

<script type="text/javascript">
  $('body').scrollspy({target: '#libraryListSidebar'});
</script>