<? $results = $this->recommend->getResults(); ?>
<? if ($results->getResultTotal() > 0): ?>
  <h4><?=$this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search')?></h4>
<? endif; ?>
<? $checkboxFilters = $results->getParams()->getCheckboxFacets(); if (count($checkboxFilters) > 0): ?>
<?
  $html = '';
  $shown = 0;
  foreach ($checkboxFilters as $current) {
    $html .= '<label class="checkbox';
    $html .= '"><input type="checkbox" name="filter[]" value="'.$this->escapeHtmlAttr($current['filter']).'"
      '. ($current['selected'] ? 'checked="checked"' : '') .' id="'.$this->escapeHtmlAttr(str_replace(' ', '', $current['desc'])).'"
      onclick="document.location.href=\''.($current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter'])).'\';" />'.$this->transEsc($current['desc']).'</label>';
  }
?>
  <div class="checkboxFilter"><?=$html ?></div>
<? endif; ?>
<? $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : array(); ?>
<? $collapsedFacets = $this->recommend->getCollapsedFacets() ?>
<? $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); if (!empty($filterList)): ?>
  <ul class="list-group filters">
    <li class="list-group-item title"><?=$this->transEsc('Remove Filters')?></li>
    <? foreach ($filterList as $field => $filters): ?>
      <? foreach ($filters as $i => $filter): ?>
        <?
          $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
          if ($index !== false) {
              unset($collapsedFacets[$index]); // Open if we have a match
          }
          if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
            $removeLink = $this->currentPath().$results->getUrlQuery()->replaceTerm($filter['value'], '');
          } else {
            $removeLink = $this->currentPath().$results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], true, $filter['operator']);}
            //$removeLink = $this->currentPath().$results->getUrlQuery()->removeFacet($filter['field'], $this->translateFacets($filter['field'],$filter['value']), true, $filter['operator']);}
          if ($filter['displayText'] == '[* TO *]') {
            $filter['displayText'] = $this->translate('filter_wildcard');
          }
        ?>
        <a class="list-group-item active" href="<?=$removeLink?>">
          <span class="pull-right"><i class="fa fa-times"></i></span>
          <? if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' ';
             if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?>
             <?=$this->transEsc($field)?>:
             <?=$this->escapeHtml($this->translateFacets(array('facetName' => $filter['field'], 'facetValue' => $filter['value'])))?>
        </a>
      <? endforeach; ?>
    <? endforeach; ?>
  </ul>
<? endif; ?>
<?= isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>


<!--
  MyLibraries (swissbib jargon 'Favoriten' are implemented as Solr-QueryFacets
  They are going to be merged with the usual Term-FacetList placed in the SideFacets component of VF2
  Because we use institutions as additional facets beside 'Favoriten'  but 'Favoriten' are queried against the institution index in Solr too
  I added an additional mylibrary index field which enables us to merge both groups in one list in the SideFacets Component
  One alternative could be to map the field names on the level of the application (complicated configuration, error prone and complicated for
  others to work with it. Another alternative to could be to use a separated template only for these facets (and to duplicate code) which isn't really nice also
-->
  <? $sideFacetSet = array_merge($this->recommend->getMyLibraries(),$this->recommend->getFacetSet()); $rangeFacets = $this->recommend->getAllRangeFacets(); ?>
<? if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
  <? foreach ($sideFacetSet as $title => $cluster): ?>
    <? $allowExclude = $this->recommend->excludeAllowed($title); ?>
    <ul class="list-group" id="side-panel-<?=$this->escapeHtmlAttr($title) ?>">
      <li class="list-group-item title<? if(in_array($title, $collapsedFacets)): ?> collapsed<? endif ?>" data-toggle="collapse" href="#side-collapse-<?=$this->escapeHtmlAttr($title) ?>">
        <?=$this->transEsc($cluster['label'])?>
      </li>
      <div id="side-collapse-<?=$this->escapeHtmlAttr($title) ?>" class="collapse<? if(!in_array($title, $collapsedFacets)): ?> in<? endif ?>">
        <? if (isset($rangeFacets[$title])): ?>
          <? if ($rangeFacets[$title]['type'] == 'date'): ?>
            <? $this->headScript()->appendFile('vendor/bootstrap-slider.js'); ?>
            <?
            $min = !empty($rangeFacets[$title]['values'][0]) ? min($rangeFacets[$title]['values'][0], 1450) : 1450;
            $future = date('Y', time()+31536000);
            $max = !empty($rangeFacets[$title]['values'][1]) ? max($future, $rangeFacets[$title]['values'][1]) : $future;
            $low  = !empty($rangeFacets[$title]['values'][0]) ? $rangeFacets[$title]['values'][0] : $min;
            $high = !empty($rangeFacets[$title]['values'][1]) ? $rangeFacets[$title]['values'][1] : $max;
            $script = <<<JS
$(document).ready(function() {
  var fillTexts = function() {
  var v = {$this->escapeHtmlAttr($title)}dateSlider.getValue();
  $('#{$this->escapeHtmlAttr($title)}from').val(v[0]);
  $('#{$this->escapeHtmlAttr($title)}to').val(v[1]);
  };
  var {$this->escapeHtmlAttr($title)}dateSlider = $('#{$this->escapeHtmlAttr($title)}dateSlider')
  .slider({
     'min':{$min},
     'max':{$max},
     'handle':"square",
     'tooltip':"hide",
     'value':[{$low},{$high}]
  })
  .on('slide', fillTexts)
  .data('slider');
});
JS;
            ?>
            <?= $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
          <? endif; ?>
          <li class="list-group-item">
            <form action="" name="<?=$this->escapeHtmlAttr($title)?>Filter" id="<?=$this->escapeHtmlAttr($title)?>Filter">
              <?=$results->getUrlQuery()->asHiddenFields(array('page' => "/./", 'filter' => "/^{$title}:.*/"))?>
              <input type="hidden" name="<?=$this->escapeHtmlAttr($rangeFacets[$title]['type'])?>range[]" value="<?=$this->escapeHtmlAttr($title)?>"/>
              <div class="row">
                <div class="col-sm-6">
                  <label for="<?=$this->escapeHtmlAttr($title)?>from">
                    <?=$this->transEsc('date_from')?>:
                  </label>
                  <input type="text" maxlength="4" class="form-control" name="<?=$this->escapeHtmlAttr($title)?>from" id="<?=$this->escapeHtmlAttr($title)?>from" value="<?=isset($rangeFacets[$title]['values'][0])?$this->escapeHtmlAttr($rangeFacets[$title]['values'][0]):''?>" placeholder="<?= $rangeFacets[$title]['type'] == 'date' ? $min : '' ?>" />
                </div>
                <div class="col-sm-6">
                  <label for="<?=$this->escapeHtmlAttr($title)?>to">
                    <?=$this->transEsc('date_to')?>:
                  </label>
                  <input type="text" maxlength="4" class="form-control" name="<?=$this->escapeHtmlAttr($title)?>to" id="<?=$this->escapeHtmlAttr($title)?>to" value="<?=isset($rangeFacets[$title]['values'][1])?$this->escapeHtmlAttr($rangeFacets[$title]['values'][1]):''?>" placeholder="<?= $rangeFacets[$title]['type'] == 'date' ? $max : '' ?>" />
                </div>
              </div>
              <? if ($rangeFacets[$title]['type'] == 'date'): ?>
                <div class="slider-container"><input type="text" class="hidden" id="<?=$this->escapeHtmlAttr($title)?><?=$this->escapeHtml($rangeFacets[$title]['type'])?>Slider"/></div>
              <? endif; ?>
              <input class="btn btn-default" type="submit" value="<?=$this->transEsc('Set')?>"/>
            </form>
          </li>
        <? else: ?>
          <? foreach ($cluster['list'] as $i=>$thisFacet): ?>
            <?
              if(strlen($thisFacet['displayText']) == 0) {
                $thisFacet['displayText'] = "-";
              }
            ?>
            <? $moreClass = 'narrowGroupHidden-'.$this->escapeHtmlAttr($title).' hidden'; ?>
          <? if ($i == $cluster['displayLimit'] + 1): ?>
            <a id="more-narrowGroupHidden-<?=$this->escapeHtmlAttr($title)?>" class="list-group-item" href="javascript:moreFacets('narrowGroupHidden-<?=$title ?>')"><?=$this->transEsc('more')?> ...</a>
          <? endif; ?>
          <? if ($thisFacet['isApplied']): ?>
            <a class="list-group-item active<? if ($i>$cluster['displayLimit']): ?><?=$moreClass ?><?endif ?><? if (isset($thisFacet['operator']) && $thisFacet['operator'] == 'OR'): ?> facetOR applied<? endif ?>" href="<?=$this->currentPath().$results->getUrlQuery()->removeFacet($title, $thisFacet['value'], true, isset($thisFacet['operator']) ? $thisFacet['operator'] : null) ?>">
                <? if(isset($thisFacet['operator']) && $thisFacet['operator'] == 'OR'): ?>
                <i class="fa fa-check-square-o"></i>
              <? else: ?>
                <span class="pull-right"><i class="fa fa-check"></i></span>
              <? endif; ?>
              <?=$this->escapeHtml($thisFacet['displayText'])?>
            </a>
          <? else: ?>

            <?
               //$thisFacet is often not set and causes a lot of logging
               $tOperator = isset($thisFacet['operator']) ? $thisFacet['operator'] : null;
               $addURL = $this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], !empty($tOperator) ? $tOperator : null);

            ?>

            <? if ($allowExclude): ?>
              <li class="list-group-item facet<?=$thisFacet['operator'] ?><? if ($i>$cluster['displayLimit']): ?> <?=$moreClass ?><?endif ?>">
            <? else: ?>
              <? $tOperatorClass = isset($thisFacet['operator']) ? 'facet' . $thisFacet['operator'] : 'facet'; ?>
              <a href="<?=$addURL ?>" class="list-group-item <?=$tOperatorClass ?><? if ($i>$cluster['displayLimit']): ?> <?=$moreClass ?><?endif ?>">
            <? endif; ?>
            <span class="badge">
              <?=$this->localizedNumber($thisFacet['count'])?>
              <? if ($allowExclude): ?>
                <a href="<?=$this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], 'NOT') ?>" title="<?=$this->transEsc('exclude_facet') ?>"><i class="fa fa-times"></i></a>
              <? endif; ?>
            </span>
            <? if ($allowExclude): ?>
              <a href="<?=$addURL ?>">
            <? endif; ?>
            <? if(isset($thisFacet['operator']) && $thisFacet['operator'] == 'OR'): ?>
              <i class="fa fa-square-o"></i>
            <? endif; ?>
            <?=$this->escapeHtml($thisFacet['displayText'])?>
            <? if ($allowExclude): ?>
                </a>
              </li>
            <? else: ?>
              </a>
            <? endif; ?>
          <? endif; ?>
        <? endforeach; ?>
          <? if ($i > $cluster['displayLimit']): ?><a class="list-group-item <?=$moreClass ?>" href="javascript:lessFacets('narrowGroupHidden-<?=$title ?>')"><?=$this->transEsc('less')?> ...</a><? endif; ?>
        <? endif; ?>
      </div>
    </ul>
  <? endforeach; ?>
<? endif; ?>
