$(document).ready(function() {
  <? if (isset($this->searchDetails) && is_object($this->searchDetails)): ?>
    <? foreach ($this->searchDetails->getQueries() as $searchGroup): ?>
      <? $i = 0; foreach ($searchGroup->getQueries() as $search): ?>
        <? if (++$i == 1): ?>
          var new_group = swissbib.AdvancedSearch.addGroup('<?=addslashes($search->getString())?>', '<?=addslashes($search->getHandler())?>', '<?=$searchGroup->isNegated() ? 'NOT' : $searchGroup->getOperator()?>');
        <? else: ?>
          swissbib.AdvancedSearch.addField(new_group, '<?=addslashes($search->getString())?>', '<?=addslashes($search->getHandler())?>');
        <? endif; ?>
      <? endforeach; ?>
    <? endforeach; ?>
  <? endif; ?>
});
