<?
  // Set page title.
  $this->headTitle($this->translate('Advanced Search'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set up breadcrumbs:
  $lastSearchLink = $this->getLastSearchLink($this->transEsc('Search'), '', '</li>');

  $this->layout()->breadcrumbs = ($lastSearchLink ? $lastSearchLink : '')
    . '<li class="active">' . $this->transEsc('Advanced') . '</li>';

  // Set up saved search details:
  if (isset($this->saved) && is_object($this->saved)) {
    $searchDetails = $this->saved->getParams()->getQuery();
    if ($searchDetails instanceof \VuFindSearch\Query\Query) {
        // Not an advanced query -- ignore it.
        $searchDetails = $groups = false;
    } else {
        $groups = $searchDetails->getQueries();
    }
    $hasDefaultsApplied = $this->saved->getParams()->hasDefaultsApplied();
    $searchFilters = $this->saved->getParams()->getFilterList();
  } else {
    $hasDefaultsApplied = $searchDetails = $searchFilters = $groups = false;
  }

  // Set up Javascript:
  // Step 1: Define our search arrays so they are usuable in the javascript
  $this->headScript()->appendScript($this->render('search/advanced/globals.phtml'));
  // Step 2: Call the javascript to make use of the above
  $this->headScript()->appendFile(
    isset($this->advancedSearchJsOverride) ? $this->advancedSearchJsOverride : 'advanced_search.js'
  );
//  $this->headScript()->appendFile('swissbib/AdvancedSearch.js');

  // Step 3: Build the page
  $this->headScript()->appendScript(
    $this->partial(
      isset($this->buildPageOverride) ? $this->buildPageOverride : 'search/advanced/build_page.phtml',
      array('searchDetails' => $searchDetails)
    )
  );
?>

<?= $this->render('search/advanced/templates-handlebars') ?>

<?=$this->flashmessages()?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <div class="row">
    <div class="advancedSearchTabsWrap">
      <? $this->searchType = 'advanced' ?>
      <?= $this->render('search/searchTabs'); ?>
    </div>

    <form role="search" name="searchForm" id="advSearchForm" method="get" action="<?=$this->url($this->options->getSearchAction())?>">
      <input type="hidden" name="sort" value="relevance">
      <!-- we need this additional field to recognize explicitly search requests out of this context to handle personal settings
      related to sort and limit
      -->
      <input type="hidden" name="advancedSearchFormRequest" value="advancedSearchFormRequest"/>

      <div class="clearfix">
        <p class="lead pull-left"><?=$this->transEsc('Advanced Search')?></p>
        <div id="groupJoin" class="form-inline pull-right">
          <label for="join"><?=$this->transEsc("search_match")?>:</label>
          <select id="search_bool0" name="join" class="form-control">
            <option value="AND"<? if($searchDetails && $searchDetails->getOperator()=='ALL'):?> selected<?endif?>><?= $this->transEsc('group_AND') ?></option>
            <option value="OR"<? if($searchDetails && $searchDetails->getOperator()=='OR'):?> selected<?endif?>><?= $this->transEsc('group_OR') ?></option>
          </select>
        </div>
      </div>

      <div class="row" id="groupPlaceHolder">
        <div class="col-sm-6">
          <a href="#" onClick="swissbib.AdvancedSearch.addGroup()">
            <i  class="fa fa-plus-circle"></i>
            <?= $this->transEsc('add_search_group') ?>
          </a>
        </div>

        <div class="col-sm-6 pull-right">
          <input class="btn btn-primary pull-right" type="submit" value="<?= $this->transEsc('Find')?>">
        </div>
      </div>


      <? if (isset($this->extraAdvancedControls)): ?>
        <?=$this->extraAdvancedControls ?>
        <div class="row">
          <div class="col-sm-12 pull-right">
            <input class="btn btn-primary pull-right" type="submit" value="<?= $this->transEsc('Find')?>"/>
          </div>
        </div>
      <? endif; ?>

    </form>
  </div>
</div>

<?= $this->render('search/advanced/sidebar') ?>
