<?php
$favoriteLanguages = array('ger', 'eng', 'fre', 'ita');
?>

<? if (!empty($this->facetList) || !empty($this->checkboxFacets)): ?>
<div class="row">
  <fieldset class="col-sm-12">
    <legend><?=$this->transEsc('Limit To')?></legend>
    <? if (!empty($this->checkboxFacets)): ?>
      <?=$this->render('search/advanced/checkbox-filters.phtml')?>
    <? endif; ?>
    <div class="row">
      <? foreach ($this->facetList as $field => $list): ?>
        <div class="col-sm-<?=floor(12/count($this->facetList)) ?>">
          <label for="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>"><?=$this->transEsc($list['label'])?></label>
          <select class="form-control" id="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>" name="filter[]" multiple="multiple" size="10">
            <?
              // Sort the current facet list alphabetically; we'll use this data
              // along with the foreach below to display facet options in the
              // correct order.
              $sorted = array();
              foreach ($list['list'] as $i => $value) {
                if (!empty($value['displayText'])) {
                  $sorted[$i] = $value['displayText'];
                }
              }
              natcasesort($sorted);
            ?>

            <?php if (strtolower($field)==="language") : ?>
              <? foreach ($sorted as $index => $display): ?>
                <? $value = $list['list'][$index]; ?>
                <? if (in_array($value['value'], $favoriteLanguages)) : ?>
                  <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>><?=$this->escapeHtml($display)?></option>
                <? endif; ?>
              <? endforeach; ?>

              <optgroup label="<?= $this->transEsc('all_languages') ?>">
            <?php endif; ?>

            <?php if (strtolower($field) === "format_str_mv") : ?>

              <option value='format:"*K01*"' title="article"><?= $this->transEsc('*K01*') ?></option>
              <option value='format:"*K02*"' title="book"><?= $this->transEsc('BK02*') ?></option>
              <option value='format:"*R0*"' title="continuing"><?= $this->transEsc('*R0*') ?></option>
              <option value='format:"*L0*"' title="collection"><?= $this->transEsc('CL0*') ?></option>
              <option value='format:"*U01*"' title="sheet_music"><?= $this->transEsc('MU01*') ?></option>
              <option value='format:"*U03*"' title="sound"><?= $this->transEsc('MU03*') ?></option>
              <option value='format:"*U04*"' title="music"><?= $this->transEsc('MU04*') ?></option>
              <option value='format:"*P0*"' title="map"><?= $this->transEsc('MP0*') ?></option>
              <option value='format:"*M01*"' title="film"><?= $this->transEsc('VM01*') ?></option>
              <option value='format:"*M02*"' title="picture"><?= $this->transEsc('VM02*') ?></option>
              <option value='format:"*M03*"' title="mx_game"><?= $this->transEsc('VM03*') ?></option>
              <option value='format:"*M04*"' title="object"><?= $this->transEsc('VM04*') ?></option>
              <option value='format:"*F0*"' title="software"><?= $this->transEsc('CF0*') ?></option>

              <optgroup label="<?= $this->transEsc('all_formats') ?>">
            <?php endif; ?>

            <? foreach ($sorted as $index => $display): ?>
              <? $value = $list['list'][$index]; ?>
              <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>><?=$this->escapeHtml($display)?></option>
            <? endforeach; ?>

          </select>
        </div>
      <? endforeach; ?>
    </div>
  </fieldset>
</div>
<hr />

<? endif; ?>
<div class="row">
  <? if (isset($this->illustratedLimit)): ?>
    <fieldset class="col-sm-4">
      <legend><?=$this->transEsc("Illustrated")?>:</legend>
      <? foreach ($this->illustratedLimit as $current): ?>
        <input class="form-control" id="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>" type="radio" name="illustration" value="<?=$this->escapeHtmlAttr($current['value'])?>"<?=$current['selected']?' checked="checked"':''?>/>
        <label for="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>"><?=$this->transEsc($current['text'])?></label><br/>
      <? endforeach; ?>
    </fieldset>
  <? endif; ?>
  <?=$this->render('search/advanced/limit.phtml')?>
  <?=$this->render('search/advanced/ranges.phtml')?>
</div>