<script id="adv-search-field" type="text/x-handlebars-template">
  <div class="row">
    <div class="col-sm-6">
      {{{term}}}
    </div>
    <div class="col-sm-6">
      {{{selector}}}
    </div>
  </div>
</script>

<script id="adv-search-field-label" type="text/x-handlebars-template">
  <label for="search_lookfor{{groupIndex}}_{{fieldIndex}}" class="{{classes}}">{{label}}:</label>
</script>

<script id="adv-search-field-term-text" type="text/x-handlebars-template">
    <input type="text" class="text form-control" value="{{value}}" size="{{size}}" name="lookfor{{groupIndex}}[]" id="search_lookfor{{groupIndex}}_{{fieldIndex}}">
</script>

<script id="adv-search-field-field-selector" type="text/x-handlebars-template">
    <select class="select form-control" name="type{{groupIndex}}[]" id="search_typ{{groupIndex}}_{{fieldIndex}}">
      {{#each options}}
      <option value="{{name}}"
      {{#if selected}}selected="selected"{{/if}}>{{label}}</option>
      {{/each}}
    </select>
</script>

<script id="adv-search-group" type="text/x-handlebars-template">
  <div id="group{{groupIndex}}" class="group well clearfix">
    {{{searchDetails}}}
    <div class="row">
        <div class="col-sm-2"></div>
        <div id="group{{groupIndex}}SearchHolder" class="groupSearchHolder col-sm-10 search-input-col"></div>
    </div>
    <div class="row">
      <div class="col-sm-2"></div>
      <div class="col-sm-10">
        {{{addLink}}}
      </div>
    </div>
  </div>
</script>

<script id="adv-search-group-searchDetails" type="text/x-handlebars-template">
  <div class="row">
    <div class="col-sm-2">
      {{{label}}}
    </div>
    <div class="col-sm-7"></div>
    <div class="col-sm-3 pull-right">
      <a onclick="swissbib.AdvancedSearch.deleteThisGroup(this)" id="delete_link_{{groupIndex}}" class="linkbutton small icon_delete" href="javascript:void(0)" style="display: inline;">
        <i class="fa fa-times-circle"></i>
        {{deleteLabel}}
      </a>
    </div>
  </div>
  <div class="row row-connector">
    <div class="col-sm-2"></div>
    <div class="col-sm-10">
      <div class="row">
        <div class="col-sm-6">
          <div class="row">
            <div class="col-sm-2">
              <label for="search_bool{{groupIndex}}">{{matchLabel}}:</label>
            </div>
            <div class="col-sm-10">
              <select name="bool{{groupIndex}}[]" id="search_bool{{groupIndex}}" class="form-control">
               {{#each joins}}
               <option value="{{name}}"
               {{#if selected}}selected="selected"{{/if}}>{{label}}</option>
               {{/each}}
              </select>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</script>

<script id="adv-search-group-addfield" type="text/x-handlebars-template">
    <a onclick="swissbib.AdvancedSearch.addFieldToThisGroup(this)" id="add_search_link_{{groupIndex}}" class="linkbutton small icon_add" href="javascript:void(0)">
      <i id="group{{ groupInex }}Holder" class="fa fa-plus-circle"></i>
      {{addLabel}}
    </a>
</script>



