<?
// Set up page title:
$this->headTitle($this->translate('Bookings'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Bookings') . '</li>';
?>

<div class="<?= $this->layoutClass('mainbody') ?>">
  <h2><?= $this->transEsc('Bookings') ?></h2>
  <?= $this->flashmessages(); ?>

  <div class="col-xs-10 col-sm-8 col-md-7">
  <?php if( sizeof($this->bookings) ): ?>

  <?php foreach ($this->bookings as $index => $booking): ?>
    <hr/>

    <?= $this->escapeHtml($booking['title']) ?>

    <? if (!empty($booking['library'])): ?>
      <br/>
      <strong><?=$this->transEsc('Institution')?>: </strong><?=$this->escapeHtml($booking['library'])?>
      <br />
    <? endif; ?>

    <? if (!empty($booking['callNumber'])): ?>
      <strong><?=$this->transEsc('Call Number')?>:</strong> <?=$this->escapeHtml($booking['callNumber'])?>
      <br />
    <? endif; ?>

    <strong><?=$this->transEsc('pick_up_location') ?>:</strong> <?=$this->transEsc($booking['pickupLocation']) ?><br />

    <strong><?=$this->transEsc('date_from') ?>:</strong> <?=date('d/m/y H:i', $booking['dateStart']) ?><br />

    <strong><?=$this->transEsc('date_to') ?>:</strong> <?=date('d/m/y H:i', $booking['dateEnd']) ?><br />

  <? endforeach; ?>

  <?php else: ?>
    <p><?=$this->transEsc('No bookings') ?></p>
  <?php endif; ?>

</div>
</div>

<div class="<?= $this->layoutClass('sidebar') ?>">
  <?= $this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'bookings')) ?>
</div>



<!--<div class="<?/*= $this->layoutClass('mainbody') */?>">
    <h2><?/*= $this->transEsc('Bookings') */?></h2>
    <?/*= $this->flashmessages(); */?>

    <?php /*if( sizeof($this->bookings) ): */?>
        <p><?/*=$this->transEsc('Your bookings') */?></p>
        <?/*=$this->render('myresearch/bookings/itemlist.phtml')*/?>
    <?php /*else: */?>
        <p><?/*=$this->transEsc('No bookings') */?></p>
    <?php /*endif; */?>

</div>

<div class="<?/*= $this->layoutClass('sidebar') */?>">
    <?/*= $this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'bookings')) */?>
</div>
-->