<?
    // Set up page title:
    $this->headTitle($this->translate('Checked Out Items'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?> resultView">
<h2><?=$this->transEsc('Your Checked Out Items')?></h2>
<?=$this->flashmessages()?>

<? if (!empty($this->transactions)): ?>
  <? if ($this->renewForm): ?>
  <form name="renewals" action="" method="post" id="renewals">
    <div class="toolbar">
      <input type="submit" class="btn btn-default hidden-print" name="renewSelected" value="<?=$this->transEsc("renew_selected")?>" />
<!--          <input type="submit" class="btn btn-default" name="renewAll" value="--><?//=$this->transEsc('renew_all')?><!--" />-->
    </div>
  <? endif; ?>

  <? $i = 0; foreach ($this->transactions as $resource): ?>
    <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
    <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId())?>" class="row result">
      <? if ($this->renewForm): ?>
        <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
          <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
          <input class="pull-left hidden-print col-xs-1"  type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" id="checkbox_<?=$safeId?>" />
          <input class="pull-left" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" />
        <? endif; ?>
      <? endif; ?>
     <!--
        <?/* if ($summThumb = $this->record($resource)->getThumbnail()): */?>
          <img src="<?/*=$this->escapeHtmlAttr($summThumb)*/?>" class="recordcover" alt="<?/*=$this->transEsc('Cover Image')*/?>"/>
        <?/* else: */?>
          <img src="<?/*=$this->url('cover-unavailable')*/?>" class="recordcover" alt="<?/*=$this->transEsc('No Cover Image')*/?>"/>
        <?/* endif; */?>-->
        <div class="col-xs-10">
            <h2 property="name">
        <?
          // If this is a non-missing Solr record, we should display a link:
          if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
            $title = $resource->getTitle();
            $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
            echo '<a href="' . $this->recordLink()->getUrl($resource) .
              '" class="title">' . $title . '</a>';
          } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
            // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
            echo $this->escapeHtml($ilsDetails['title']);
          } else {
            // Last resort -- indicate that no title could be found.
            echo $this->transEsc('Title not available');
          }
        ?></h2>

        <div class="meta">
        <? if (!empty($ilsDetails['library'])): ?>
        <span class="label"><strong><?=$this->transEsc('Institution')?>:</strong></span> <?=$this->escapeHtml($ilsDetails['library'])?>
           <br />
        <? endif; ?>

        <? if (!empty($ilsDetails['callnum'])): ?>
         <span class="label"><strong><?=$this->transEsc('Call Number')?>:</strong></span> <?=$this->escapeHtml($ilsDetails['callnum'])?>
          <br />
        <? endif; ?>

        <span class="label"><strong><?=$this->transEsc('Checked Out') ?>:</strong></span> <?=$this->escapeHtml($ilsDetails['loandate']) ?> <?=$this->transEsc('Due')?> <?=$this->escapeHtml($ilsDetails['duedate'])?><? if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><? endif; ?> <br />

        <? $isRenewable = $ilsDetails['renewable'];
            if ( $isRenewable )
            {
                $renewalLimit = preg_replace('/^\d+ \(out of (\d+)\).*$/', '$1', $ilsDetails['renew_info']);
                if (is_numeric($renewalLimit))
                {
                    $Renewals = $ilsDetails['renewals'] . ' ' .$this->transEsc('of') . ' ' . $renewalLimit;
                }
                else
                {
                    $renewalInfo = preg_replace('/^\d+ \((.*)\).$/', '$1', $ilsDetails['renew_info']);
                    $Renewals = $ilsDetails['renewals'] . ' (' .$this->translate($renewalInfo) . ')';
                    //$Renewals = $ilsDetails['renew_info'];
                }
            }
            else
            {
                $Renewals = $this->translate('no_renewal');
            }
            ?>
        <span class="label"><strong><?=$this->transEsc('Renewals')?>:</strong></span> <?=$this->escapeHtml($Renewals)?>

<!--                <?/* $listAuthor = $resource->getPrimaryAuthor(); if (!empty($listAuthor)): */?>
                <?/*=$this->transEsc('by')*/?>:
                <a href="<?/*=$this->record($resource)->getLink('author', $listAuthor)*/?>"><?/*=$this->escapeHtml($listAuthor)*/?></a><br/>
            <?/* endif; */?>
            <?/* $formats = $resource->getFormats(); if (count($formats) > 0): */?>
                <?/*=str_replace('class="', 'class="label label-info ', $this->record($resource)->getFormatList())*/?>
                <br/>
            <?/* endif; */?>
            <?/* if (!empty($ilsDetails['volume'])): */?>
                <strong><?/*=$this->transEsc('Volume')*/?>:</strong> <?/*=$this->escapeHtml($ilsDetails['volume'])*/?>
                <br />
            <?/* endif; */?>

            <?/* if (!empty($ilsDetails['publication_year'])): */?>
                <strong><?/*=$this->transEsc('Year of Publication')*/?>:</strong> <?/*=$this->escapeHtml($ilsDetails['publication_year'])*/?>
                <br />
            <?/* endif; */?>

            <?/* if (!empty($ilsDetails['institution_name']) && (empty($ilsDetails['borrowingLocation']) || $ilsDetails['institution_name'] != $ilsDetails['borrowingLocation'])): */?>
                <strong><?/*=$this->transEsc('location_' . $ilsDetails['institution_name'], array(), $ilsDetails['institution_name'])*/?></strong>
                <br />
            <?/* endif; */?>

            <?/* if (!empty($ilsDetails['borrowingLocation'])): */?>
                <strong><?/*=$this->transEsc('Borrowing Location')*/?>:</strong> <?/*=$this->transEsc('location_' . $ilsDetails['borrowingLocation'], array(), $ilsDetails['borrowingLocation'])*/?>
                <br />
            <?/* endif; */?>

            <?/* if (isset($ilsDetails['renew'])): */?>
                <strong><?/*=$this->transEsc('Renewed')*/?>:</strong> <?/*=$this->transEsc($ilsDetails['renew'])*/?>
                <?/* if (isset($ilsDetails['renewLimit'])): */?>
                    / <?/*=$this->transEsc($ilsDetails['renewLimit'])*/?>
                <?/* endif; */?>
                <br />
            --><?/* endif; */?>

        <? $showStatus = true; ?>

        <? if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
          <? $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
          <? if (isset($renewDetails['success']) && $renewDetails['success']): ?>
            <? $showStatus = false; ?>
<!--            --><?//=$this->transEsc('Due')?><!-- --><?//=$this->escapeHtml($renewDetails['new_date'])?><!-- --><?// if (isset($renewDetails['new_time'])): ?><!----><?//=$this->escapeHtml($renewDetails['new_time'])?><!----><?// endif; ?>
            <div class="alert alert-success"><?=$this->transEsc('renew_success')?></div>
          <? else: ?>
<!--            --><?//=$this->transEsc('Due')?><!-- --><?//=$this->escapeHtml($ilsDetails['duedate'])?><!----><?// if (isset($ilsDetails['dueTime'])): ?><!-- --><?//=$this->escapeHtml($ilsDetails['dueTime'])?><!----><?// endif; ?>
            <div class="alert alert-danger"><?=$this->transEsc('renew_fail')?><? //if (isset($renewDetails['sysMessage'])): ?>: <?//=$this->escapeHtml($renewDetails['sysMessage'])?><? //endif; ?></div>
          <? endif; ?>
        <? else: ?>
<!--          --><?//=$this->transEsc('Due')?><!-- --><?//=$this->escapeHtml($ilsDetails['duedate'])?><!----><?// if (isset($ilsDetails['dueTime'])): ?><!-- --><?//=$this->escapeHtml($ilsDetails['dueTime'])?><!----><?// endif; ?><!--<br />-->
          <? if ($showStatus): ?>
            <? if (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "overdue"): ?>
              <div class="alert alert-danger"><?=$this->transEsc("renew_item_overdue")?></div>
            <? elseif (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "due"): ?>
              <div class="alert alert-info"><?=$this->transEsc("renew_item_due")?></div>
            <? endif; ?>
          <? endif; ?>
        <? endif; ?>


    </div>

        <? if ($showStatus && isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
          <div class="alert alert-info"><?=$this->transEsc($ilsDetails['message'])?></div>
        <? endif; ?>
        <? if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_link'])): ?>
          <a href="<?=$this->escapeHtmlAttr($ilsDetails['renew_link'])?>"><?=$this->transEsc('renew_item')?></a>
        <? endif; ?>
      </div>
    </div>
  <? endforeach; ?>
  <? if ($this->renewForm): ?></form><? endif; ?>
<? else: ?>
  <?=$this->transEsc('You do not have any items checked out')?>.
<? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
<?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'checkedout'))?>
</div>