<?
/** @var Array $autocompleterData */

// Set up page title:
$this->headTitle($this->translate('mylibraries'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('mylibraries') . '</li>';

$isLoggedIn = !!$this->auth()->isLoggedIn();
?>

<div class="<?= $this->layoutClass('mainbody') ?>">
  <h2><?= $this->transEsc('mylibraries') ?></h2>
  <?= $this->flashmessages(); ?>

  <h3><?= $this->transEsc('mylibraries.add') ?></h3>
  <div class="panel panel-default">

    <form class="form-horizontal panel-body">
      <fieldset class="form-group">
        <label for="query" class="col-sm-2 control-label"><?= $this->transEsc('Library') ?></label>
        <div class="col-sm-10">
          <input type="text" id="query" class="form-control"/>
        </div>
      </fieldset>

      <div class="status information">
        <h4><?= $this->transEsc('mylibraries.title') ?></h4>
        <ul class="list">
          <li><?= $this->transEsc('mylibraries.text.1') ?>.</li>
          <li><?= $this->transEsc('mylibraries.text.2') ?>.</li>
        </ul>
        <?php if ($isLoggedIn): ?>
          <!--   keine Anzeige -->
        <?php else: ?>
          <p><strong><?= $this->transEsc('mylibraries.login') ?></strong></p>
        <?php endif ?>
      </div>
    </form>
  </div>

  <div id="user-favorites">
    <?= $this->render('favorites/selectionList') ?>
  </div>
</div>

<div class="<?= $this->layoutClass('sidebar') ?>">
  <?= $this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'favorite-institutions')) ?>
</div>

<script type="text/javascript">
   jQuery(function () {
     swissbib.FavoriteInstitutions.init(<?=json_encode($autocompleterData)?>);
   });
 </script>