<?
    // Set up page title:
    $this->headTitle($this->translate('My Fines'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Fines') . '</li>';
?>
<div class="<?=$this->layoutClass('mainbody')?> resultView">
  <h2><?=$this->transEsc('Your Fines')?></h2>
  <? if (empty($this->fines)): ?>
    <?=$this->transEsc('You do not have any fines')?>
  <? else: ?>


        <? $totalDue = 0; ?>
        <? foreach ($this->fines as $record): ?>
            <? if (!empty($record['balance'])): ?>
                <?$totalDue += $record['amount']; ?>
            <? endif; ?>
        <? endforeach; ?>
        <p><span><strong><?=$this->transEsc('Total Balance Due') ?>:</strong></span> CHF <?=isset($totalDue) ? number_format($totalDue, 2, '.', '\'') : ''?></p>
        <br />

    <form>
        <div class="col-xs-10">
    <? foreach ($this->fines as $record): ?>
    <div  class="row result">
            <h2 property="name">

            <? if (empty($record['title'])): ?>
              <?=$this->transEsc('not_applicable')?>
            <? elseif (!isset($record['id'])): ?>
              <?=$this->escapeHtml(trim($record['title'], '/:'))?>
            <? else: ?>
              <a href="<?=$this->url('record', array('id' => $record['id']))?>"><?=$this->escapeHtml(trim($record['title'], '/:'))?></a>
            <? endif; ?>
          </h2>

          <div class="meta">
              <? if (!empty($record['institution'])): ?>
              <span class="label"><strong><?=$this->transEsc('Institution')?>:</strong></span> <?=$this->escapeHtml($this->zendTranslate($record['institution'], 'institution'))?>
              <br />
              <? endif; ?>

              <? if (!empty($record['signature'])): ?>
              <span class="label"><strong><?=$this->transEsc('Call Number')?>:</strong></span> <?=$this->escapeHtml($record['signature'])?>
              <br />
              <? endif; ?>

              <span class="label"><strong><?=$this->transEsc('Date') ?>:</strong></span> <?=$this->escapeHtml($record['checkout']) ?>
              <br />

              <span class="label"><strong><?=$this->transEsc('Fee') ?>:</strong></span> CHF <?=isset($record['amount']) ? number_format($record['amount'], 2, '.', '\'') : ''?> (<?=isset($record['description']) ? $this->escapeHtml($record['description']) : ''?>)
              <br/>
          </div>
        </div>
   <? endforeach; ?>
      </div>
    </form>
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'fines'))?>
</div>