<? $loginlink = 'http://aleph.unibas.ch/F/?func=file&file_name=login-session&con_lng' . $lang; ?>

<h4><?=$this->transEsc('Your Account')?></h4>
<ul class="list-group">
  <? if ($this->userlist()->getMode() !== 'disabled'): ?>
    <a href="<?=$this->url('myresearch-favorites')?>" class="list-group-item<?=$this->active == 'favorites' ? ' active' : ''?>">
      <?=$this->transEsc('Favorites')?>
      <span class="pull-right"><i class="fa fa-star"></i></span>
    </a>
  <? endif; ?>
  <? if ('ils-none' !== $this->ils()->getOfflineMode() && true
    /* @todo " && false" for development of swissbib green " && true" for swissbib orange, must be removed after development!,
    it should be possible to have swissbib green and orange in this template together! yay:) */): ?>
    <a href="<?=$this->url('myresearch-checkedout')?>" class="list-group-item<?=$this->active == 'checkedout' ? ' active' : ''?>">
      <?=$this->transEsc('Checked Out Items')?>
      <span class="pull-right"><i class="fa fa-book"></i></span>
    </a>
    <a href="<?=$this->url('myresearch-holds')?>" class="list-group-item<?=$this->active == 'holds' ? ' active' : ''?>">
      <?=$this->transEsc('Holds and Recalls')?>
      <span class="pull-right"><i class="fa fa-flag"></i></span>
    </a>
    <? if ($this->ils()->checkFunction('StorageRetrievalRequests')): ?>
      <a href="<?=$this->url('myresearch-storageretrievalrequests')?>" class="list-group-item<?=$this->active == 'storageRetrievalRequests' ? ' active' : ''?>">
        <?=$this->transEsc('Storage Retrieval Requests')?>
        <span class="pull-right"><i class="fa fa-archive"></i></span>
      </a>
    <? endif; ?>
    <? if ($this->ils()->checkFunction('ILLRequests')): ?>
    <a href="<?=$this->url('myresearch-illrequests')?>" class="list-group-item<?=$this->active == 'ILLRequests' ? ' active' : ''?>">
      <?=$this->transEsc('Interlibrary Loan Requests')?>
      <span class="pull-right"><i class="fa fa-exchange"></i></span>
    </a>
    <? endif; ?>
    <a href="<?=$this->url('myresearch-fines')?>" class="list-group-item<?=$this->active == 'fines' ? ' active' : ''?>">
      <?=$this->transEsc('Fines')?>
      <span class="pull-right"><i class="fa fa-usd"></i></span>
    </a>
    <a href="<?=$this->url('myresearch-profile')?>" class="list-group-item<?=$this->active == 'profile' ? ' active' : ''?>">
      <?=$this->transEsc('Profile')?>
      <span class="pull-right"><i class="fa fa-user"></i></span>
    </a>
  <? endif; ?>
  <a href="<?=$this->url('search-history')?>?require_login" class="list-group-item<?=$this->active == 'history' ? ' active' : ''?>">
    <?=$this->transEsc('history_saved_searches')?>
    <span class="pull-right"><i class="fa fa-search"></i></span>
  </a>
  <a href="<?=$this->url('myresearch-settings')?>" class="list-group-item<?=$this->active == 'settings' ? ' active' : ''?>">
    <?=$this->transEsc('My_Search_Settings')?>
    <span class="pull-right"><i class="fa fa-user"></i></span>
  </a>
  <a href="<?=$this->url('myresearch-favorite-institutions')?>" class="list-group-item<?=$this->active == 'favorite-institutions' ? ' active' : ''?>">
    <?=$this->transEsc('mylibraries')?>
    <span class="pull-right"><i class="fa fa-heart"></i></span>
  </a>
  <? if ($user = $this->auth()->isLoggedIn()): ?>
    <a href="<?=$this->url('myresearch-logout')?>" class="list-group-item">
      <?=$this->transEsc("Log Out")?>
      <span class="pull-right"><i class="fa fa-sign-out"></i></span>
    </a>
  <? endif; ?>
</ul>
<? if ($this->auth()->isLoggedIn() && $this->auth()->getManager()->supportsPasswordChange() || true /*
  @todo figure out how to add supportspasswordchange
  */): ?>
  <h4><?=$this->transEsc('Preferences')?></h4>
  <ul class="list-group">
    <a href="<?=$loginlink ?>" class="list-group-item" target="_blank">
      <?=$this->transEsc('changeaddress') ?>
      <span class="pull-right"><i class="fa fa-home"></i></span>
    </a>
    <a href="<?=$loginlink ?>" class="list-group-item" target="_blank">
      <?=$this->transEsc('Change Password') ?>
      <span class="pull-right"><i class="fa fa-lock"></i></span>
    </a>
  </ul>
<? endif; ?>
<? if ($this->userlist()->getMode() !== 'disabled' && $user = $this->auth()->isLoggedIn()): ?>
  <h4><?=$this->transEsc('Your Lists')?></h4>
  <ul class="list-group">
    <a href="<?=$this->url('myresearch-favorites')?>" class="list-group-item<?=$this->active == 'favorites' ? ' active' : ''?>">
      <?=$this->transEsc('Your Favorites')?>
      <span class="pull-right"><i class="fa fa-star"></i></span>
    </a>
    <? $lists = $user->getLists() ?>
    <? foreach ($lists as $list): ?>
        <a href="<?=$this->url('userList', array('id' => $list['id']))?>" class="list-group-item<?=$this->active == 'list' . $list['id'] ? ' active' : ''?>">
          <?=$this->escapeHtml($list['title'])?>
          <span class="badge"><?=$list->cnt?></span>
        </a>
    <? endforeach; ?>
    <a href="<?=$this->url('editList', array('id'=>'NEW'))?>" title="<?=$this->transEsc('Create a List') ?>" class="list-group-item">
      <?=$this->transEsc('Create a List') ?>
      <span class="pull-right"><i class="fa fa-plus"></i></span>
    </a>
  </ul>
<? endif ?>
