<?
// Set up page title:
$this->headTitle($this->translate('Photocopies'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Photocopies') . '</li>';
?>

<div class="<?= $this->layoutClass('mainbody') ?>">
  <h2><?= $this->transEsc('Photocopies') ?></h2>
  <?= $this->flashmessages(); ?>

  <?php if( sizeof($this->photoCopies) ): ?>
    <p><?=$this->transEsc('Your photocopies') ?></p>
    <?=$this->render('myresearch/photocopies/itemlist.phtml')?>
  <?php else: ?>
    <p><?=$this->transEsc('No photocopies') ?></p>
  <?php endif; ?>

</div>

<div class="<?= $this->layoutClass('sidebar') ?>">
  <?= $this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'photocopies')) ?>
</div>
