<?
// Set up page title:
$this->headTitle($this->translate('My_Search_Settings'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('My_Search_Settings') . '</li>';
?>

<div class="<?= $this->layoutClass('mainbody') ?>">
  <h2><?= $this->transEsc('My_Search_Settings') ?></h2>
  <?= $this->flashmessages(); ?>

  <form class="form-horizontal" action="" method="post" id="settings-form">
    <div class="form-group">
      <label class="col-sm-3 control-label" for="language"><?=$this->transEsc('Language') ?>:</label>
      <div class="col-sm-3">
        <select id="language" name="language" class="form-control">
          <? foreach ($this->optsLanguage as $languageKey => $languageLabel): ?>
            <option <? if ($languageKey == $this->language): ?>selected="selected"<? endif; ?> value="<?= $languageKey ?>">
              <?= $languageLabel ?>
            </option>
          <? endforeach; ?>
        </select>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-3 control-label" for="maxHits"><?=$this->transEsc('Max_Amount_Hits') ?>:</label>
      <div class="col-sm-3">
        <select id="maxHits" name="max_hits" class="form-control">
          <? foreach ($this->optsMaxHits as $maxHits): ?>
            <option <? if($maxHits == $this->max_hits): ?>selected="selected"<? endif; ?> value="<?= $maxHits ?>">
              <?= $maxHits ?>
            </option>
          <? endforeach; ?>
        </select>
      </div>
    </div>
    <? foreach($this->defaultSort as $defaultSort): ?>
        <div class="form-group">
          <label class="col-sm-3 control-label" for="defaultSort"><?=$this->transEsc('Sort') . ( $defaultSort['label'] ?  ' ' . $this->transEsc($defaultSort['label']) : '') ?>:</label>
          <div class="col-sm-3">
            <select id="defaultSort" name="default_sort[<?= $defaultSort['engine'] ?>]" class="form-control">
              <? foreach ($defaultSort['options'] as $defaultSortValue => $defaultSortLabel): ?>
                <option <? if($defaultSortValue == $defaultSort['selected']): ?>selected="selected"<? endif; ?> value="<?= $defaultSortValue ?>">
                  <?= $this->transEsc($defaultSortLabel) ?>
                </option>
              <? endforeach; ?>
            </select>
          </div>
        </div>
    <? endforeach; ?>
  </form>
</div>

<div class="<?= $this->layoutClass('sidebar') ?>">
  <?= $this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'settings')) ?>
</div>

<script type="text/javascript">
  swissbib.Settings.init();
</script>