<h1>Über swissbib Basel Bern, Kontakt</h1>
<h2>Über swissbib Basel Bern</h2>
<p>swissbib Basel Bern verzeichnet über 7 Mio. Titel aus über 200 <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">wissenschaftlichen Bibliotheken in Basel und Bern</a> (Bibliotheken der Universitäten Basel und Bern, Nationalbibliothek, einige Spezialbibliotheken sowie Fachhochschulbibliotheken).</p>
<p>Das Projekt wird getragen vom <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.informationsverbund.ch/21.0.html') ?>" target="_blank">Verbund IDS Basel Bern</a> und nutzt Infrastruktur und Know How des gesamtschweizerischen Metakatalogs <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('https://www.swissbib.ch') ?>" target="_blank" title="swissbib">swissbib</a>.</p>
<h2>Kontakt</h2>
<p>Gerne unterstützen wir Sie bei der Recherche und beim Bestellen in swissbib Basel Bern und nehmen Ihre Anregungen und Kritik entgegen:</p>
<ul>
    <li>Fragen zu Ihrem Konto: wenden Sie sich bitte an Ihre <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">Bibliothek</a></li>
    <li>Fragen zu bestimmten Werken: wenden Sie sich bitte an die besitzende <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">Bibliothek</a></li>
    <li>Fragen und Anregungen zur Suchoberfläche: swissbib-baselbern@unibas.ch (Ein Formular analog Feedback-Formular aleph wäre schön)</li>
</ul>

<h2>News</h2>
Abonnieren Sie unseren Blog

<h1>Was findet man in swissbib Basel Bern?</h1>
<p>In swissbib Basel Bern können zwei separate Datenbanken durchsucht werden:</p>
<h2>Bücher & mehr</h2>
    <ul>
    <li>Verschiedenste Medien wie Bücher/E-Books, Zeitschriften/E-Journals, Zeitungen, CD/DVD, Datenbanken etc. Verzeichnet sind die Titel dieser Medien, i.d.R. nicht einzelne Artikel oder Kapitel daraus.</li>
    <li>Retrodigitalisierte wissenschaftliche Zeitschriften aus der Schweiz (Projekt retro.seals), mit Direktzugang zu den digitalen Artikeltexten.</li>
    </ul>
<h2>Artikel & mehr</h2>
    <ul>
    <li>Artikel, Buchkapitel, Textbeiträge etc. aus zahlreichen E-Journals, E-Books und Datenbanken, die von den Universitäten Basel bzw. Bern zur Verfügung gestellt werden. In den meisten Fällen kann von einem Universitätsstandort aus direkt auf den elektronischen Volltext zugegriffen werden.</li>
    <li>Elektronische Ressourcen, die frei im Internet und somit auch ausserhalb der Universitäten Basel und Bern zugänglich sind.</li>
    </ul>
<p>Titel, zu denen kein direkter Volltextzugang besteht, können Sie via <i class="fa fa-external-link"></i> SFX-Services bei Ihrer Bibliothek bestellen.</p>


<!--<h1>Über swissbib</h1>

<p>swissbib Basel Bern ist der neue Katalog der Bibliotheken in Basel und Bern. Das Projekt wird getragen vom Verbund IDS Basel Bern und nutzt Infrastruktur und Know-How des gesamtschweizerischen Metakatalogs
    <a href="http://www.swissbib.ch" target="_blank">swissbib</a>.
</p>

<h2>Kontakt</h2>
<ul class="list">
    <li>Für Fragen zu Ihrem Konto wenden Sie sich bitte an <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/" target="_blank">Ihre Bibliothek</a>.</li>
    <li>Für Fragen zu bestimmten Werken wenden Sie sich bitte an die <a href="<?= $this->url('libraries-index') ?>">besitzende Bibliothek</a>.</li>
    <li>Kontakt swissbib Basel Bern: E-Mail an <a href="mailto:swissbib-baselbern@unibas.ch">swissbib-baselbern@unibas.ch</a> oder Kommentar im <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">Blog</a>.</li>
</ul>
                                
<h2>News</h2>
<p>In unserem <a href="http://swissbib-baselbern.blogspot.ch" target="_blank">Blog</a></p>
</br>
<h1>Datenbestand</h1>
<p>swissbib Basel Bern besteht aus zwei separaten Katalogen:</p>
<h2>Bücher &amp; mehr</h2>
<ul class="list">
<li>Bestände aller wissenschaftlichen Bibliotheken in <a href="<?= $this->url('libraries-index') ?>#nav_0">Basel</a> und <a href="<?= $this->url('libraries-index') ?>#nav_1">Bern</a> inkl. Nationalbibliothek sowie
    Fachhochschulbibliotheken</li>
<li><a href="http://retro.seals.ch" target="_blank">retro.seals</a>: retrodigitalisierte wissenschaftliche Zeitschriften
</li>  
</ul>    
<h2>Artikel &amp; mehr</h2>
<ul class="list">
    <li>In <i>Artikel &amp; mehr</i> finden Sie die Inhalte von zahlreichen e-Journals, e-Books und Fachdatenbanken, die von den Universitätsbibliotheken Basel bzw. Bern lizenziert wurden. In den meisten Fällen kann von einem Universitätsstandort aus direkt auf den elektronischen Volltext (Journal-Artikel, e-Book-Kapitel etc.) zugegriffen werden.</li>
    <li>Zusätzlich enthält <i>Artikel &amp; mehr</i> elektronische Ressourcen, die frei im Internet zugänglich sind.</li>
    <li>Titel, zu denen kein direkter Volltextzugang besteht, können Sie via <img src="<?= $this->basePath('themes/swissbib/images/sfx.gif') ?>"> <i>Bibliotheksservice</i> bei der Universitätsbibliothek Basel oder Bern bestellen.</li>
    <li>Für mehr Informationen siehe die <a href="http://www.proquest.com/products-services/The-Summon-Service.html" target="_blank">Seite des Anbieters ProQuest</a>.</li>
</ul>-->
