<h1>Kosten / Lieferfristen</h1>
<h2>IDS-Kurierdienst</h2>
<p>Medien aus IDS-Kurierbibliotheken können zum Abholen an alle anderen IDS-Kurierbibliotheken bestellt werden und an jeder IDS-Kurierbibliothek auch zurückgebracht werden:</p>
<ul>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a100/?S=1') ?>" target="_blank">Basel UB Hauptbibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a140/?S=1') ?>" target="_blank">Basel UB Medizin</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a125/?S=1') ?>" target="_blank">Basel UB Wirtschaft - SWA</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b400') ?>" target="_blank">Bern UB Zentralbibliothek/Speichermagazin</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b410') ?>" target="_blank">Bern UB Basisbibliothek Unitobler</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b500') ?>" target="_blank">Bern UB Bibliothek vonRoll</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/index.php?id=1218') ?>" target="_blank">Luzern Zentral- und Hochschulbibliothek Sempacherstrasse</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/index.php?id=1219') ?>" target="_blank">Luzern Zentral- und Hochschulbibliothek UNI/PH-Gebäude</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.unisg.ch/wissen/bibliothek') ?>" target="_blank">St. Gallen HSG</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.sg.ch/home/kultur/kantonsbibliothek.html') ?>" target="_blank">St. Gallen Kantonsbibliothek Vadiana</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zb.uzh.ch') ?>" target="_blank">Zürich Zentralbibliothek</a></li>
</ul>

<p>Zusätzliche Berner Bibliotheken, die einen Kurier mit den genannten Basler IDS-Kurierbibliotheken anbieten:</p>
<ul>
<li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b452') ?>" target="_blank">Bern UB Fachbereichsbibliothek Bühlplatz</a></li>
<li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b465') ?>" target="_blank">Bern UB Juristische Bibliothek</a> (nur Abholort)</li>
<li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b415') ?>" target="_blank">Bern UB Schweizerische Osteuropabibliothek</a></li>
<li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zb.unibe.ch/aleph/biblinfo/b517.html') ?>" target="_blank">Bern PH Weiterbildung und Medienbildung</a></li>
</ul>

<p><strong>Kosten:</strong> Fr. 5.- pro Dokument. Barzahlung bei Abholung. Für nicht abgeholte Dokumente wird der Tarif trotzdem in Rechnung gestellt.</p>
<p><strong>Lieferfrist:</strong> Die von Ihnen online bestellten Dokumente werden vom IDS-Kurier täglich (ohne Samstag) abgeholt und im Normalfall innerhalb von zwei Arbeitstagen an die gewünschte Abholbibliothek geliefert. Dort bleiben die Medien während einer Woche zum Abholen bereitgestellt.</p>
<h2>Kurierdienste Basel und Bern</h2>
<p>Die ortsinternen Kurierdienste in <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/ausleihe/kurier-und-fernleihe') ?>" target="_blank" title="Basler Kurier">Basel</a> und <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/bestellen__ausleihen/kurier') ?>" target="_blank" title="Berner Kurier">Bern</a> sind kostenlos.
<h2>Postversand von Dokumenten an Ihre Adresse aus UB Basel und UB Bern</h2>
<p><strong>Kosten:</strong> Fr. 12.- pro Dokument. </p>
<p><strong>Lieferfrist:</strong> Die Bestellungen werden von Montag bis Freitag innerhalb von 24 Stunden bearbeitet und versandt.</p>
<h2>Kopienversand (per Post oder elektronisch) aus UB Basel und UB Bern</h2>
<p><strong>Kosten Privatkunden:</strong> Fr. 8.- pro 20 Seiten.</p>
<p><strong>Kosten Firmenkunden:</strong> Fr. 24.- pro Kopierauftrag bis 20 Seiten plus Fr. 8.- pro weitere 20 Seiten.
<p><strong>Lieferfrist:</strong> Bearbeitung Montag bis Freitag innerhalb von 24 Stunden.</p>
<p>Die Kosten werden Ihnen vom IDS Basel Bern in Rechnung gestellt.</p>
<p><strong>Kontakt:</strong> Inkasso-/Clearingstelle UB ZB Bern, +41 (0)31 631 92 21, <a href="mailto:clearing@ub.unibe.ch">clearing@ub.unibe.ch</a></p>
<h2>Versand an Ihre Adresse aus anderen Bibliotheken</h2>
<p>Für die Bedingungen der anderen Bibliotheken siehe auf der jeweiligen Webseite: <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">Bibliothek</a></p>
