<h1>Kosten, Lieferfristen</h1>
<h2>IDS-Kurierdienst</h2>
<p>Fr. 5.- pro Dokument. Barzahlung bei Abholung. Für nicht abgeholte Dokumente wird der Tarif trotzdem in Rechnung gestellt.</p>
<p>Kostenlos: <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/ausleihe/kurier-und-fernleihe') ?>" target="_blank" title="Basler Kurier">Basler Kurier</a>, <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/bestellen__ausleihen/kurier') ?>" target="_blank" title="Berner Kurier">Berner Kurier</a></p>
<h2>Postversand von Dokumenten an Ihre Adresse aus UB Basel und UB Bern</h2>
<p>Fr. 12.- pro Dokument. Die Bestellungen werden von Montag bis Freitag innerhalb von 24 Stunden bearbeitet und versandt.</p>
<h2>Kopienversand (per Post oder elektronisch) aus UB Basel und UB Bern</h2>
<p><strong>Privatkunden:</strong> 	Fr. 8.- pro Kopierauftrag bis 20 Seiten. Bearbeitung Montag bis Freitag innerhalb von 24 Stunden.</p>
<p><strong>Firmenkunden:</strong> Fr. 24.- pro Kopierauftrag bis 20 Seiten plus Fr. 8.- pro weitere 20 Seiten. Bearbeitung Montag bis Freitag innerhalb von 24 Stunden.</p>
<p>Die Kosten werden Ihnen vom IDS Basel Bern in Rechnung gestellt.</p>
<p><strong>Kontakt:</strong> Inkasso-/Clearingstelle UB ZB Bern, +41 (0)31 631 92 21, clearing@ub.unibe.ch</p>

<p>Für Reproduktionen aus dem historischen Bestand siehe die entsprechenden Seiten der <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/reprografie/reproduktionen-hist-bestand') ?>" target="_blank">UB Hauptbibliothek Basel</a> und der <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/bestellen__ausleihen/tarif') ?>" target="_blank">UB ZB Bern</a></p>

<h2>Versand an Ihre Adresse aus anderen Bibliotheken</h2>
<p>Für die Bedingungen der anderen Bibliotheken siehe auf der jeweiligen Webseite: <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">Bibliothek</a></p>
