<h1>Speichern, bestellen</h1>
<h2>Speichern, weiterverarbeiten</h2>
<p><i class="fa fa-list-ul"></i> Diesen Titel auf einer Merkliste speichern</p>
<p><i class="fa fa-plus-square"></i> Diese Suchanfrage speichern</p>
<p><i class="fa fa-rss"></i> Neue Einträge zu dieser Suchanfrage per Feed gemeldet bekommen</p>
<p><i class="fa fa-envelope"></i> Diesen Titel/diese Trefferliste per E-Mail versenden</p>
<p><i class="fa fa-share"></i> Diesen Titel/diese Trefferliste in ein Literaturverwaltungsprogramm exportieren</p>
<p><i class="fa fa-pencil"></i> Zitiervorschläge für diesen Titel anzeigen</p>

<h2>Bestellen</h2>
[Film Bestellen verlinken/einbetten] Screenshot dann ev. nicht mehr nötig?
<ul>
<li>Klicken Sie auf den Titel des Mediums, das Sie bestellen möchten.</li>
<li>Wählen Sie unter Exemplare eine Bibliothek aus.</li>
<li>Klicken Sie Anmelden unter dem Bibliotheksnamen (falls Sie noch nicht angemeldet sind).</li>
<li>Wählen Sie Bestellen oder Kopie bestellen.</li>
<li>Je nach Bibliothek werden unterschiedliche Abhol- und Liefermöglichkeiten angeboten. Siehe Details unter Kosten, Lieferfristen [Link]</li>
<li>Wenn keine dieser Optionen angezeigt wird, kann das Werk nicht online bestellt werden. Ein Klick auf das Icon <i class="fa fa-info-circle"></i> unterhalb Standort zeigt Öffnungszeiten und Adresse der Bibliothek.</li>
</ul>




<!--<h1>Speichern</h1>
<table class="table table-striped">
	<tbody>
	<tr>
		<td><img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_notepad_add.gif') ?>"
                 alt="<?= $this->transEsc('memorizelistadd')?>"
                 title="<?= $this->transEsc('memorizelistadd')?>">
        </td>
		<td>Titel in einer Ihrer <strong>Merklisten</strong> speichern</td>
	</tr>
    <tr>
		<td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_rss.gif') ?>"
                 alt="<?= $this->transEsc('Get RSS Feed')?>"
                 title="<?= $this->transEsc('Get RSS Feed')?>">
        </td>
		<td>Neue Einträge zu Ihrer Suche per <strong>Feed</strong> gemeldet bekommen</td>
	</tr>
    <tr>
        <td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_perma.gif') ?>"
                 alt="<?= $this->transEsc('Cite this')?>"
                 title="<?= $this->transEsc('Cite this')?>">
        </td>
        <td>Treffer <strong>zitieren</strong></td>
    </tr>
	<tr>
		<td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_print.gif') ?>"
                 alt="<?= $this->transEsc('Print')?>"
                 title="<?= $this->transEsc('Print')?>"">
        </td>
		<td>Treffer <strong>drucken</strong></td>
	</tr>
	<tr>
		<td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_send.gif') ?>"
                 alt="<?= $this->transEsc('Email this')?>"
                 title="<?= $this->transEsc('Email this')?>">
        </td>
		<td>Treffer als <strong>E-Mail</strong> versenden</td>
	</tr>

	<tr>
		<td>
            <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_pagefunctions_save.gif') ?>"
                 alt="<?= $this->transEsc('Export Items')?>"
                 title="<?= $this->transEsc('Export Items')?>">
        </td>
		<td>Treffer in verschiedenen Formaten <strong>exportieren</strong></td>
	</tr>
	</tbody>
</table>

<h2>Bestellen</h2>
<div class="row">
  <div class="col-sm-6">
    <a href="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/de/order.png') ?>" class="help">
      <img class="img-responsive" src="<?= $this->basePath('themes/swissbibmulti/images/HelpPage/de/order_small.png') ?>" alt="Zoom">
    </a>
  </div>
  <div class="col-sm-6">
    <ul class="list">
      <li>Klicken Sie auf den Titel.</li>
      <li>Wählen Sie unter <i>Exemplare</i> eine Bibliothek aus.</li>
      <li>Klicken Sie <i>Anmelden</i> unter dem Bibliotheksnamen.</li>
      <li>Wählen Sie <i>Bestellen</i> oder <i>Kopie bestellen</i>.</li>
      <li>Wenn keine dieser Optionen angezeigt wird, kann das Werk nicht online bestellt werden. Klick auf das Icon
        <img src="<?= $this->basePath('themes/swissbibmulti/css/img/icon_link-external.gif') ?>" alt="Bibliotheksinformation"> unterhalb Standort zeigt Öffnungszeiten und Adresse der Bibliothek.</li>
    </ul>
  </div>
</div>-->