<div class="home-content-box">
    <h2 class="lead">Redesign 2015</h2>
    <p>A partir du 5 mai 2015, swissbib Bâle Berne adaptera automatiquement son affichage à la taille de l’écran du terminal de réception. Ainsi il n’y aura plus de restrictions, et les recherches pourront aussi bien se faire sur l’ordinateur, qu’à partir d’une tablette ou d’un smartphone.</p>

    <a href="http://swissbib-baselbern.blogspot.com/2015/05/redesign-2015.html" target="_blank" class="btn btn-link">Weiterlesen</a>
</div>