<h1>Fees / delivery times</h1>
<h2>IDS courier service</h2>
<p>Items from libraries offering a courier service can be sent to any other courier library for pickup or return:</p>
<ul>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a100/?S=1') ?>" target="_blank">Basel UB Hauptbibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a140/?S=1') ?>" target="_blank">Basel UB Medizin</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken/a125/?S=1') ?>" target="_blank">Basel UB Wirtschaft - SWA</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b400') ?>" target="_blank">Bern UB Zentralbibliothek/Speichermagazin</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b410') ?>" target="_blank">Bern UB Basisbibliothek Unitobler</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b500') ?>" target="_blank">Bern UB Bibliothek vonRoll</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/index.php?id=1218') ?>" target="_blank">Luzern Zentral- und Hochschulbibliothek Sempacherstrasse</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zhbluzern.ch/index.php?id=1219') ?>" target="_blank">Luzern Zentral- und Hochschulbibliothek UNI/PH-Gebäude</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.unisg.ch/wissen/bibliothek') ?>" target="_blank">St. Gallen HSG</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.sg.ch/home/kultur/kantonsbibliothek.html') ?>" target="_blank">St. Gallen Kantonsbibliothek Vadiana</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zb.uzh.ch') ?>" target="_blank">Zürich Zentralbibliothek</a></li>
</ul>

<p>Additional libraries in Bern who offer a courier services with the courier libraries from Basel:</p>
<ul>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b452') ?>" target="_blank">Bern UB Fachbereichsbibliothek Bühlplatz</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b465') ?>" target="_blank">Bern UB Juristische Bibliothek</a> (pickup only)</li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/b415') ?>" target="_blank">Bern UB Schweizerische Osteuropabibliothek</a></li>
    <li><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.zb.unibe.ch/aleph/biblinfo/b517.html') ?>" target="_blank">Bern PH Weiterbildung und Medienbildung</a></li>
</ul>

<p><strong>Fees:</strong> CHF. 5.- per item. Fee is paid cash at pickup. Items not picked up will still be charged CHF 5.-.</p>
<p><strong>Delivery times:</strong> Items ordered online are picked-up daily via IDS courier (except on Saturdays) and normally delivered within two working days to the pick-up library of your choice. They can be picked up within one week of delivery.</p>
<h2>Courier service Basel and Bern</h2>
<p>The courier service within <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/ub-hauptbibliothek/dienstleistungen/ausleihe/kurier-und-fernleihe') ?>" target="_blank" title="Basler Kurier">Basel</a> und <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/bestellen__ausleihen/kurier') ?>" target="_blank" title="Berner Kurier">Bern</a> is free of charge.
<h2>Postal delivery to your address from UB Basel and UB Bern</h2>
<p><strong>Fees:</strong> CHF 12.- per item. </p>
<p><strong>Delivery times:</strong> Orders are processed and sent within 24 hours of receipt (Monday to Friday).</p>
<h2>Ordering photocopies/electronic copies (via post or e-mail) from UB Basel and UB Bern</h2>
<p><strong>Private customers:</strong> CHF 8.- per 20 pages.</p>
<p><strong>Corporate customers:</strong> CHF 24.- per order up to 20 pages plus CHF 8.- per any 20 additional pages.
<p><strong>Delivery times:</strong> Orders are process Monday to Friday within 24 hours of receipt.</p>
<p>Costs are charged to your library account by IDS Basel Bern.</p>
<p><strong>Contact:</strong> Clearing UB ZB Bern, +41 (0)31 631 92 21, <a href="mailto:clearing@ub.unibe.ch">clearing@ub.unibe.ch</a></p>
<h2>Delivery to your postal address from other libraries</h2>
<p>Please check conditions of other libraries from their respective webpages: <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">Library</a></p>