<h1>Benutzerkonto / My swissbib</h1>
<p>Ihr Benutzerkonto (<a href="<?= $this->url('myresearch-userlogin') ?>">My swissbib</a>) informiert Sie über Ihre Ausleihen, Bestellungen sowie Erinnerungen/Gebühren. Über das Konto können Sie ausgeliehene Medien verlängern sowie Ihre persönlichen <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://aleph.unibas.ch/F/?func=file&file_name=login-session&con_lng') ?>"> Daten</a> und <a href="<?= $this->url('myresearch-settings'); ?>"><?= $this->transEsc('My_Search_Settings') ?></a> ändern.</p>
<h2>Noch kein Konto?</h2>
<p><a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://aleph.unibas.ch/F/?func=bor-new-0') ?>" target="_blank"><?= $this->transEsc('Create New Account') ?></a> (oder vor Ort in einer der IDS-Bibliotheken in <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken') ?>" target="_blank">Basel</a> oder <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/berner_ids_bibliotheken') ?>" target="_blank">Bern</a>)</p>
<p>Benutzerausweise einer anderen <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.informationsverbund.ch/21.0.html') ?>" target="_blank" title="IDS-Bibliothek">IDS-Bibliothek</a> sind auch für swissbib Basel Bern <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.informationsverbund.ch/6.0.html') ?>" target="_blank">gültig</a>, ebenso die Studierenden- und Mitarbeitendenausweise der Universitäten Basel und Bern.</p>
<h2>Passwort vergessen</h2>
<p>Kontaktieren Sie Ihre <a href="<?= $this->basePath('Libraries') ?>" title="Liste der Institutionen">Bibliothek</a>.</p>
<h2>Benutzerausweis verloren</h2>
<p>Bitte kommen Sie bei einer der IDS-Bibliotheken vorbei: <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibas.ch/bibliotheksnetz/verbund-basel/bibliotheken-im-verbund/liste-der-bibliotheken') ?>" target="_blank">Region Basel</a>, <a href="<?= $this->redirectProtocolWrapper()->getWrappedURL('http://www.ub.unibe.ch/content/ueber_uns/bibliotheken_der_ub/berner_ids_bibliotheken') ?>" target="_blank">Region Bern</a>. Ein Ersatz ist kostenpflichtig und wir benötigen dazu einen amtlichen Ausweis.</p>
<h1>Persönliche Einstellungen</h1>
<h2>Gespeicherte Suchen</h2>
<p>Wenn Sie nicht angemeldet sind, werden Ihre Suchen gespeichert, bis Sie den Browser schliessen. Wenn Sie sich anmelden, können Sie Ihre Suchanfragen längerfristig speichern, um sie bei Bedarf zu wiederholen.</p>
<h2>Einstellungen</h2>
<p>Sie können die Sprache der Suchoberfläche, die angezeigte Anzahl Treffer pro Seite sowie das Sortierungskriterium für die Trefferliste nach Ihren Vorlieben einstellen. Die Einstellungen sind nur wirksam, wenn Sie angemeldet sind.</p>
<h2>Favoriten</h2>
<p>Um eine Bibliothek als Ihren Favoriten zu markieren, benutzen Sie entweder die Suche unter <a href="<?=$this->url('myresearch-favorite-institutions')?>"><?=$this->transEsc('mylibraries')?></a> oder klicken Sie in einer Titelanzeige bei der entsprechenden Bibliothek auf <i class="fa fa-heart-o"></i>. In der Liste der Suchergebnisse sind Ihre Favoriten-Bibliotheken mit <i class="fa fa-heart"></i> markiert. Wenn Sie angemeldet sind können Sie die Suchergebnisse nach Vorhandensein in Ihren Favoritenbibliotheken filtern.</p>
<h2>Merklisten</h2>
<p>Wenn Sie sich anmelden, können Sie Titel auf Merklisten speichern, indem Sie auf <i class="fa fa-list-ul"></i> klicken.</p>

<!--<h1>Log in</h1>
<p>If you have a valid library card for IDS Basel Bern, log in as usual.</p>
<!--
<p>If you have a valid library card for any one of the following partner libraries, log in as usual:</p>
<ul class="list">
    <li>IDS Basel Bern</li>
    <li>IDS Luzern</li>
    <li>IDS St. Gallen</li>
    <li>NEBIS</li>
    <li>St. Galler Bibliotheksnetz</li>
</ul>

<h2>No account yet?</h2>
<p><a href="http://aleph.unibas.ch/F/?func=bor-new-0&CON_LNG=ENG"
      target="_blank"><?/*= $this->transEsc('Create New Account') */?></a></p>

<h2>Why log in?</h2>
<p>To use loan functions and lists and to save searches, favorites and preferences.</p>

<h2>Forgot your password?</h2>
<p>Please contact <a href="http://www.ub.unibas.ch/ids-basel-bern/ausleihbibliotheken/" target="_blank">your library</a>.
</p>

<h2>Profile</h2>
<p><a href="http://aleph.unibas.ch/F/?func=LOGIN-PAGE" target="_blank">Change password, address etc.</a></p>

<h2>Why log out?</h2>
<p>If you are using a public computer you should log out so nobody else can use your account.</p>
</br>
<h1>My swissbib</h1>
<h2>Saved searches</h2>
<p>When you are not logged in, your searches are saved until you close the browser. You can repeat a search or - if you
    log in - save it permanently.</p>

<h2>Favorites</h2>
<p>To mark a library as favorite, either use <i>My swissbib - Favorites</i> or click on the <img
        src="<?/*= $this->basePath('themes/swissbib/images/icon_favorit_library.gif') */?>"
        alt="<?/*= $this->transEsc('mylibraries.add')*/?>"
        title="<?/*= $this->transEsc('mylibraries.add')*/?>"> in the catalog. In your search results, these libraries are marked with a <img
        src="<?/*= $this->basePath('/themes/swissbib/images/icon_favorit_library.gif') */?>"
        alt="Favorit"> and can be used as filters.</p>

<h2>Lists</h2>
<ul class="list">
    <li>When you are logged in you can save titles on lists by clicking on this sign: <br />
        <img src="<?/*= $this->basePath('themes/swissbibmulti/css/img/icon_notepad_add.gif') */?>"
             alt="<?/*= $this->transEsc('memorizelistadd')*/?>"
             title="<?/*= $this->transEsc('memorizelistadd')*/?>">
    </li>
    <li>If you make a new list while saving a title you have to click <i>Save</i> twice.</li>
    <li>Public = List visible for everybody who knows the URL</li>
    <li>Private = List visible only for you</li>
</ul>

<h2>Preferences</h2>
<p>Language of the catalog interface, number of titles per page</p>

<h2>Account IDS Basel Bern</h2>
<p>Loan functions</p>
-->