<?
/**
 * Record detail view
 */

  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
      $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  $lastSearchUrl = $this->getextendedlastsearchlink()->getEscapedLinkOnly(); //@todo necessary?

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';
  $this->layout()->title = $this->driver->getShortTitle();
?>

<? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <ul class="pager hidden-print">
    <? if ($this->scrollData['previousRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>">&laquo; <?=$this->transEsc('Prev')?></a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>
    <span><?=$this->escapeHtml($this->scrollData['currentPosition']) . ' ' . $this->transEsc('of') . ' ' . number_format($this->escapeHtml($this->scrollData['resultTotal'])) . ' ' . $this->transEsc('results') ?></span>
    <? if ($this->scrollData['nextRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>"><?=$this->transEsc('Next')?> &raquo;</a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
  </ul>
<? endif; ?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <?=$this->record($this->driver)->getToolbar()?>

  <div class="record recordId source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" id="record">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id" />
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
    <?=$this->flashmessages()?>
    <?=$this->record($this->driver)->getCoreMetadata()?>
  </div>

  <? if (count($this->tabs) > 0): ?>
    <a name="tabnav"></a>
    <ul class="recordTabs nav nav-tabs">
      <? foreach ($this->tabs as $tab => $obj): ?>
      <? // add current tab to breadcrumbs if applicable:
        $desc = $obj->getDescription();
        $isCurrent = (strtolower($this->activeTab) == strtolower($tab));
        if ($isCurrent) {
          $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
          $activeTabObj = $obj;
        }

        $tab_classes = array();
        if ($isCurrent) $tab_classes[] = 'active';
        if (!$obj->isVisible()) $tab_classes[] = 'hidden';
        $tab_classes[] = $this->record($this->driver)->getTabVisibility($tab);
      ?>

      <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
        <a id="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><?=$this->transEsc($desc)?></a>
      </li>
      <? endforeach; ?>
    </ul>
  <? endif; ?>

  <div class="tab-content" id="record-tabs">
    <div class="tab-pane active" id="<?=$this->activeTab ?>-tab">
      <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
    </div>
  </div>

  <span class="Z3988" title="<?=$this->escapeHtmlAttr($this->driver->getOpenURL())?>"></span>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->render('record/sidebar/sidebar');?>
</div>
